package presentacion.Materiales;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelo.Material;
import negocio.MaterialBO;

/**
 *
 * @author vidireria
 */
public class frmMaterialesExistentes extends javax.swing.JFrame {

    private MaterialBO materialBO = new MaterialBO();
    private DefaultTableModel modeloTabla;
    TableRowSorter sorter;

    /**
     * Creates new form frmRegistrarMateriales
     */
    public frmMaterialesExistentes() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        inicializarTabla();
        editarTabla();

        DefaultTableModel model = (DefaultTableModel) tblMateriales.getModel();
        sorter = new TableRowSorter<>(model);
        tblMateriales.setRowSorter(sorter);

        tblMateriales.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                actualizarTextoBotonEstado();
            }
        });

        activarFiltroEnTiempoReal();
    }

    private void inicializarTabla() {
        modeloTabla = new DefaultTableModel(
                new Object[]{"ID", "Descripción", "Precio", "Stock", "Tipo", "Unidad", "Estado"},
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblMateriales.setModel(modeloTabla);
        cargarMateriales();
    }

    public void cargarMateriales() {
        modeloTabla.setRowCount(0);

        try {
            List<Material> lista = materialBO.obtenerTodos();

            for (Material m : lista) {
                modeloTabla.addRow(new Object[]{
                    m.getIdMaterial(),
                    m.getDescripcion(),
                    m.getPrecio(),
                    m.getStockActual(),
                    m.getTipo(),
                    m.getUnidadMedida(),
                    m.getEstadoActivo() ? "ACTIVO" : "INACTIVO"

                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar los materiales: " + ex.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        }

        tblMateriales.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int col) {

                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);

                // Convertir row del JTable al row del modelo (por el sorter)
                int modelRow = tblMateriales.convertRowIndexToModel(row);

                String estado = table.getModel().getValueAt(modelRow, 6).toString();

                if (estado.equals("INACTIVO")) {
                    c.setForeground(Color.GRAY);
                } else {
                    c.setForeground(Color.BLACK);
                }

                return c;
            }
        });


        // Orden ACTIVO va primero, INACTIVO al final        
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(modeloTabla);

        sorter.setComparator(6, (o1, o2) -> {
            String e1 = o1.toString();
            String e2 = o2.toString();

            if (e1.equals(e2)) {
                return 0;
            }
            if (e1.equals("ACTIVO")) {
                return -1; // ACTIVO va arriba
            }
            return 1; // INACTIVO va abajo
        });

        tblMateriales.setRowSorter(sorter);

// Aplicar orden
        List<RowSorter.SortKey> order = new ArrayList<>();
        order.add(new RowSorter.SortKey(6, SortOrder.ASCENDING));
        sorter.setSortKeys(order);
        sorter.sort();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelSubtitulo = new javax.swing.JPanel();
        MaterialesExitentes = new javax.swing.JLabel();
        btnNuevoMaterial = new javax.swing.JButton();
        Buscar = new javax.swing.JLabel();
        lblListadoMateriales = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMateriales = new javax.swing.JTable();
        btnCambiarEstado = new javax.swing.JButton();
        txtBuscarMaterial = new javax.swing.JTextField();
        btnEditarMaterial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelTitulo.setBackground(new java.awt.Color(0, 19, 90));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar materiales");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        panelSubtitulo.setBackground(new java.awt.Color(0, 81, 168));

        MaterialesExitentes.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        MaterialesExitentes.setForeground(new java.awt.Color(255, 255, 255));
        MaterialesExitentes.setText("Listado materiales existentes");

        javax.swing.GroupLayout panelSubtituloLayout = new javax.swing.GroupLayout(panelSubtitulo);
        panelSubtitulo.setLayout(panelSubtituloLayout);
        panelSubtituloLayout.setHorizontalGroup(
            panelSubtituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubtituloLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(MaterialesExitentes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSubtituloLayout.setVerticalGroup(
            panelSubtituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubtituloLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(MaterialesExitentes)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnNuevoMaterial.setBackground(new java.awt.Color(0, 81, 168));
        btnNuevoMaterial.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnNuevoMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-24.png"))); // NOI18N
        btnNuevoMaterial.setText("Nuevo material");
        btnNuevoMaterial.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNuevoMaterial.setBorderPainted(false);
        btnNuevoMaterial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevoMaterial.setDefaultCapable(false);
        btnNuevoMaterial.setFocusPainted(false);
        btnNuevoMaterial.setRequestFocusEnabled(false);
        btnNuevoMaterial.setRolloverEnabled(false);
        btnNuevoMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoMaterialActionPerformed(evt);
            }
        });

        Buscar.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        Buscar.setForeground(new java.awt.Color(15, 105, 196));
        Buscar.setText("Buscar Material");

        lblListadoMateriales.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblListadoMateriales.setForeground(new java.awt.Color(15, 105, 196));
        lblListadoMateriales.setText("Listado de Materiales");

        tblMateriales.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Descripcion", "Tipo material", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tblMateriales);

        btnCambiarEstado.setBackground(new java.awt.Color(255, 153, 0));
        btnCambiarEstado.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCambiarEstado.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarEstado.setText("Inactivar");
        btnCambiarEstado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCambiarEstado.setBorderPainted(false);
        btnCambiarEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCambiarEstado.setDefaultCapable(false);
        btnCambiarEstado.setFocusPainted(false);
        btnCambiarEstado.setRequestFocusEnabled(false);
        btnCambiarEstado.setRolloverEnabled(false);
        btnCambiarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarEstadoActionPerformed(evt);
            }
        });

        txtBuscarMaterial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnEditarMaterial.setBackground(new java.awt.Color(97, 85, 245));
        btnEditarMaterial.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEditarMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit-20.png"))); // NOI18N
        btnEditarMaterial.setText("Editar");
        btnEditarMaterial.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEditarMaterial.setBorderPainted(false);
        btnEditarMaterial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditarMaterial.setDefaultCapable(false);
        btnEditarMaterial.setFocusPainted(false);
        btnEditarMaterial.setRequestFocusEnabled(false);
        btnEditarMaterial.setRolloverEnabled(false);
        btnEditarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblListadoMateriales)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNuevoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCambiarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(230, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(35, 35, 35))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblListadoMateriales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCambiarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 292, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoMaterialActionPerformed
        frmRegistrarMateriales frm = new frmRegistrarMateriales();
        frm.setVisible(true);
    }//GEN-LAST:event_btnNuevoMaterialActionPerformed

    private void btnCambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarEstadoActionPerformed
        int fila = tblMateriales.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un material para cambiar su estado.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int idMaterial = (int) modeloTabla.getValueAt(fila, 0);
            String estadoActual = (String) modeloTabla.getValueAt(fila, 6);

            if (estadoActual.equals("ACTIVO")) {
                btnCambiarEstado.setText("Inactivar");
            } else {
                btnCambiarEstado.setText("Activar");
            }

            btnEditarMaterial.setEnabled(estadoActual.equals("ACTIVO"));

            boolean activar = estadoActual.equals("INACTIVO");
            String accion = activar ? "Activar" : "Inactivar";

            int confirm = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de " + accion.toLowerCase() + " el material " + idMaterial + "?",
                    "Confirmar Cambio de Estado", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                if (materialBO.cambiarEstado(idMaterial, activar)) {
                    JOptionPane.showMessageDialog(this, "Estado actualizado a " + (activar ? "ACTIVO" : "INACTIVO") + " correctamente.");
                    cargarMateriales();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al actualizar el estado.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error de base de datos: " + ex.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnCambiarEstadoActionPerformed

    private void btnEditarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMaterialActionPerformed
        int fila = tblMateriales.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un material para modificar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int id = (int) modeloTabla.getValueAt(fila, 0);
            Material materialAEditar = materialBO.obtenerPorId(id);

            if (materialAEditar != null) {
                abrirFormularioEdicion(materialAEditar);
            } else {
                JOptionPane.showMessageDialog(this, "Material no encontrado en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al consultar material: " + ex.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarMaterialActionPerformed

    //filtro para buscar materiales
    private void activarFiltroEnTiempoReal() {
        txtBuscarMaterial.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {

            private void filtrar() {
                String texto = txtBuscarMaterial.getText().trim();

                if (texto.length() == 0) {
                    sorter.setRowFilter(null);
                } else {
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto));
                }
            }

            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                filtrar();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                filtrar();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                filtrar();
            }
        });
    }

    /**
     * Función para abrir el formulario de registro y edición.
     */
    private void abrirFormularioEdicion(Material materialAEditar) {
        frmRegistrarMateriales frm = new frmRegistrarMateriales(materialAEditar);
        frm.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                cargarMateriales();
            }
        });

        frm.setVisible(true);
    }

    private void editarTabla() {
        JTableHeader headerCotizaciones = tblMateriales.getTableHeader();
        headerCotizaciones.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                Component comp = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                comp.setBackground(new Color(15, 105, 196)); // Fondo azul
                comp.setForeground(Color.WHITE);             // Texto blanco
                return comp;
            }
        });
    }

    private void actualizarTextoBotonEstado() {
        int fila = tblMateriales.getSelectedRow();

        if (fila == -1) {
            btnCambiarEstado.setText("Cambiar Estado");
            return;
        }

        String estado = modeloTabla.getValueAt(fila, 6).toString();

        if (estado.equalsIgnoreCase("ACTIVO")) {
            btnCambiarEstado.setText("Inactivar");
        } else {
            btnCambiarEstado.setText("Activar");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMaterialesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMaterialesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMaterialesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMaterialesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMaterialesExistentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Buscar;
    private javax.swing.JLabel MaterialesExitentes;
    private javax.swing.JButton btnCambiarEstado;
    private javax.swing.JButton btnEditarMaterial;
    private javax.swing.JButton btnNuevoMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListadoMateriales;
    private javax.swing.JPanel panelSubtitulo;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTable tblMateriales;
    private javax.swing.JTextField txtBuscarMaterial;
    // End of variables declaration//GEN-END:variables
}
