/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion.Canceleria;

import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Material;
import dao.CatalogoTrabajoDAO;
import java.awt.Window;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;
import modelo.MaterialDetalle;

/**
 *
 * @author User
 */
public class PanelDetalleCanceleria extends javax.swing.JPanel {

    private List<Material> materialesDisponibles;
    private CatalogoTrabajoDAO catalogoDAO;

    /**
     * Creates new form PanelDetalleCanceleria
     */
    public PanelDetalleCanceleria() {
        initComponents();
        configurarListeners();
    }

    /**
     * Prepara el panel.
     *
     * @param materiales La lista COMPLETA de materiales.
     */
    public void inicializarDatos(List<Material> materiales) {
        this.materialesDisponibles = materiales;
        try {
            this.catalogoDAO = new CatalogoTrabajoDAO(utils.Conexion.getConnection());
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al conectar con BD para Catálogo", "Error DB", JOptionPane.ERROR_MESSAGE);
        }

        cargarDatosComboBox();

        // Configurar los Spinners
        spnCantidad.setModel(new SpinnerNumberModel(1, 1, 100, 1));
        spnNoHojas.setModel(new SpinnerNumberModel(1, 1, 100, 1));
        spnNumFijosVerticales1.setModel(new SpinnerNumberModel(0, 0, 10, 1)); // Usa el nombre correcto
        spnNumFijosHorizontales1.setModel(new SpinnerNumberModel(0, 0, 10, 1)); // Usa el nombre correcto
        spnCantidadTapa.setModel(new SpinnerNumberModel(0, 0, 50, 1));

        // Validar campos de texto
        permitirSoloNumeros(txtMedidaH);
        permitirSoloNumeros(txtMedidaV);
        permitirSoloNumeros(txtMedidaArco);
        permitirSoloNumeros(txtMedidaCanalillo);

    }

    /**
     * Carga los ComboBoxes con datos filtrando por tipo de material o desde DAO
     * según corresponda.
     */
    private void cargarDatosComboBox() {
        // ===============================
        // Tipo de Cancelería
        // ===============================
        cmbTipoCanceleria.removeAllItems();
        cmbTipoCanceleria.addItem("Seleccione una opción...");
        for (modelo.TipoCanceleria tc : modelo.TipoCanceleria.values()) {
            cmbTipoCanceleria.addItem(tc.getDescripcion());
        }
        cmbTipoCanceleria.setSelectedIndex(0);

        // ===============================
        // Materiales (Vidrio, Tapa, etc.)
        // ===============================
        cargarComboPorTipo(cmbTipoCristal, Material.TipoMaterial.VIDRIO);
        cargarComboPorTipo(cbxTipoTapa, Material.TipoMaterial.TAPA);
        cargarComboPorTipo(cbxTipoZoclo, Material.TipoMaterial.ZOCLO);
        cargarComboPorTipo(cbxTipoJunquillo, Material.TipoMaterial.JUNQUILLO);
        cargarComboPorTipo(cbxTipoArco, Material.TipoMaterial.ARCO);
        cargarComboPorTipo(cbxTipoCanalillo, Material.TipoMaterial.CANALILLO);
    }

    /**
     * Llena un JComboBox filtrando la lista de materiales por el tipo de
     * material.
     *
     * @param combo El JComboBox a llenar.
     * @param tipo El tipo de material a filtrar.
     */
    private void cargarComboPorTipo(JComboBox<String> combo, Material.TipoMaterial tipo) {
        combo.removeAllItems();
        combo.addItem("Seleccione una opción");

        if (materialesDisponibles != null && !materialesDisponibles.isEmpty()) {
            for (Material m : materialesDisponibles) {
                if (m.getTipo() == tipo) {
                    combo.addItem(m.getDescripcion());
                }
            }
        } else {
            combo.addItem("Error al cargar");
        }

        combo.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDetalleVentana = new javax.swing.JPanel();
        medidaH = new javax.swing.JLabel();
        txtMedidaH = new javax.swing.JTextField();
        medidaV = new javax.swing.JLabel();
        txtMedidaV = new javax.swing.JTextField();
        panelTitulo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        tipoCristal = new javax.swing.JLabel();
        cmbTipoCristal = new javax.swing.JComboBox<>();
        noHojas = new javax.swing.JLabel();
        spnNoHojas = new javax.swing.JSpinner();
        tipoCanceleria = new javax.swing.JLabel();
        cmbTipoCanceleria = new javax.swing.JComboBox<>();
        bolsa = new javax.swing.JLabel();
        ckBolsa = new javax.swing.JCheckBox();
        zoclo = new javax.swing.JLabel();
        ckZoclo = new javax.swing.JCheckBox();
        tipoZoclo = new javax.swing.JLabel();
        cbxTipoZoclo = new javax.swing.JComboBox<>();
        medicaArco = new javax.swing.JLabel();
        txtMedidaArco = new javax.swing.JTextField();
        descripcion = new javax.swing.JLabel();
        tipoTapa = new javax.swing.JLabel();
        cbxTipoTapa = new javax.swing.JComboBox<>();
        cantidadTapa = new javax.swing.JLabel();
        spnCantidadTapa = new javax.swing.JSpinner();
        fijosVertical = new javax.swing.JLabel();
        fijosHorizontal = new javax.swing.JLabel();
        spnNumFijosVerticales1 = new javax.swing.JSpinner();
        spnNumFijosHorizontales1 = new javax.swing.JSpinner();
        junquillo = new javax.swing.JLabel();
        ckJunquillo = new javax.swing.JCheckBox();
        tipoJuanquillo = new javax.swing.JLabel();
        cbxTipoJunquillo = new javax.swing.JComboBox<>();
        arco = new javax.swing.JLabel();
        ckArco = new javax.swing.JCheckBox();
        tipoArco = new javax.swing.JLabel();
        cbxTipoArco = new javax.swing.JComboBox<>();
        canalillo = new javax.swing.JLabel();
        ckCanalillo = new javax.swing.JCheckBox();
        tipoCanalillo = new javax.swing.JLabel();
        cbxTipoCanalillo = new javax.swing.JComboBox<>();
        medidaCanalillo = new javax.swing.JLabel();
        txtMedidaCanalillo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();

        panelDetalleVentana.setBackground(new java.awt.Color(255, 255, 255));

        medidaH.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medidaH.setForeground(new java.awt.Color(0, 38, 115));
        medidaH.setText("Medida horizontal (m):");

        txtMedidaH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        medidaV.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medidaV.setForeground(new java.awt.Color(0, 38, 115));
        medidaV.setText("Medida vertical (m):");

        txtMedidaV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        panelTitulo.setBackground(new java.awt.Color(0, 19, 90));

        titulo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Detalles de Cancelería");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(10, 10, 10))
        );

        cantidad.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cantidad.setForeground(new java.awt.Color(0, 38, 115));
        cantidad.setText("Cantidad:");

        tipoCristal.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoCristal.setForeground(new java.awt.Color(0, 38, 115));
        tipoCristal.setText("Tipo cristal:");

        cmbTipoCristal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTipoCristal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoCristal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoCristalActionPerformed(evt);
            }
        });

        noHojas.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        noHojas.setForeground(new java.awt.Color(0, 38, 115));
        noHojas.setText("No. hojas:");

        tipoCanceleria.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoCanceleria.setForeground(new java.awt.Color(0, 38, 115));
        tipoCanceleria.setText("Tipo cancelerÍa:");

        cmbTipoCanceleria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTipoCanceleria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bolsa.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        bolsa.setForeground(new java.awt.Color(0, 38, 115));
        bolsa.setText("Bolsa:");

        ckBolsa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckBolsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckBolsaActionPerformed(evt);
            }
        });

        zoclo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        zoclo.setForeground(new java.awt.Color(0, 38, 115));
        zoclo.setText("Zoclo:");

        ckZoclo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckZoclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckZocloActionPerformed(evt);
            }
        });

        tipoZoclo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoZoclo.setForeground(new java.awt.Color(0, 38, 115));
        tipoZoclo.setText("Tipo zoclo:");

        cbxTipoZoclo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoZoclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoZoclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoZocloActionPerformed(evt);
            }
        });

        medicaArco.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medicaArco.setForeground(new java.awt.Color(0, 38, 115));
        medicaArco.setText("Altura arco (m):");

        txtMedidaArco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        descripcion.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        descripcion.setForeground(new java.awt.Color(0, 38, 115));
        descripcion.setText("Descripción:");

        tipoTapa.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoTapa.setForeground(new java.awt.Color(0, 38, 115));
        tipoTapa.setText("Tipo tapa:");

        cbxTipoTapa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoTapa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoTapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoTapaActionPerformed(evt);
            }
        });

        cantidadTapa.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cantidadTapa.setForeground(new java.awt.Color(0, 38, 115));
        cantidadTapa.setText("Cantidad tapa:");

        fijosVertical.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        fijosVertical.setForeground(new java.awt.Color(0, 38, 115));
        fijosVertical.setText("Fijos verticales:");
        fijosVertical.setToolTipText("");

        fijosHorizontal.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        fijosHorizontal.setForeground(new java.awt.Color(0, 38, 115));
        fijosHorizontal.setText("Fijos Horizontales:");

        junquillo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        junquillo.setForeground(new java.awt.Color(0, 38, 115));
        junquillo.setText("Junquillo:");

        ckJunquillo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckJunquillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckJunquilloActionPerformed(evt);
            }
        });

        tipoJuanquillo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoJuanquillo.setForeground(new java.awt.Color(0, 38, 115));
        tipoJuanquillo.setText("Tipo junquillo:");
        tipoJuanquillo.setToolTipText("");

        cbxTipoJunquillo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoJunquillo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoJunquillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoJunquilloActionPerformed(evt);
            }
        });

        arco.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        arco.setForeground(new java.awt.Color(0, 38, 115));
        arco.setText("Arco:");

        ckArco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckArco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckArcoActionPerformed(evt);
            }
        });

        tipoArco.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoArco.setForeground(new java.awt.Color(0, 38, 115));
        tipoArco.setText("Tipo arco:");
        tipoArco.setToolTipText("");

        cbxTipoArco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoArco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoArco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoArcoActionPerformed(evt);
            }
        });

        canalillo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        canalillo.setForeground(new java.awt.Color(0, 38, 115));
        canalillo.setText("Canalillo:");

        ckCanalillo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckCanalillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckCanalilloActionPerformed(evt);
            }
        });

        tipoCanalillo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoCanalillo.setForeground(new java.awt.Color(0, 38, 115));
        tipoCanalillo.setText("Tipo canalillo:");
        tipoCanalillo.setToolTipText("");

        cbxTipoCanalillo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoCanalillo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoCanalillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoCanalilloActionPerformed(evt);
            }
        });

        medidaCanalillo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medidaCanalillo.setForeground(new java.awt.Color(0, 38, 115));
        medidaCanalillo.setText("Medida canalillo(m):");

        txtMedidaCanalillo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        javax.swing.GroupLayout panelDetalleVentanaLayout = new javax.swing.GroupLayout(panelDetalleVentana);
        panelDetalleVentana.setLayout(panelDetalleVentanaLayout);
        panelDetalleVentanaLayout.setHorizontalGroup(
            panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalleVentanaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bolsa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ckBolsa)
                        .addGap(141, 141, 141))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addComponent(fijosHorizontal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(spnNumFijosHorizontales1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addComponent(noHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spnNoHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTipoCanceleria, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMedidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoCanceleria, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(txtMedidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addComponent(fijosVertical, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(spnNumFijosVerticales1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                            .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(zoclo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tipoZoclo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ckZoclo)
                                .addComponent(cbxTipoZoclo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtMedidaArco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addComponent(cantidadTapa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(spnCantidadTapa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addComponent(tipoTapa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cbxTipoTapa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addComponent(tipoJuanquillo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxTipoJunquillo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addComponent(arco, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckArco))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addComponent(junquillo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckJunquillo))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addComponent(tipoArco, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxTipoArco, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(medicaArco, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalleVentanaLayout.createSequentialGroup()
                            .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(canalillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tipoCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ckCanalillo)
                                .addComponent(cbxTipoCanalillo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                            .addComponent(medidaCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMedidaCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        panelDetalleVentanaLayout.setVerticalGroup(
            panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalleVentanaLayout.createSequentialGroup()
                            .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ckCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(canalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(12, 12, 12)
                            .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tipoCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbxTipoCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(12, 12, 12)
                            .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(medidaCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMedidaCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                            .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(medidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMedidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(13, 13, 13)
                            .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(medidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMedidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(13, 13, 13)
                            .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(12, 12, 12)
                            .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tipoCanceleria, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbTipoCanceleria, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(12, 12, 12)
                            .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbTipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(noHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spnNoHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(12, 12, 12)
                            .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bolsa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ckBolsa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fijosVertical, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spnNumFijosVerticales1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(12, 12, 12)
                            .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fijosHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spnNumFijosHorizontales1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(4, 4, 4)))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoTapa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTipoTapa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidadTapa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnCantidadTapa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckZoclo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zoclo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoZoclo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTipoZoclo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                        .addComponent(ckArco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckJunquillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(txtMedidaArco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(tipoArco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cbxTipoArco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(12, 12, 12)
                                                .addComponent(medicaArco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                        .addComponent(arco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(junquillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tipoJuanquillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxTipoJunquillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDetalleVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDetalleVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTipoTapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoTapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoTapaActionPerformed

    private void cbxTipoZocloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoZocloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoZocloActionPerformed

    private void ckZocloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckZocloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckZocloActionPerformed

    private void ckBolsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckBolsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckBolsaActionPerformed

    private void cmbTipoCristalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoCristalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoCristalActionPerformed

    private void ckJunquilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckJunquilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckJunquilloActionPerformed

    private void cbxTipoJunquilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoJunquilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoJunquilloActionPerformed

    private void ckArcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckArcoActionPerformed
        

    }//GEN-LAST:event_ckArcoActionPerformed

    private void cbxTipoArcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoArcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoArcoActionPerformed

    private void ckCanalilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckCanalilloActionPerformed
       
    }//GEN-LAST:event_ckCanalilloActionPerformed

    private void cbxTipoCanalilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoCanalilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoCanalilloActionPerformed

    /**
     * Configura los listeners para habilitar/deshabilitar campos.
     */
    private void configurarListeners() {
        // Zoclo
        cbxTipoZoclo.setEnabled(false);
        ckZoclo.addActionListener(e -> {
            boolean sel = ckZoclo.isSelected();
            cbxTipoZoclo.setEnabled(sel);
            if (!sel) {
                cbxTipoZoclo.setSelectedIndex(0);
            }
        });

        // Junquillo
        cbxTipoJunquillo.setEnabled(false);
        ckJunquillo.addActionListener(e -> {
            boolean sel = ckJunquillo.isSelected();
            cbxTipoJunquillo.setEnabled(sel);
            if (!sel) {
                cbxTipoJunquillo.setSelectedIndex(0);
            }
        });

        // Arco
        cbxTipoArco.setEnabled(false);
        txtMedidaArco.setEnabled(false);
        ckArco.addActionListener(e -> {
            boolean sel = ckArco.isSelected();
            cbxTipoArco.setEnabled(sel);
            txtMedidaArco.setEnabled(sel);
            if (!sel) {
                cbxTipoArco.setSelectedIndex(0);
                txtMedidaArco.setText("");
            }
        });

        // Canalillo
        cbxTipoCanalillo.setEnabled(false);
        txtMedidaCanalillo.setEnabled(false);
        ckCanalillo.addActionListener(e -> {
            boolean sel = ckCanalillo.isSelected();
            cbxTipoCanalillo.setEnabled(sel);
            txtMedidaCanalillo.setEnabled(sel);
            if (!sel) {
                cbxTipoCanalillo.setSelectedIndex(0);
                txtMedidaCanalillo.setText("");
            }
        });

        // (Bolsa, Tapa, Fijos no tienen lógica condicional por ahora)
    }

    public modelo.CanceleriaFijaDetalle getDetalle() {

        modelo.CanceleriaFijaDetalle d = new modelo.CanceleriaFijaDetalle();

        // Variables aseguradas
        BigDecimal medidaH = null;
        BigDecimal medidaV = null;
        BigDecimal medidaArcoBD = null;
        BigDecimal medidaCanalilloBD = null;

        try {

            // =============================================
            // VALIDAR MEDIDAS PRINCIPALES
            // =============================================
            if (txtMedidaH.getText().trim().isEmpty()
                    || txtMedidaV.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(this,
                        "Debe ingresar las medidas horizontal y vertical.",
                        "Campos obligatorios",
                        JOptionPane.WARNING_MESSAGE);
                return null;
            }

            BigDecimal maxAncho = new BigDecimal("15");
            BigDecimal maxAlto = new BigDecimal("10");

            try {
                medidaH = new BigDecimal(txtMedidaH.getText().trim());
                medidaV = new BigDecimal(txtMedidaV.getText().trim());

                if (medidaH.compareTo(BigDecimal.ZERO) <= 0
                        || medidaV.compareTo(BigDecimal.ZERO) <= 0) {

                    JOptionPane.showMessageDialog(this,
                            "Las medidas deben ser mayores que cero.",
                            "Valor inválido",
                            JOptionPane.WARNING_MESSAGE);
                    return null;
                }

                if (medidaH.compareTo(maxAncho) > 0) {
                    JOptionPane.showMessageDialog(this,
                            "La medida horizontal no puede exceder 15 metros.",
                            "Medida fuera de rango",
                            JOptionPane.WARNING_MESSAGE);
                    return null;
                }

                if (medidaV.compareTo(maxAlto) > 0) {
                    JOptionPane.showMessageDialog(this,
                            "La medida vertical no puede exceder 10 metros.",
                            "Medida fuera de rango",
                            JOptionPane.WARNING_MESSAGE);
                    return null;
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this,
                        "Las medidas deben ser numéricas válidas.",
                        "Error de formato",
                        JOptionPane.ERROR_MESSAGE);
                return null;
            }

            // Asignación segura
            d.setMedidaHorizontal(medidaH);
            d.setMedidaVertical(medidaV);

            // =============================================
            // VALIDAR COMBOS
            // =============================================
            if (cmbTipoCanceleria.getSelectedIndex() <= 0) {
                JOptionPane.showMessageDialog(this,
                        "Debe seleccionar un tipo de cancelería.",
                        "Falta selección",
                        JOptionPane.WARNING_MESSAGE);
                return null;
            }

            if (cmbTipoCristal.getSelectedIndex() <= 0
                    || "Error al cargar".equals(cmbTipoCristal.getSelectedItem())) {

                JOptionPane.showMessageDialog(this,
                        "Debe seleccionar un tipo de cristal válido.",
                        "Falta selección",
                        JOptionPane.WARNING_MESSAGE);
                return null;
            }

            // =============================================
            // VALIDAR ARCO (si aplica)
            // =============================================
            d.setArco(ckArco.isSelected());

            if (d.isArco()) {

                if (txtMedidaArco.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this,
                            "Debe ingresar la medida del arco.",
                            "Campo requerido",
                            JOptionPane.WARNING_MESSAGE);
                    return null;
                }

                try {
                    medidaArcoBD = new BigDecimal(txtMedidaArco.getText().trim());

                    if (medidaArcoBD.compareTo(BigDecimal.ZERO) <= 0
                            || medidaArcoBD.compareTo(maxAlto) > 0) {

                        JOptionPane.showMessageDialog(this,
                                "La medida del arco debe ser > 0 y ≤ 10 metros.",
                                "Valor inválido",
                                JOptionPane.WARNING_MESSAGE);
                        return null;
                    }

                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this,
                            "La medida del arco debe ser numérica.",
                            "Error de formato",
                            JOptionPane.ERROR_MESSAGE);
                    return null;
                }

                d.setTipoArco((String) cbxTipoArco.getSelectedItem());
                d.setMedidaArco(medidaArcoBD);

            } else {
                d.setTipoArco(null);
                d.setMedidaArco(null);
            }

            // =============================================
            // VALIDAR CANALILLO (si aplica)
            // =============================================
            d.setCanalillo(ckCanalillo.isSelected());

            if (d.isCanalillo()) {

                if (txtMedidaCanalillo.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this,
                            "Debe ingresar la medida del canalillo.",
                            "Campo requerido",
                            JOptionPane.WARNING_MESSAGE);
                    return null;
                }

                try {
                    medidaCanalilloBD = new BigDecimal(txtMedidaCanalillo.getText().trim());

                    if (medidaCanalilloBD.compareTo(BigDecimal.ZERO) <= 0
                            || medidaCanalilloBD.compareTo(maxAncho) > 0) {

                        JOptionPane.showMessageDialog(this,
                                "La medida del canalillo debe ser > 0 y ≤ 15 metros.",
                                "Valor inválido",
                                JOptionPane.WARNING_MESSAGE);
                        return null;
                    }

                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this,
                            "La medida del canalillo debe ser numérica.",
                            "Error de formato",
                            JOptionPane.ERROR_MESSAGE);
                    return null;
                }

                d.setTipoCanalillo((String) cbxTipoCanalillo.getSelectedItem());
                d.setMedidaCanalillo(medidaCanalilloBD);

            } else {
                d.setTipoCanalillo(null);
                d.setMedidaCanalillo(null);
            }

            // =============================================
            // DESCRIPCIÓN
            // =============================================
            if (txtDescripcion.getText().length() > 255) {
                JOptionPane.showMessageDialog(this,
                        "La descripción no debe superar los 255 caracteres.",
                        "Texto demasiado largo",
                        JOptionPane.WARNING_MESSAGE);
                return null;
            }

            d.setDescripcion(txtDescripcion.getText().trim());

            // =============================================
            // OTROS CAMPOS
            // =============================================
            d.setTipoTrabajo(catalogoDAO.obtenerPorId(3));
            d.setCantidad((Integer) spnCantidad.getValue());
            d.setTipoCristal((String) cmbTipoCristal.getSelectedItem());
            d.setNoHojas((Integer) spnNoHojas.getValue());
            d.setTipoCanceleria(modelo.TipoCanceleria.fromDescripcion(
                    (String) cmbTipoCanceleria.getSelectedItem()));

            d.setBolsa(ckBolsa.isSelected());
            d.setNumFijosVerticales((Integer) spnNumFijosVerticales1.getValue());
            d.setNumFijosHorizontales((Integer) spnNumFijosHorizontales1.getValue());
            d.setTipoTapa((String) cbxTipoTapa.getSelectedItem());
            d.setCantidadTapa((Integer) spnCantidadTapa.getValue());

            d.setZoclo(ckZoclo.isSelected());
            d.setTipoZoclo(ckZoclo.isSelected() ? (String) cbxTipoZoclo.getSelectedItem() : null);

            d.setJunquillo(ckJunquillo.isSelected());
            d.setTipoJunquillo(ckJunquillo.isSelected() ? (String) cbxTipoJunquillo.getSelectedItem() : null);

            // =============================================
            // MATERIALES Y SUBTOTAL
            // =============================================
            List<Material> materialesSeleccionados = obtenerMaterialesSeleccionados();
            List<MaterialDetalle> materialesDetalle = new ArrayList<>();

            for (Material m : materialesSeleccionados) {
                BigDecimal cant = BigDecimal.valueOf(d.getCantidad());
                materialesDetalle.add(new MaterialDetalle(m, cant, m.getPrecio()));
            }

            d.setMateriales(materialesDetalle);

            BigDecimal subtotal = BigDecimal.ZERO;
            for (MaterialDetalle md : materialesDetalle) {
                subtotal = subtotal.add(md.getPrecioTotal());
            }

            d.setPrecioSoloUnaUnidadCalculado(subtotal);
            d.setSubtotalLinea(subtotal);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return null;
        }

        return d;
    }

    /**
     * llena los campos del panel con datos de un detalle existente para editar.
     *
     * @param detalle El detalle a cargar en el formulario.
     */
    public void setDetalle(modelo.CanceleriaFijaDetalle detalle) {
        if (detalle == null) {
            return;
        }

        txtMedidaH.setText(detalle.getMedidaHorizontal().toPlainString());
        txtMedidaV.setText(detalle.getMedidaVertical().toPlainString());
        spnCantidad.setValue(detalle.getCantidad());
        cmbTipoCristal.setSelectedItem(detalle.getTipoCristal());
        spnNoHojas.setValue(detalle.getNoHojas());

        // txtPrecioUnidad.setText(detalle.getPrecioSoloUnaUnidadCalculado().toPlainString());
        // txtSubtotal.setText(detalle.getSubtotalLinea().toPlainString());
        txtDescripcion.setText(detalle.getDescripcion());

        if (detalle.getTipoCanceleria() != null) {
            cmbTipoCanceleria.setSelectedItem(detalle.getTipoCanceleria().getDescripcion());
        }

        // Cargar datos y habilitar/deshabilitar campos
        ckBolsa.setSelected(detalle.isBolsa());
        spnNumFijosVerticales1.setValue(detalle.getNumFijosVerticales());
        spnNumFijosHorizontales1.setValue(detalle.getNumFijosHorizontales());

        cbxTipoTapa.setSelectedItem(detalle.getTipoTapa());
        spnCantidadTapa.setValue(detalle.getCantidadTapa());

        ckZoclo.setSelected(detalle.isZoclo());
        cbxTipoZoclo.setSelectedItem(detalle.getTipoZoclo());
        cbxTipoZoclo.setEnabled(detalle.isZoclo());

        ckJunquillo.setSelected(detalle.isJunquillo());
        cbxTipoJunquillo.setSelectedItem(detalle.getTipoJunquillo());
        cbxTipoJunquillo.setEnabled(detalle.isJunquillo());

        ckArco.setSelected(detalle.isArco());
        cbxTipoArco.setSelectedItem(detalle.getTipoArco());
        txtMedidaArco.setText(detalle.getMedidaArco() != null ? detalle.getMedidaArco().toPlainString() : "");
        cbxTipoArco.setEnabled(detalle.isArco());
        txtMedidaArco.setEnabled(detalle.isArco());

        ckCanalillo.setSelected(detalle.isCanalillo());
        cbxTipoCanalillo.setSelectedItem(detalle.getTipoCanalillo());
        txtMedidaCanalillo.setText(detalle.getMedidaCanalillo() != null ? detalle.getMedidaCanalillo().toPlainString() : "");
        cbxTipoCanalillo.setEnabled(detalle.isCanalillo());
        txtMedidaCanalillo.setEnabled(detalle.isCanalillo());
    }

    private void permitirSoloNumeros(javax.swing.JTextField campo) {
        campo.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                char c = e.getKeyChar();
                // Permitir solo dígitos, punto decimal o borrar
                if (!Character.isDigit(c) && c != '.' && c != KeyEvent.VK_BACK_SPACE) {
                    e.consume();
                }
            }
        });
    }

    /**
     * Devuelve la lista de materiales seleccionados según los checkboxes y
     * comboboxes.
     */
    private List<Material> obtenerMaterialesSeleccionados() {
        List<Material> seleccionados = new ArrayList<>();

        if (ckZoclo.isSelected() && cbxTipoZoclo.getSelectedItem() != null) {
            Material m = buscarMaterial(Material.TipoMaterial.ZOCLO, (String) cbxTipoZoclo.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        if (ckJunquillo.isSelected() && cbxTipoJunquillo.getSelectedItem() != null) {
            Material m = buscarMaterial(Material.TipoMaterial.JUNQUILLO, (String) cbxTipoJunquillo.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        if (ckArco.isSelected() && cbxTipoArco.getSelectedItem() != null) {
            Material m = buscarMaterial(Material.TipoMaterial.ARCO, (String) cbxTipoArco.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        if (ckCanalillo.isSelected() && cbxTipoCanalillo.getSelectedItem() != null) {
            Material m = buscarMaterial(Material.TipoMaterial.CANALILLO, (String) cbxTipoCanalillo.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        if (ckBolsa.isSelected() && cbxTipoTapa.getSelectedItem() != null) {
            Material m = buscarMaterial(Material.TipoMaterial.BOLSA, (String) cbxTipoTapa.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        return seleccionados;
    }

    /**
     * Busca un material dentro de la lista de materiales disponibles según tipo
     * y descripción.
     */
    private Material buscarMaterial(Material.TipoMaterial tipo, String descripcion) {
        for (Material m : materialesDisponibles) {
            if (m.getTipo() == tipo && m.getDescripcion().equals(descripcion)) {
                return m;
            }
        }
        return null;
    }

    public boolean validar() {

        // ========== VALIDAR MEDIDAS OBLIGATORIAS ==========
        if (txtMedidaH.getText().trim().isEmpty() || txtMedidaV.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe ingresar las medidas horizontal y vertical.",
                    "Campos obligatorios", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        BigDecimal h, v;

        try {
            h = new BigDecimal(txtMedidaH.getText());
            v = new BigDecimal(txtMedidaV.getText());

            if (h.compareTo(BigDecimal.ZERO) <= 0 || v.compareTo(BigDecimal.ZERO) <= 0) {
                JOptionPane.showMessageDialog(this,
                        "Las medidas deben ser mayores que cero.",
                        "Valor inválido", JOptionPane.WARNING_MESSAGE);
                return false;
            }

            // límites definidos en tu getDetalle()
            BigDecimal maxH = new BigDecimal("15");
            BigDecimal maxV = new BigDecimal("10");

            if (h.compareTo(maxH) > 0) {
                JOptionPane.showMessageDialog(this,
                        "La medida horizontal no debe exceder 15 metros.",
                        "Medida fuera de rango", JOptionPane.WARNING_MESSAGE);
                return false;
            }

            if (v.compareTo(maxV) > 0) {
                JOptionPane.showMessageDialog(this,
                        "La medida vertical no debe exceder 10 metros.",
                        "Medida fuera de rango", JOptionPane.WARNING_MESSAGE);
                return false;
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Las medidas deben ser numéricas válidas.",
                    "Error de formato", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // ========== VALIDAR COMBOS OBLIGATORIOS ==========
        if (cmbTipoCanceleria.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un tipo de cancelería.",
                    "Selección requerida", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (cmbTipoCristal.getSelectedIndex() <= 0
                || "Error al cargar".equals(cmbTipoCristal.getSelectedItem())) {

            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un tipo de cristal válido.",
                    "Selección requerida", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        // ========== VALIDACIONES CONDICIONALES POR CHECKBOX ==========
        // --- Arco ---
        if (ckArco.isSelected()) {

            if (cbxTipoArco.getSelectedIndex() <= 0) {
                JOptionPane.showMessageDialog(this,
                        "Debe seleccionar un tipo de arco.",
                        "Selección requerida", JOptionPane.WARNING_MESSAGE);
                return false;
            }

            if (txtMedidaArco.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Debe ingresar la medida del arco.",
                        "Dato faltante", JOptionPane.WARNING_MESSAGE);
                return false;
            }

            try {
                BigDecimal medidaArco = new BigDecimal(txtMedidaArco.getText());
                if (medidaArco.compareTo(BigDecimal.ZERO) <= 0
                        || medidaArco.compareTo(new BigDecimal("10000")) > 0) {

                    JOptionPane.showMessageDialog(this,
                            "La medida del arco debe ser mayor que cero y menor o igual a 10,000 mm.",
                            "Valor inválido", JOptionPane.WARNING_MESSAGE);
                    return false;
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this,
                        "La medida del arco debe ser numérica.",
                        "Error de formato", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }

        // --- Canalillo ---
        if (ckCanalillo.isSelected()) {

            if (cbxTipoCanalillo.getSelectedIndex() <= 0) {
                JOptionPane.showMessageDialog(this,
                        "Debe seleccionar un tipo de canalillo.",
                        "Selección requerida", JOptionPane.WARNING_MESSAGE);
                return false;
            }

            if (txtMedidaCanalillo.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Debe ingresar la medida del canalillo.",
                        "Dato faltante", JOptionPane.WARNING_MESSAGE);
                return false;
            }

            try {
                BigDecimal medidaCanalillo = new BigDecimal(txtMedidaCanalillo.getText());
                if (medidaCanalillo.compareTo(BigDecimal.ZERO) <= 0
                        || medidaCanalillo.compareTo(new BigDecimal("10000")) > 0) {

                    JOptionPane.showMessageDialog(this,
                            "La medida del canalillo debe ser mayor que cero y menor o igual a 10,000 mm.",
                            "Valor inválido", JOptionPane.WARNING_MESSAGE);
                    return false;
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this,
                        "La medida del canalillo debe ser numérica.",
                        "Error de formato", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }

        // --- Zoclo ---
        if (ckZoclo.isSelected() && cbxTipoZoclo.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un tipo de zoclo.",
                    "Selección requerida", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        // --- Junquillo ---
        if (ckJunquillo.isSelected() && cbxTipoJunquillo.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un tipo de junquillo.",
                    "Selección requerida", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        // --- Tapa ---
        if (cbxTipoTapa.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un tipo de tapa.",
                    "Selección requerida", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        // ========== VALIDAR DESCRIPCIÓN ==========
        if (txtDescripcion.getText().length() > 255) {
            JOptionPane.showMessageDialog(this,
                    "La descripción no debe superar los 255 caracteres.",
                    "Texto demasiado largo", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arco;
    private javax.swing.JLabel bolsa;
    private javax.swing.JLabel canalillo;
    private javax.swing.JLabel cantidad;
    private javax.swing.JLabel cantidadTapa;
    private javax.swing.JComboBox<String> cbxTipoArco;
    private javax.swing.JComboBox<String> cbxTipoCanalillo;
    private javax.swing.JComboBox<String> cbxTipoJunquillo;
    private javax.swing.JComboBox<String> cbxTipoTapa;
    private javax.swing.JComboBox<String> cbxTipoZoclo;
    private javax.swing.JCheckBox ckArco;
    private javax.swing.JCheckBox ckBolsa;
    private javax.swing.JCheckBox ckCanalillo;
    private javax.swing.JCheckBox ckJunquillo;
    private javax.swing.JCheckBox ckZoclo;
    private javax.swing.JComboBox<String> cmbTipoCanceleria;
    private javax.swing.JComboBox<String> cmbTipoCristal;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel fijosHorizontal;
    private javax.swing.JLabel fijosVertical;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel junquillo;
    private javax.swing.JLabel medicaArco;
    private javax.swing.JLabel medidaCanalillo;
    private javax.swing.JLabel medidaH;
    private javax.swing.JLabel medidaV;
    private javax.swing.JLabel noHojas;
    private javax.swing.JPanel panelDetalleVentana;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JSpinner spnCantidadTapa;
    private javax.swing.JSpinner spnNoHojas;
    private javax.swing.JSpinner spnNumFijosHorizontales1;
    private javax.swing.JSpinner spnNumFijosVerticales1;
    private javax.swing.JLabel tipoArco;
    private javax.swing.JLabel tipoCanalillo;
    private javax.swing.JLabel tipoCanceleria;
    private javax.swing.JLabel tipoCristal;
    private javax.swing.JLabel tipoJuanquillo;
    private javax.swing.JLabel tipoTapa;
    private javax.swing.JLabel tipoZoclo;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtMedidaArco;
    private javax.swing.JTextField txtMedidaCanalillo;
    private javax.swing.JTextField txtMedidaH;
    private javax.swing.JTextField txtMedidaV;
    private javax.swing.JLabel zoclo;
    // End of variables declaration//GEN-END:variables
}
