/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.proyecto;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Proyecto;
import negocio.ProyectoBO;

/**
 *
 * @author cesar
 */
public class frmAdministrarProyectos extends javax.swing.JFrame {

    private ProyectoBO proyectoBO;
    private java.util.List<Proyecto> listaCompleta;

    /**
     * Creates new form frmRegistrarMateriales
     */
    public frmAdministrarProyectos() {
        initComponents();
        proyectoBO = new ProyectoBO();
        cargarProyectosEnTabla();
    }

    private void cargarProyectosEnTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblListaProyectos.getModel();
        modelo.setRowCount(0);
        listaCompleta = proyectoBO.obtenerProyectos();
        for (Proyecto p : listaCompleta) {
            modelo.addRow(new Object[]{
                p.getIdProyecto(),
                p.getCliente().getNombre(),
                p.getFechaInicio(),
                p.getFechaEntregaEstimada(),
                p.getEstado()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelSubtitulo = new javax.swing.JPanel();
        ConsultarCotizacion = new javax.swing.JLabel();
        iconoCrear = new javax.swing.JLabel();
        txtBusquedaProyecto = new javax.swing.JPanel();
        btnCreardesdeCeroProyecto = new javax.swing.JButton();
        Buscar = new javax.swing.JLabel();
        Buscar1 = new javax.swing.JLabel();
        btnBuscarProyecto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaProyectos = new javax.swing.JTable();
        btnCambiarEstadoProyecto = new javax.swing.JButton();
        btnNuevoProyecto = new javax.swing.JButton();
        btnEliminarProyecto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTitulo.setBackground(new java.awt.Color(0, 19, 90));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar proyectos");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        panelSubtitulo.setBackground(new java.awt.Color(0, 81, 168));

        ConsultarCotizacion.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ConsultarCotizacion.setForeground(new java.awt.Color(255, 255, 255));
        ConsultarCotizacion.setText("Listado proyectos");

        iconoCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info-24.png"))); // NOI18N

        javax.swing.GroupLayout panelSubtituloLayout = new javax.swing.GroupLayout(panelSubtitulo);
        panelSubtitulo.setLayout(panelSubtituloLayout);
        panelSubtituloLayout.setHorizontalGroup(
            panelSubtituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubtituloLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(iconoCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConsultarCotizacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSubtituloLayout.setVerticalGroup(
            panelSubtituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubtituloLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelSubtituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconoCrear)
                    .addComponent(ConsultarCotizacion))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        txtBusquedaProyecto.setBackground(new java.awt.Color(255, 255, 255));
        txtBusquedaProyecto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout txtBusquedaProyectoLayout = new javax.swing.GroupLayout(txtBusquedaProyecto);
        txtBusquedaProyecto.setLayout(txtBusquedaProyectoLayout);
        txtBusquedaProyectoLayout.setHorizontalGroup(
            txtBusquedaProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
        );
        txtBusquedaProyectoLayout.setVerticalGroup(
            txtBusquedaProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        btnCreardesdeCeroProyecto.setBackground(new java.awt.Color(0, 81, 168));
        btnCreardesdeCeroProyecto.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnCreardesdeCeroProyecto.setForeground(new java.awt.Color(255, 255, 255));
        btnCreardesdeCeroProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-20.png"))); // NOI18N
        btnCreardesdeCeroProyecto.setText("Crear desde cotizacion");
        btnCreardesdeCeroProyecto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCreardesdeCeroProyecto.setBorderPainted(false);
        btnCreardesdeCeroProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCreardesdeCeroProyecto.setDefaultCapable(false);
        btnCreardesdeCeroProyecto.setFocusPainted(false);
        btnCreardesdeCeroProyecto.setRequestFocusEnabled(false);
        btnCreardesdeCeroProyecto.setRolloverEnabled(false);
        btnCreardesdeCeroProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreardesdeCeroProyectoActionPerformed(evt);
            }
        });

        Buscar.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        Buscar.setForeground(new java.awt.Color(15, 105, 196));
        Buscar.setText("Buscar proyecto");

        Buscar1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        Buscar1.setForeground(new java.awt.Color(15, 105, 196));
        Buscar1.setText("Listado de proyectos");

        btnBuscarProyecto.setBackground(new java.awt.Color(0, 81, 168));
        btnBuscarProyecto.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnBuscarProyecto.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search-20.png"))); // NOI18N
        btnBuscarProyecto.setText("Buscar");
        btnBuscarProyecto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBuscarProyecto.setBorderPainted(false);
        btnBuscarProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscarProyecto.setDefaultCapable(false);
        btnBuscarProyecto.setDisplayedMnemonicIndex(0);
        btnBuscarProyecto.setFocusPainted(false);
        btnBuscarProyecto.setRequestFocusEnabled(false);
        btnBuscarProyecto.setRolloverEnabled(false);
        btnBuscarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProyectoActionPerformed(evt);
            }
        });

        tblListaProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Fecha inicio", "Fecha entrega est.", "Estado actual"
            }
        ));
        jScrollPane1.setViewportView(tblListaProyectos);

        btnCambiarEstadoProyecto.setBackground(new java.awt.Color(255, 153, 51));
        btnCambiarEstadoProyecto.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnCambiarEstadoProyecto.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarEstadoProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit-20.png"))); // NOI18N
        btnCambiarEstadoProyecto.setText("Cambiar estado");
        btnCambiarEstadoProyecto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCambiarEstadoProyecto.setBorderPainted(false);
        btnCambiarEstadoProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCambiarEstadoProyecto.setDefaultCapable(false);
        btnCambiarEstadoProyecto.setFocusPainted(false);
        btnCambiarEstadoProyecto.setRequestFocusEnabled(false);
        btnCambiarEstadoProyecto.setRolloverEnabled(false);
        btnCambiarEstadoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarEstadoProyectoActionPerformed(evt);
            }
        });

        btnNuevoProyecto.setBackground(new java.awt.Color(0, 81, 168));
        btnNuevoProyecto.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnNuevoProyecto.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-24.png"))); // NOI18N
        btnNuevoProyecto.setText("Nuevo proyecto");
        btnNuevoProyecto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNuevoProyecto.setBorderPainted(false);
        btnNuevoProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevoProyecto.setDefaultCapable(false);
        btnNuevoProyecto.setFocusPainted(false);
        btnNuevoProyecto.setRequestFocusEnabled(false);
        btnNuevoProyecto.setRolloverEnabled(false);
        btnNuevoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProyectoActionPerformed(evt);
            }
        });

        btnEliminarProyecto.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminarProyecto.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnEliminarProyecto.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelar-20.png"))); // NOI18N
        btnEliminarProyecto.setText("Eliminar");
        btnEliminarProyecto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEliminarProyecto.setBorderPainted(false);
        btnEliminarProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarProyecto.setDefaultCapable(false);
        btnEliminarProyecto.setFocusPainted(false);
        btnEliminarProyecto.setRequestFocusEnabled(false);
        btnEliminarProyecto.setRolloverEnabled(false);
        btnEliminarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProyectoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Buscar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnCambiarEstadoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnEliminarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(20, 20, 20))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Buscar1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCreardesdeCeroProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(btnNuevoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtBusquedaProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnBuscarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap()))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBusquedaProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Buscar1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCreardesdeCeroProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNuevoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminarProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCambiarEstadoProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreardesdeCeroProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreardesdeCeroProyectoActionPerformed

    }//GEN-LAST:event_btnCreardesdeCeroProyectoActionPerformed

    private void btnBuscarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarProyectoActionPerformed

    private void btnCambiarEstadoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarEstadoProyectoActionPerformed
        int fila = tblListaProyectos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un proyecto");
            return;
        }
        int id = (Integer) tblListaProyectos.getValueAt(fila, 0);
        Proyecto p = proyectoBO.obtenerProyectoPorId(id);
        if (p == null) {
            JOptionPane.showMessageDialog(this, "No se encontró el proyecto");
            return;
        }
        PanelDetallesProyecto frm = new PanelDetallesProyecto(this,p);
        frm.setLocationRelativeTo(this);
        frm.setVisible(true);
    }//GEN-LAST:event_btnCambiarEstadoProyectoActionPerformed

    private void btnNuevoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProyectoActionPerformed
        PanelCotizacionesAceptadas frm = new PanelCotizacionesAceptadas();
        frm.setLocationRelativeTo(this);
        frm.setVisible(true);
    }//GEN-LAST:event_btnNuevoProyectoActionPerformed

    private void btnEliminarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProyectoActionPerformed
        int fila = tblListaProyectos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un proyecto");
            return;
        }
        int id = (Integer) tblListaProyectos.getValueAt(fila, 0);
        int op = JOptionPane.showConfirmDialog(this, "¿Eliminar proyecto?", "Confirmar",
                JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            if (proyectoBO.eliminarProyecto(id)) {
                JOptionPane.showMessageDialog(this, "Proyecto eliminado");
                cargarProyectosEnTabla();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar");
            }
        }
    }//GEN-LAST:event_btnEliminarProyectoActionPerformed

    public void recargarProyectos() {
        cargarProyectosEnTabla();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdministrarProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdministrarProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdministrarProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdministrarProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdministrarProyectos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Buscar;
    private javax.swing.JLabel Buscar1;
    private javax.swing.JLabel ConsultarCotizacion;
    private javax.swing.JButton btnBuscarProyecto;
    private javax.swing.JButton btnCambiarEstadoProyecto;
    private javax.swing.JButton btnCreardesdeCeroProyecto;
    private javax.swing.JButton btnEliminarProyecto;
    private javax.swing.JButton btnNuevoProyecto;
    private javax.swing.JLabel iconoCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelSubtitulo;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTable tblListaProyectos;
    private javax.swing.JPanel txtBusquedaProyecto;
    // End of variables declaration//GEN-END:variables
}
