/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package presentacion;

import java.awt.BorderLayout;
import java.io.FileOutputStream;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.printing.PDFPageable;
import javax.swing.*;
import java.awt.*;
import java.awt.print.PrinterJob;
import java.io.ByteArrayInputStream;
import java.io.FileOutputStream;
import modelo.Cotizacion;
import negocio.GeneradorPDF;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

/**
 *
 * @author delll
 */
public class DialogoPrevisualizacionCotizacion extends javax.swing.JDialog {

    /**
     * Creates new form DialogoPrevisualizacionCotizacion
     */
    public DialogoPrevisualizacionCotizacion(java.awt.Frame parent, Cotizacion cotizacion) {
        super(parent, "Previsualización de Cotización", true);
       setSize(800, 600);
        setLocationRelativeTo(parent);
     // 1. Generar el PDF en memoria con los datos de la cotización
        byte[] pdfBytes = GeneradorPDF.generarCotizacionPdf(cotizacion);
      ByteArrayInputStream bais = new ByteArrayInputStream(pdfBytes);

       // 2. Panel de visualización (ICEpdf)
        SwingController controller = new SwingController();
        SwingViewBuilder factory = new SwingViewBuilder(controller);
        JPanel pdfPanel = factory.buildViewerPanel();
        controller.openDocument(bais, "application/pdf", null);

        // 3. Botones
        JButton btnDescargar = new JButton("Descargar");
        btnDescargar.addActionListener(e -> descargarPdf(pdfBytes));
        JButton btnImprimir = new JButton("Imprimir");
        btnImprimir.addActionListener(e -> imprimirPdf(pdfBytes));
        JPanel panelBotones = new JPanel();
        panelBotones.add(btnDescargar);
        panelBotones.add(btnImprimir);

        // 4. Layout propio
        setLayout(new BorderLayout());
        add(pdfPanel, BorderLayout.CENTER);
        add(panelBotones, BorderLayout.SOUTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void descargarPdf(byte[] pdfBytes) {
        JFileChooser fc = new JFileChooser();
        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try (FileOutputStream fos = new FileOutputStream(fc.getSelectedFile())) {
                fos.write(pdfBytes);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al guardar PDF: " + ex.getMessage());
            }
        }
    }

    private void imprimirPdf(byte[] pdfBytes) {
        try {
            PDDocument doc = PDDocument.load(pdfBytes);
            PrinterJob job = PrinterJob.getPrinterJob();
            job.setPageable(new PDFPageable(doc));
            if (job.printDialog()) {
                job.print();
            }
            doc.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al imprimir PDF: " + ex.getMessage());
        }
    }


    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
