/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dao.CatalogoTrabajoDAO;
import dao.DetalleCotizacionDAO;
import dao.MaterialDAO;
import java.awt.BorderLayout;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import modelo.*;
import negocio.CotizacionBO;
import negocio.GeneradorPDF;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.graphics.image.LosslessFactory;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;
import utils.Conexion;

/**
 *
 * @author User
 */
public class frmEditarCotizacion extends javax.swing.JFrame {

    private List<CatalogoTrabajo> catalogoTrabajos;
    private Vendedor vendedorPorDefecto;
    private List<Material> materialesDisponibles;

    private DefaultTableModel modeloTablaDetalles;
    private List<Object> detallesEnMemoria = new ArrayList<>();
    private Cotizacion cotizacionSeleccionada;
    private CotizacionBO cotizacionBO;
    private DetalleCotizacionDAO detalleDAO;
    private Cotizacion cotizacionActual;

    /**
     * Creates new form frmEditarCotizacion
     */
    public frmEditarCotizacion() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * Constructor para editar
     */
    public frmEditarCotizacion(int idCotizacion) {
        initComponents();
        txtDescuento2.setTransferHandler(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        try {
            this.cotizacionBO = new CotizacionBO();
            this.detalleDAO = new DetalleCotizacionDAO(cotizacionBO.getConexion());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al inicializar la conexión: " + e.getMessage());
            this.dispose();
            return;
        }

        cargarMaterialesDisponibles(); // carga materiales para el cuadro de dialogo
        cargarCatalogo();
        inicializarLogica();
        cargarDatosCotizacion(idCotizacion);

        ButtonGroup grupoDescuento = new ButtonGroup();
        grupoDescuento.add(ckbxDescuentoSi2);
        grupoDescuento.add(ckbxDescuentoNo2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSubtitulo = new javax.swing.JPanel();
        EditarCotizacion = new javax.swing.JLabel();
        iconoEditar = new javax.swing.JLabel();
        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        iconoTitulo = new javax.swing.JLabel();
        panelBuscarCliente = new javax.swing.JPanel();
        detalleCotizacion = new javax.swing.JLabel();
        cbxEstadoCotizacion = new javax.swing.JComboBox<>();
        labelNumCotizacion = new javax.swing.JLabel();
        labelNomCliente = new javax.swing.JLabel();
        labelFechaCotizacion = new javax.swing.JLabel();
        nomCliente = new javax.swing.JLabel();
        NumCotizacion1 = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        fehcCotizacion = new javax.swing.JLabel();
        pnlNuevaCotizacion = new javax.swing.JPanel();
        tituloEditarCotizacion = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDetallesAgregados = new javax.swing.JTable();
        btnEliminarCotizacion = new javax.swing.JButton();
        btnNuevaCotizacion = new javax.swing.JButton();
        btnEditarCotizacion = new javax.swing.JButton();
        panelBotones = new javax.swing.JPanel();
        btnVistaPrevia = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnDescartar = new javax.swing.JButton();
        pnlTotales2 = new javax.swing.JPanel();
        ckbxDescuentoSi2 = new javax.swing.JCheckBox();
        descuento = new javax.swing.JLabel();
        ckbxDescuentoNo2 = new javax.swing.JCheckBox();
        txtDescuento2 = new javax.swing.JTextField();
        labelPorsentaje2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblManoObra2 = new javax.swing.JLabel();
        lblSubtotal2 = new javax.swing.JLabel();
        lblDescuento2 = new javax.swing.JLabel();
        lblTotal2 = new javax.swing.JLabel();
        lblIVA2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMaterialUtilizar = new javax.swing.JTextArea();
        descuento1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar cotización");

        panelSubtitulo.setBackground(new java.awt.Color(0, 81, 168));

        EditarCotizacion.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        EditarCotizacion.setForeground(new java.awt.Color(255, 255, 255));
        EditarCotizacion.setText("Editar cotización");

        iconoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit-20.png"))); // NOI18N

        javax.swing.GroupLayout panelSubtituloLayout = new javax.swing.GroupLayout(panelSubtitulo);
        panelSubtitulo.setLayout(panelSubtituloLayout);
        panelSubtituloLayout.setHorizontalGroup(
            panelSubtituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubtituloLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(iconoEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditarCotizacion)
                .addContainerGap(870, Short.MAX_VALUE))
        );
        panelSubtituloLayout.setVerticalGroup(
            panelSubtituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSubtituloLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(panelSubtituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconoEditar)
                    .addComponent(EditarCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        panelTitulo.setBackground(new java.awt.Color(0, 19, 90));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar cotizaciones");

        iconoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clipboard-48.png"))); // NOI18N
        iconoTitulo.setText("jLabel2");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iconoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBuscarCliente.setBackground(new java.awt.Color(255, 255, 255));

        detalleCotizacion.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        detalleCotizacion.setForeground(new java.awt.Color(15, 105, 196));
        detalleCotizacion.setText("Detalles de Cotización");

        cbxEstadoCotizacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "Item 2", "Item 3", "Item 4" }));
        cbxEstadoCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoCotizacionActionPerformed(evt);
            }
        });

        labelNumCotizacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNumCotizacion.setText("Num. Cotizacion");

        labelNomCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNomCliente.setText("Nombre del Cliente");

        labelFechaCotizacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelFechaCotizacion.setText("Fecha de cotizacion");

        nomCliente.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        nomCliente.setForeground(new java.awt.Color(0, 38, 115));
        nomCliente.setText("Nombre del Cliente");

        NumCotizacion1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NumCotizacion1.setForeground(new java.awt.Color(0, 38, 115));
        NumCotizacion1.setText("Num. Cotización");

        estado.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        estado.setForeground(new java.awt.Color(0, 38, 115));
        estado.setText("Estado");

        fehcCotizacion.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        fehcCotizacion.setForeground(new java.awt.Color(0, 38, 115));
        fehcCotizacion.setText("Fecha de Cotización");

        pnlNuevaCotizacion.setBackground(new java.awt.Color(255, 255, 255));

        tituloEditarCotizacion.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tituloEditarCotizacion.setForeground(new java.awt.Color(15, 105, 196));
        tituloEditarCotizacion.setText("Editar Cotización");

        tblDetallesAgregados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo de trabajo", "Cantidad", "Descripción", "Medidas", "Subtotal"
            }
        ));
        jScrollPane3.setViewportView(tblDetallesAgregados);

        btnEliminarCotizacion.setText("Eliminar");
        btnEliminarCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCotizacionActionPerformed(evt);
            }
        });

        btnNuevaCotizacion.setText("Agregar");
        btnNuevaCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaCotizacionActionPerformed(evt);
            }
        });

        btnEditarCotizacion.setText("Editar");
        btnEditarCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCotizacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNuevaCotizacionLayout = new javax.swing.GroupLayout(pnlNuevaCotizacion);
        pnlNuevaCotizacion.setLayout(pnlNuevaCotizacionLayout);
        pnlNuevaCotizacionLayout.setHorizontalGroup(
            pnlNuevaCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevaCotizacionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlNuevaCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(pnlNuevaCotizacionLayout.createSequentialGroup()
                        .addComponent(tituloEditarCotizacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 555, Short.MAX_VALUE)
                        .addComponent(btnNuevaCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        pnlNuevaCotizacionLayout.setVerticalGroup(
            pnlNuevaCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevaCotizacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNuevaCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevaCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloEditarCotizacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
        );

        panelBotones.setBackground(new java.awt.Color(255, 255, 255));

        btnVistaPrevia.setBackground(new java.awt.Color(254, 188, 47));
        btnVistaPrevia.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnVistaPrevia.setForeground(new java.awt.Color(255, 255, 255));
        btnVistaPrevia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistaprevia-20.png"))); // NOI18N
        btnVistaPrevia.setText("Vista Previa");
        btnVistaPrevia.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVistaPrevia.setBorderPainted(false);
        btnVistaPrevia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVistaPrevia.setDefaultCapable(false);
        btnVistaPrevia.setFocusPainted(false);
        btnVistaPrevia.setRequestFocusEnabled(false);
        btnVistaPrevia.setRolloverEnabled(false);
        btnVistaPrevia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaPreviaActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(4, 210, 65));
        btnGuardar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-20.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGuardar.setBorderPainted(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.setDefaultCapable(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.setRequestFocusEnabled(false);
        btnGuardar.setRolloverEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnDescartar.setBackground(new java.awt.Color(255, 0, 51));
        btnDescartar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnDescartar.setForeground(new java.awt.Color(255, 255, 255));
        btnDescartar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelar-20.png"))); // NOI18N
        btnDescartar.setText("Descartar");
        btnDescartar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDescartar.setBorderPainted(false);
        btnDescartar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDescartar.setDefaultCapable(false);
        btnDescartar.setFocusPainted(false);
        btnDescartar.setRequestFocusEnabled(false);
        btnDescartar.setRolloverEnabled(false);
        btnDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescartarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnVistaPrevia, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 568, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDescartar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVistaPrevia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDescartar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pnlTotales2.setBackground(new java.awt.Color(255, 255, 255));

        ckbxDescuentoSi2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckbxDescuentoSi2.setSelected(true);
        ckbxDescuentoSi2.setText("Si");
        ckbxDescuentoSi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxDescuentoSi2ActionPerformed(evt);
            }
        });

        descuento.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        descuento.setForeground(new java.awt.Color(15, 105, 196));
        descuento.setText("Material a utilizar:");

        ckbxDescuentoNo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckbxDescuentoNo2.setText("No");
        ckbxDescuentoNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxDescuentoNo2ActionPerformed(evt);
            }
        });

        txtDescuento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuento2ActionPerformed(evt);
            }
        });
        txtDescuento2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescuento2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescuento2KeyTyped(evt);
            }
        });

        labelPorsentaje2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelPorsentaje2.setForeground(new java.awt.Color(0, 38, 115));
        labelPorsentaje2.setText("%");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        jPanel4.setForeground(new java.awt.Color(153, 204, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Subtotal");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Mano de Obra");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("TOTAL");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("IVA");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Descuento");

        lblManoObra2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblManoObra2.setText("$0.00");

        lblSubtotal2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtotal2.setText("$0.00");

        lblDescuento2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescuento2.setText("-$0.00");

        lblTotal2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotal2.setText("$0.00");

        lblIVA2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIVA2.setText("$0.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubtotal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblManoObra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIVA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDescuento2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblSubtotal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblManoObra2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblIVA2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblDescuento2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblTotal2)))
        );

        txtMaterialUtilizar.setEditable(false);
        txtMaterialUtilizar.setColumns(20);
        txtMaterialUtilizar.setRows(5);
        jScrollPane1.setViewportView(txtMaterialUtilizar);

        descuento1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        descuento1.setForeground(new java.awt.Color(15, 105, 196));
        descuento1.setText("Descuento");

        javax.swing.GroupLayout pnlTotales2Layout = new javax.swing.GroupLayout(pnlTotales2);
        pnlTotales2.setLayout(pnlTotales2Layout);
        pnlTotales2Layout.setHorizontalGroup(
            pnlTotales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotales2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlTotales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlTotales2Layout.createSequentialGroup()
                        .addComponent(ckbxDescuentoSi2)
                        .addGap(18, 18, 18)
                        .addComponent(ckbxDescuentoNo2)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescuento2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPorsentaje2))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addGroup(pnlTotales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descuento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlTotales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTotales2Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(descuento1)
                    .addContainerGap(895, Short.MAX_VALUE)))
        );
        pnlTotales2Layout.setVerticalGroup(
            pnlTotales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTotales2Layout.createSequentialGroup()
                .addGroup(pnlTotales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTotales2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlTotales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbxDescuentoSi2)
                            .addComponent(ckbxDescuentoNo2)
                            .addComponent(txtDescuento2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPorsentaje2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(pnlTotales2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(descuento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)))
                .addGroup(pnlTotales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(pnlTotales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTotales2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(descuento1)
                    .addContainerGap(194, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelBuscarClienteLayout = new javax.swing.GroupLayout(panelBuscarCliente);
        panelBuscarCliente.setLayout(panelBuscarClienteLayout);
        panelBuscarClienteLayout.setHorizontalGroup(
            panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detalleCotizacion)
                    .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                        .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNumCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumCotizacion1))
                        .addGap(18, 18, 18)
                        .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomCliente))
                        .addGap(18, 18, 18)
                        .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFechaCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fehcCotizacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estado)
                            .addComponent(cbxEstadoCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNuevaCotizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                        .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(pnlTotales2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelBuscarClienteLayout.setVerticalGroup(
            panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detalleCotizacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomCliente)
                    .addComponent(estado)
                    .addComponent(fehcCotizacion)
                    .addComponent(NumCotizacion1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFechaCotizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxEstadoCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(pnlNuevaCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTotales2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (cotizacionActual == null) {
            JOptionPane.showMessageDialog(this, "No hay cotización cargada para guardar.");
            return;
        }
        if (detallesEnMemoria.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe agregar al menos un detalle a la cotización.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Deseas guardar los cambios realizados en la cotización?",
                "Confirmar edición",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion != JOptionPane.YES_OPTION) {
            // Si el usuario elige "No", se cancela el guardado
            JOptionPane.showMessageDialog(this, "La edición de la cotización fue cancelada.");
            return;
        }

        try {
            ArrayList<VentanaDetalle> detallesVentana = new ArrayList<>();
            ArrayList<PuertaAbatibleDetalle> detallesPuerta = new ArrayList<>();
            ArrayList<CanceleriaFijaDetalle> detallesCanceleria = new ArrayList<>();
            BigDecimal subtotal = BigDecimal.ZERO;

            for (Object detalleObj : detallesEnMemoria) {
                if (detalleObj instanceof VentanaDetalle vd) {
                    detallesVentana.add(vd);
                    subtotal = subtotal.add(vd.getSubtotalLinea());
                } else if (detalleObj instanceof PuertaAbatibleDetalle pd) {
                    detallesPuerta.add(pd);
                    subtotal = subtotal.add(pd.getSubtotalLinea());
                } else if (detalleObj instanceof CanceleriaFijaDetalle cd) {
                    detallesCanceleria.add(cd);
                    subtotal = subtotal.add(cd.getSubtotalLinea());
                }
            }

            // Calcula el descuento
            BigDecimal descuentoMonto = BigDecimal.ZERO;

            if (ckbxDescuentoSi2.isSelected()) {
                String textoDescuento = txtDescuento2.getText().trim();

                if (textoDescuento.isEmpty()) {
                    descuentoMonto = BigDecimal.ZERO; // sin descuento
                } else {
                    try {
                        BigDecimal descuentoPorcentaje = new BigDecimal(textoDescuento);

                        if (descuentoPorcentaje.compareTo(BigDecimal.ZERO) < 0
                                || descuentoPorcentaje.compareTo(new BigDecimal("100")) > 0) {
                            JOptionPane.showMessageDialog(this,
                                    "El descuento debe estar entre 0% y 100%.",
                                    "Descuento inválido", JOptionPane.ERROR_MESSAGE);
                            return;
                        }

                        descuentoMonto = subtotal.multiply(descuentoPorcentaje.divide(new BigDecimal("100")));

                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(this,
                                "Ingrese un valor numérico válido para el descuento.",
                                "Error de formato", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
            }

            cotizacionActual.setEstado(cbxEstadoCotizacion.getSelectedItem().toString());
            cotizacionActual.setSubtotal(subtotal);
            cotizacionActual.setDescuentoMonto(descuentoMonto);

            boolean exito = cotizacionBO.actualizarCotizacionCompleta(
                    cotizacionActual,
                    detallesVentana,
                    detallesCanceleria,
                    detallesPuerta
            );

            if (exito) {
                JOptionPane.showMessageDialog(this,
                        "Cotización " + cotizacionActual.getIdCotizacion() + " actualizada con éxito.",
                        "Éxito", JOptionPane.INFORMATION_MESSAGE);

                this.dispose();
                InicioAdministrarCotizaciones inicio = new InicioAdministrarCotizaciones();
                inicio.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al actualizar la cotización.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error de formato numérico. Verifique el campo de descuento.", "Error de Datos", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inesperado al guardar: " + e.getMessage(), "Error General", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescartarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de descartar los cambios?",
                "Confirmar Cancelación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
            new InicioAdministrarCotizaciones().setVisible(true);
        }
    }//GEN-LAST:event_btnDescartarActionPerformed

    private void btnEliminarCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCotizacionActionPerformed
        int filaSeleccionada = tblDetallesAgregados.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un detalle para eliminarlo.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Seguro que deseas eliminar esta cotización de la lista?",
                "Confirmar", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            detallesEnMemoria.remove(filaSeleccionada);
            actualizarTablaDetalles();
            recalcularTotales();
            actualizarTextAreaMateriales();
        }
    }//GEN-LAST:event_btnEliminarCotizacionActionPerformed

    private void btnNuevaCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaCotizacionActionPerformed
        List<Material> materiales = this.materialesDisponibles;
        if (materiales == null || materiales.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error: No se pudieron cargar los materiales.");
            return;
        }

        DetalleEditorDialog dialog = new DetalleEditorDialog(this, true, materiales);
        dialog.setVisible(true);

        Object nuevoDetalle = dialog.getDetalleResultado();

        if (nuevoDetalle != null) {
            detallesEnMemoria.add(nuevoDetalle);
            actualizarTablaDetalles();
            recalcularTotales();
            actualizarTextAreaMateriales();
        }

    }//GEN-LAST:event_btnNuevaCotizacionActionPerformed

    private BufferedImage panelToImage(JPanel panel) {
        int w = panel.getWidth();
        int h = panel.getHeight();
        BufferedImage image = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        panel.paint(g2);
        g2.dispose();
        return image;
    }
    private void btnEditarCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCotizacionActionPerformed
        int filaSeleccionada = tblDetallesAgregados.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una cotización de la tabla para editar.");
            return;
        }

        Object detalleAEditar = detallesEnMemoria.get(filaSeleccionada);
        List<Material> materiales = materialesDisponibles;

        DetalleEditorDialog dialog = null;

        if (detalleAEditar instanceof VentanaDetalle vd) {
            dialog = new DetalleEditorDialog(this, true, materiales, vd);
        } else if (detalleAEditar instanceof PuertaAbatibleDetalle pd) {
            dialog = new DetalleEditorDialog(this, true, materiales, pd);
        } else if (detalleAEditar instanceof CanceleriaFijaDetalle cd) {
            dialog = new DetalleEditorDialog(this, true, materiales, cd);
        } else {
            JOptionPane.showMessageDialog(this, "Error desconocido en el detalle.");
            return;
        }

        dialog.setVisible(true);
        Object detalleResultado = dialog.getDetalleResultado();

        if (detalleResultado != null) {
            detallesEnMemoria.set(filaSeleccionada, detalleResultado);
            actualizarTablaDetalles();
            recalcularTotales();
            actualizarTextAreaMateriales();
        }
    }//GEN-LAST:event_btnEditarCotizacionActionPerformed

    private void btnVistaPreviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaPreviaActionPerformed
        if (this.cotizacionSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una cotización.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        VistaPreviaCotizacionDialog.mostrarPrevia(this, this.cotizacionSeleccionada);


    }//GEN-LAST:event_btnVistaPreviaActionPerformed

    private void cbxEstadoCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoCotizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEstadoCotizacionActionPerformed

    private void txtDescuento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuento2ActionPerformed
        if (ckbxDescuentoSi2.isSelected()) {
            ckbxDescuentoNo2.setSelected(false);
            recalcularTotales();
        }


    }//GEN-LAST:event_txtDescuento2ActionPerformed

    private void txtDescuento2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescuento2KeyReleased
        if (ckbxDescuentoSi2.isSelected()) {
            recalcularTotales();
        }
    }//GEN-LAST:event_txtDescuento2KeyReleased

    private void txtDescuento2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescuento2KeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) && c != '.') {
            evt.consume();
        }

        if (c == '.' && txtDescuento2.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDescuento2KeyTyped

    private void ckbxDescuentoNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxDescuentoNo2ActionPerformed
        ckbxDescuentoSi2.setSelected(false);
        txtDescuento2.setText("");
        txtDescuento2.setEnabled(false);
        recalcularTotales();
    }//GEN-LAST:event_ckbxDescuentoNo2ActionPerformed

    private void ckbxDescuentoSi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxDescuentoSi2ActionPerformed
        ckbxDescuentoNo2.setSelected(false);
        txtDescuento2.setEnabled(true);
        txtDescuento2.requestFocus();
        recalcularTotales();
    }//GEN-LAST:event_ckbxDescuentoSi2ActionPerformed

    // --- carga el catalogo
    private void cargarCatalogo() {
        this.catalogoTrabajos = new ArrayList<>();
        try (Connection con = Conexion.getConnection()) {
            CatalogoTrabajoDAO dao = new CatalogoTrabajoDAO(con);
            this.catalogoTrabajos = dao.obtenerTodos();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar el catálogo de trabajos.");
        }
    }

    // (Copiado de frmCrearCotizacion - Asegúrate de que tu MaterialDAO esté completo)
    private void cargarMaterialesDisponibles() {
        try {
            MaterialDAO materialDAO = new MaterialDAO(utils.Conexion.getConnection());
            materialesDisponibles = materialDAO.obtenerTodos();

            if (materialesDisponibles == null || materialesDisponibles.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No se encontraron materiales en la base de datos.",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error al conectar con la base de datos: " + e.getMessage(),
                    "Error de conexión",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // (Copiado de frmCrearCotizacion)
    private void inicializarLogica() {
        this.modeloTablaDetalles = (DefaultTableModel) tblDetallesAgregados.getModel();
        modeloTablaDetalles.setRowCount(0);

        tblDetallesAgregados.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                actualizarEstadoBotones();
            }
        });
        actualizarEstadoBotones();
    }

    // actuliza los estados de los botones
    private void actualizarEstadoBotones() {
        boolean filaSeleccionada = tblDetallesAgregados.getSelectedRow() != -1;
        btnEditarCotizacion.setEnabled(filaSeleccionada);
        btnEliminarCotizacion.setEnabled(filaSeleccionada);
    }

    // actualiza la tablla de las cotizaiones
    private void actualizarTablaDetalles() {
        modeloTablaDetalles.setRowCount(0);

        for (Object detalle : detallesEnMemoria) {
            if (detalle instanceof VentanaDetalle vd) {
                modeloTablaDetalles.addRow(new Object[]{
                    "Ventana", vd.getCantidad(), vd.getDescripcion(),
                    vd.getMedidaHorizontal() + " x " + vd.getMedidaVertical(), vd.getSubtotalLinea()
                });
            } else if (detalle instanceof PuertaAbatibleDetalle pd) {
                modeloTablaDetalles.addRow(new Object[]{
                    "Puerta", pd.getCantidad(), pd.getDescripcion(),
                    pd.getMedidaHorizontal() + " x " + pd.getMedidaVertical(), pd.getSubtotalLinea()
                });
            } else if (detalle instanceof CanceleriaFijaDetalle cd) {
                modeloTablaDetalles.addRow(new Object[]{
                    "Cancelería", cd.getCantidad(), cd.getDescripcion(),
                    cd.getMedidaHorizontal() + " x " + cd.getMedidaVertical(), cd.getSubtotalLinea()
                });
            }
        }
        actualizarEstadoBotones();
    }

    // calcula los totales
    private void recalcularTotales() {
        BigDecimal subtotal = BigDecimal.ZERO;

        for (Object detalle : detallesEnMemoria) {
            if (detalle instanceof VentanaDetalle vd) {
                subtotal = subtotal.add(vd.getSubtotalLinea());
            } else if (detalle instanceof PuertaAbatibleDetalle pd) {
                subtotal = subtotal.add(pd.getSubtotalLinea());
            } else if (detalle instanceof CanceleriaFijaDetalle cd) {
                subtotal = subtotal.add(cd.getSubtotalLinea());
            }
        }

        BigDecimal descuento = BigDecimal.ZERO;
        if (ckbxDescuentoSi2.isSelected() && !txtDescuento2.getText().trim().isEmpty()) { // Usa nombres de Editar
            try {
                BigDecimal porcentaje = new BigDecimal(txtDescuento2.getText().trim()); // Usa nombres de Editar
                descuento = subtotal.multiply(porcentaje.divide(new BigDecimal("100")));
            } catch (NumberFormatException e) {
                descuento = BigDecimal.ZERO;
            }
        }

        BigDecimal porcentajeManoObra = new BigDecimal("0.45");
        BigDecimal manoObra = subtotal.multiply(porcentajeManoObra);
        BigDecimal baseImponible = subtotal.add(manoObra).subtract(descuento);
        BigDecimal iva = baseImponible.multiply(new BigDecimal("0.16"));
        BigDecimal total = baseImponible.add(iva);

        //actualiza los costos
        lblSubtotal2.setText(String.format("$%.2f", subtotal));
        lblManoObra2.setText(String.format("$%.2f", manoObra));
        lblDescuento2.setText(String.format("-$%.2f", descuento));
        lblIVA2.setText(String.format("$%.2f", iva));
        lblTotal2.setText(String.format("$%.2f", total));
    }

    private List<Material> getMaterialesVidrio() {
        List<Material> vidrios = new ArrayList<>();
        if (this.materialesDisponibles != null) {
            for (Material m : this.materialesDisponibles) {
                if (m.getTipo() == Material.TipoMaterial.VIDRIO) {
                    vidrios.add(m);
                }
            }
        }
        return vidrios;
    }

    /**
     * Carga la cotización existente y sus detalles en el formulario.
     */
    private void cargarDatosCotizacion(int idCotizacion) {
        try {
            this.cotizacionActual = cotizacionBO.obtenerCotizacionPorId(idCotizacion);
            if (cotizacionActual == null) {
                JOptionPane.showMessageDialog(this, "Error: No se encontró la cotización con ID: " + idCotizacion);
                this.dispose();
                return;
            }

            labelNumCotizacion.setText(String.valueOf(cotizacionActual.getIdCotizacion()));
            labelNomCliente.setText(cotizacionActual.getCliente().getNombre());
            labelFechaCotizacion.setText(new SimpleDateFormat("yyyy-MM-dd").format(cotizacionActual.getFecha()));

            cbxEstadoCotizacion.removeAllItems();
            cbxEstadoCotizacion.addItem("Pendiente");
            cbxEstadoCotizacion.addItem("Aceptado");
            cbxEstadoCotizacion.addItem("Cancelada");

            // Si hay un estado guardado, lo seleccionamos, si no, dejamos la opción inicial
            String estadoActual = cotizacionActual.getEstado();
            if (estadoActual != null && !estadoActual.isEmpty()) {
                cbxEstadoCotizacion.setSelectedItem(estadoActual);
            } else {
                cbxEstadoCotizacion.setSelectedIndex(0);
            }
            // Llenar descuento
            BigDecimal descuentoMonto = cotizacionActual.getDescuentoMonto();
            BigDecimal subtotal = cotizacionActual.getSubtotal();

            // Calcula el porcentaje si es posible
            if (descuentoMonto != null && subtotal != null && subtotal.compareTo(BigDecimal.ZERO) > 0) {
                BigDecimal porcentaje = descuentoMonto.multiply(new BigDecimal("100")).divide(subtotal, 2, BigDecimal.ROUND_HALF_UP);
                txtDescuento2.setText(porcentaje.toPlainString());
                ckbxDescuentoSi2.setSelected(true);
                ckbxDescuentoNo2.setSelected(false);
            } else {
                txtDescuento2.setText("0");
                ckbxDescuentoSi2.setSelected(false);
                ckbxDescuentoNo2.setSelected(true);
            }

            //Llenar la lista 
            detallesEnMemoria.clear();

            List<VentanaDetalle> ventanas = detalleDAO.obtenerVentanasPorCotizacion(idCotizacion);
            if (ventanas != null) {
                detallesEnMemoria.addAll(ventanas);
            }

            List<PuertaAbatibleDetalle> puertas = detalleDAO.obtenerPuertasPorCotizacion(idCotizacion);
            if (puertas != null) {
                detallesEnMemoria.addAll(puertas);
            }

            List<CanceleriaFijaDetalle> cancelerias = detalleDAO.obtenerCanceleriasPorCotizacion(idCotizacion);
            if (cancelerias != null) {
                detallesEnMemoria.addAll(cancelerias);
            }

            // 4. Actualizar la JTable y los Totales
            actualizarTablaDetalles();
            recalcularTotales();
            actualizarTextAreaMateriales();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar la cotización: " + e.getMessage());
        }
    }

    /**
     * Genera un resumen de texto con los detalles específicos (accesorios,
     * hojas, etc.) de los elementos en la cotización actual.
     */
    private void actualizarTextAreaMateriales() {
        StringBuilder sb = new StringBuilder();

        if (detallesEnMemoria.isEmpty()) {
            txtMaterialUtilizar.setText("");
            return;
        }

        sb.append("=== RESUMEN DE COTIZACIÓN ===\n\n");

        for (Object obj : detallesEnMemoria) {

            // ------------------------------
            // VENTANA
            // ------------------------------
            if (obj instanceof VentanaDetalle v) {
                sb.append(v.getDescripcion()).append("\n");
            } // ------------------------------
            // PUERTA
            // ------------------------------
            else if (obj instanceof PuertaAbatibleDetalle p) {
                sb.append(p.getDescripcion()).append("\n");
            } // ------------------------------
            // CANCELERÍA
            // ------------------------------
            else if (obj instanceof CanceleriaFijaDetalle c) {
                sb.append(c.getDescripcion()).append("\n");
            }

            sb.append("\n"); // salto entre items
        }

        txtMaterialUtilizar.setText(sb.toString());
        txtMaterialUtilizar.setCaretPosition(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EditarCotizacion;
    private javax.swing.JLabel NumCotizacion1;
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnEditarCotizacion;
    private javax.swing.JButton btnEliminarCotizacion;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevaCotizacion;
    private javax.swing.JButton btnVistaPrevia;
    private javax.swing.JComboBox<String> cbxEstadoCotizacion;
    private javax.swing.JCheckBox ckbxDescuentoNo2;
    private javax.swing.JCheckBox ckbxDescuentoSi2;
    private javax.swing.JLabel descuento;
    private javax.swing.JLabel descuento1;
    private javax.swing.JLabel detalleCotizacion;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel fehcCotizacion;
    private javax.swing.JLabel iconoEditar;
    private javax.swing.JLabel iconoTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelFechaCotizacion;
    private javax.swing.JLabel labelNomCliente;
    private javax.swing.JLabel labelNumCotizacion;
    private javax.swing.JLabel labelPorsentaje2;
    private javax.swing.JLabel lblDescuento2;
    private javax.swing.JLabel lblIVA2;
    private javax.swing.JLabel lblManoObra2;
    private javax.swing.JLabel lblSubtotal2;
    private javax.swing.JLabel lblTotal2;
    private javax.swing.JLabel nomCliente;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBuscarCliente;
    private javax.swing.JPanel panelSubtitulo;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel pnlNuevaCotizacion;
    private javax.swing.JPanel pnlTotales2;
    private javax.swing.JTable tblDetallesAgregados;
    private javax.swing.JLabel tituloEditarCotizacion;
    private javax.swing.JTextField txtDescuento2;
    private javax.swing.JTextArea txtMaterialUtilizar;
    // End of variables declaration//GEN-END:variables
}
