/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import negocio.CotizacionBO;
import modelo.Cotizacion;
import java.util.List;

/**
 *
 * @author User
 */
public class frmEditarCotizacion extends javax.swing.JFrame {

    private CotizacionBO cotizacionBO;
    private Cotizacion cotizacionActual;

    /**
     * Creates new form frmEditarCotizacion
     */
    public frmEditarCotizacion(int idCotizacion) {
        initComponents();
        this.cotizacionBO = new CotizacionBO();

        // Buscar la cotización completa usando el BO
        this.cotizacionActual = cotizacionBO.obtenerCotizacionPorId(idCotizacion);

        cargarTiposTrabajo();
        cargarEstados(); // Llena el combo con los estados
        cargarDatosCotizacion(); // Llena los campos con la información actual
    }

    private void cargarEstados() {
        List<String> estados = cotizacionBO.obtenerEstadosCotizacion();
        cbxEstadoCotizacion.removeAllItems();
        for (String estado : estados) {
            cbxEstadoCotizacion.addItem(estado);
        }
    }

    private void cargarDatosCotizacion() {
        if (cotizacionActual != null) {
            // Selecciona el estado actual en el combo
            cbxEstadoCotizacion.setSelectedItem(cotizacionActual.getEstado());
            // Aquí podrías llenar otros campos, como:
            labelNumCotizacion.setText(String.valueOf(cotizacionActual.getIdCotizacion()));
            labelNomCliente.setText(cotizacionActual.getCliente().getNombre());
            labelFechaCotizacion.setText(String.valueOf(cotizacionActual.getFecha()));
            txtDescuento.setText(cotizacionActual.getDescuentoMonto().toString());
        }
    }

    private void cargarTiposTrabajo() {
        List<String> tipos = cotizacionBO.obtenerTiposTrabajo();
        cbxTipoTrabajo1.removeAllItems();
        for (String tipo : tipos) {
            cbxTipoTrabajo1.addItem(tipo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSubtitulo = new javax.swing.JPanel();
        EditarCotizacion = new javax.swing.JLabel();
        iconoEditar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        iconoTitulo = new javax.swing.JLabel();
        panelTituloDetalle = new javax.swing.JPanel();
        Descuento = new javax.swing.JLabel();
        panelInformacionTrabajo = new javax.swing.JPanel();
        labelHorizontal = new javax.swing.JLabel();
        tituloCantidad = new javax.swing.JLabel();
        txtMetrosHorizontal = new javax.swing.JTextField();
        labelVertical = new javax.swing.JLabel();
        txtMetrosVertical = new javax.swing.JTextField();
        tituloMedidas = new javax.swing.JLabel();
        cbxCantidad = new javax.swing.JComboBox<>();
        tituloMosquitero = new javax.swing.JLabel();
        ckbxMosquiteroSi = new javax.swing.JCheckBox();
        ckbxMosquiteroNo = new javax.swing.JCheckBox();
        tituloCristal = new javax.swing.JLabel();
        cbxTipoCristal = new javax.swing.JComboBox<>();
        labelNumHojas = new javax.swing.JLabel();
        cbxNumHojas = new javax.swing.JComboBox<>();
        panelTipoTrabajo = new javax.swing.JPanel();
        tituloTipoTrabajo = new javax.swing.JLabel();
        cbxTipoTrabajo1 = new javax.swing.JComboBox<>();
        panelDescuento = new javax.swing.JPanel();
        ckbxDescuentoSi = new javax.swing.JCheckBox();
        ckbxDescuentoNo = new javax.swing.JCheckBox();
        txtDescuento = new javax.swing.JTextField();
        labelPorsentaje = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnDescartar = new javax.swing.JButton();
        panelBotones = new javax.swing.JPanel();
        btnVistaPrevia = new javax.swing.JButton();
        btnDescargar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        panelBuscarCliente = new javax.swing.JPanel();
        labelCliente = new javax.swing.JLabel();
        cbxEstadoCotizacion = new javax.swing.JComboBox<>();
        labelNumCotizacion = new javax.swing.JLabel();
        labelNomCliente = new javax.swing.JLabel();
        labelFechaCotizacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar cotización");

        panelSubtitulo.setBackground(new java.awt.Color(0, 81, 168));

        EditarCotizacion.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        EditarCotizacion.setForeground(new java.awt.Color(255, 255, 255));
        EditarCotizacion.setText("Editar cotización");

        iconoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit-20.png"))); // NOI18N

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSubtituloLayout = new javax.swing.GroupLayout(panelSubtitulo);
        panelSubtitulo.setLayout(panelSubtituloLayout);
        panelSubtituloLayout.setHorizontalGroup(
            panelSubtituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubtituloLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconoEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditarCotizacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );
        panelSubtituloLayout.setVerticalGroup(
            panelSubtituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSubtituloLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(panelSubtituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconoEditar)
                    .addGroup(panelSubtituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EditarCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGap(8, 8, 8))
        );

        panelTitulo.setBackground(new java.awt.Color(0, 19, 90));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar cotizaciones");

        iconoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clipboard-48.png"))); // NOI18N
        iconoTitulo.setText("jLabel2");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iconoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTituloDetalle.setBackground(new java.awt.Color(255, 255, 255));

        Descuento.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        Descuento.setForeground(new java.awt.Color(15, 105, 196));
        Descuento.setText("Descuento");

        javax.swing.GroupLayout panelTituloDetalleLayout = new javax.swing.GroupLayout(panelTituloDetalle);
        panelTituloDetalle.setLayout(panelTituloDetalleLayout);
        panelTituloDetalleLayout.setHorizontalGroup(
            panelTituloDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloDetalleLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(Descuento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloDetalleLayout.setVerticalGroup(
            panelTituloDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloDetalleLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(Descuento)
                .addContainerGap())
        );

        panelInformacionTrabajo.setBackground(new java.awt.Color(255, 255, 255));

        labelHorizontal.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelHorizontal.setForeground(new java.awt.Color(0, 38, 115));
        labelHorizontal.setText("Horizontal");

        tituloCantidad.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tituloCantidad.setForeground(new java.awt.Color(0, 38, 115));
        tituloCantidad.setText("Cantidad");

        labelVertical.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelVertical.setForeground(new java.awt.Color(0, 38, 115));
        labelVertical.setText("Vertical");

        tituloMedidas.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tituloMedidas.setForeground(new java.awt.Color(0, 38, 115));
        tituloMedidas.setText("Medidas");

        cbxCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tituloMosquitero.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tituloMosquitero.setForeground(new java.awt.Color(0, 38, 115));
        tituloMosquitero.setText("Mosquitero");

        ckbxMosquiteroSi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckbxMosquiteroSi.setText("Si");
        ckbxMosquiteroSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbxMosquiteroSiActionPerformed(evt);
            }
        });

        ckbxMosquiteroNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckbxMosquiteroNo.setText("No");

        tituloCristal.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tituloCristal.setForeground(new java.awt.Color(0, 38, 115));
        tituloCristal.setText("Cristal");

        cbxTipoCristal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelNumHojas.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelNumHojas.setForeground(new java.awt.Color(0, 38, 115));
        labelNumHojas.setText("No. de hojas");

        cbxNumHojas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelInformacionTrabajoLayout = new javax.swing.GroupLayout(panelInformacionTrabajo);
        panelInformacionTrabajo.setLayout(panelInformacionTrabajoLayout);
        panelInformacionTrabajoLayout.setHorizontalGroup(
            panelInformacionTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionTrabajoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelInformacionTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInformacionTrabajoLayout.createSequentialGroup()
                        .addComponent(labelNumHojas)
                        .addGap(18, 18, 18)
                        .addComponent(cbxNumHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbxTipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloCristal)
                    .addGroup(panelInformacionTrabajoLayout.createSequentialGroup()
                        .addGroup(panelInformacionTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInformacionTrabajoLayout.createSequentialGroup()
                                .addComponent(labelHorizontal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMetrosHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(labelVertical)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMetrosVertical, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tituloMedidas))
                        .addGap(62, 62, 62)
                        .addGroup(panelInformacionTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloCantidad)
                            .addComponent(cbxCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(panelInformacionTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloMosquitero)
                            .addGroup(panelInformacionTrabajoLayout.createSequentialGroup()
                                .addComponent(ckbxMosquiteroSi)
                                .addGap(33, 33, 33)
                                .addComponent(ckbxMosquiteroNo)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInformacionTrabajoLayout.setVerticalGroup(
            panelInformacionTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionTrabajoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelInformacionTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInformacionTrabajoLayout.createSequentialGroup()
                        .addComponent(tituloMosquitero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInformacionTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbxMosquiteroNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbxMosquiteroSi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInformacionTrabajoLayout.createSequentialGroup()
                        .addGroup(panelInformacionTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloCantidad)
                            .addComponent(tituloMedidas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInformacionTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInformacionTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelHorizontal)
                                .addComponent(txtMetrosHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelVertical)
                                .addComponent(txtMetrosVertical, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(tituloCristal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelInformacionTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumHojas)
                    .addComponent(cbxNumHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTipoTrabajo.setBackground(new java.awt.Color(255, 255, 255));

        tituloTipoTrabajo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tituloTipoTrabajo.setForeground(new java.awt.Color(15, 105, 196));
        tituloTipoTrabajo.setText("Tipo de trabajo");

        cbxTipoTrabajo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoTrabajo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoTrabajo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTipoTrabajoLayout = new javax.swing.GroupLayout(panelTipoTrabajo);
        panelTipoTrabajo.setLayout(panelTipoTrabajoLayout);
        panelTipoTrabajoLayout.setHorizontalGroup(
            panelTipoTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoTrabajoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelTipoTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxTipoTrabajo1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloTipoTrabajo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTipoTrabajoLayout.setVerticalGroup(
            panelTipoTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoTrabajoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tituloTipoTrabajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxTipoTrabajo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        panelDescuento.setBackground(new java.awt.Color(255, 255, 255));

        ckbxDescuentoSi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckbxDescuentoSi.setSelected(true);
        ckbxDescuentoSi.setText("Si");

        ckbxDescuentoNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckbxDescuentoNo.setText("No");

        labelPorsentaje.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelPorsentaje.setForeground(new java.awt.Color(0, 38, 115));
        labelPorsentaje.setText("%");

        btnGuardar.setBackground(new java.awt.Color(3, 175, 61));
        btnGuardar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-20.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGuardar.setBorderPainted(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.setDefaultCapable(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.setRequestFocusEnabled(false);
        btnGuardar.setRolloverEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnDescartar.setBackground(new java.awt.Color(202, 50, 0));
        btnDescartar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnDescartar.setForeground(new java.awt.Color(255, 255, 255));
        btnDescartar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelar-20.png"))); // NOI18N
        btnDescartar.setText("Descartar");
        btnDescartar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDescartar.setBorderPainted(false);
        btnDescartar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDescartar.setDefaultCapable(false);
        btnDescartar.setFocusPainted(false);
        btnDescartar.setRequestFocusEnabled(false);
        btnDescartar.setRolloverEnabled(false);

        javax.swing.GroupLayout panelDescuentoLayout = new javax.swing.GroupLayout(panelDescuento);
        panelDescuento.setLayout(panelDescuentoLayout);
        panelDescuentoLayout.setHorizontalGroup(
            panelDescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescuentoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(ckbxDescuentoSi)
                .addGap(18, 18, 18)
                .addComponent(ckbxDescuentoNo)
                .addGap(18, 18, 18)
                .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPorsentaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 390, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnDescartar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        panelDescuentoLayout.setVerticalGroup(
            panelDescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDescuentoLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(panelDescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbxDescuentoSi)
                    .addComponent(ckbxDescuentoNo)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPorsentaje)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDescartar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        panelBotones.setBackground(new java.awt.Color(255, 255, 255));

        btnVistaPrevia.setBackground(new java.awt.Color(254, 188, 47));
        btnVistaPrevia.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnVistaPrevia.setForeground(new java.awt.Color(255, 255, 255));
        btnVistaPrevia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistaprevia-20.png"))); // NOI18N
        btnVistaPrevia.setText("Vista Previa");
        btnVistaPrevia.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVistaPrevia.setBorderPainted(false);
        btnVistaPrevia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVistaPrevia.setDefaultCapable(false);
        btnVistaPrevia.setFocusPainted(false);
        btnVistaPrevia.setRequestFocusEnabled(false);
        btnVistaPrevia.setRolloverEnabled(false);

        btnDescargar.setBackground(new java.awt.Color(0, 81, 168));
        btnDescargar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnDescargar.setForeground(new java.awt.Color(255, 255, 255));
        btnDescargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download-updates-20.png"))); // NOI18N
        btnDescargar.setText("Descargar");
        btnDescargar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDescargar.setBorderPainted(false);
        btnDescargar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDescargar.setDefaultCapable(false);
        btnDescargar.setFocusPainted(false);
        btnDescargar.setRequestFocusEnabled(false);
        btnDescargar.setRolloverEnabled(false);

        btnImprimir.setBackground(new java.awt.Color(0, 81, 168));
        btnImprimir.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnImprimir.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print-20.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnImprimir.setBorderPainted(false);
        btnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnImprimir.setDefaultCapable(false);
        btnImprimir.setFocusPainted(false);
        btnImprimir.setRequestFocusEnabled(false);
        btnImprimir.setRolloverEnabled(false);

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnVistaPrevia, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnDescargar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVistaPrevia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDescargar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panelBuscarCliente.setBackground(new java.awt.Color(255, 255, 255));

        labelCliente.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        labelCliente.setForeground(new java.awt.Color(15, 105, 196));
        labelCliente.setText("Cliente");

        cbxEstadoCotizacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "Item 2", "Item 3", "Item 4" }));
        cbxEstadoCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoCotizacionActionPerformed(evt);
            }
        });

        labelNumCotizacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNumCotizacion.setText("Num. Cotizacion");

        labelNomCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNomCliente.setText("Nombre del Cliente");

        labelFechaCotizacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelFechaCotizacion.setText("Fecha de cotizacion");

        javax.swing.GroupLayout panelBuscarClienteLayout = new javax.swing.GroupLayout(panelBuscarCliente);
        panelBuscarCliente.setLayout(panelBuscarClienteLayout);
        panelBuscarClienteLayout.setHorizontalGroup(
            panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                        .addComponent(labelNumCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelFechaCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxEstadoCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBuscarClienteLayout.setVerticalGroup(
            panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbxEstadoCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                        .addComponent(labelCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNumCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFechaCotizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTipoTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTituloDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(panelInformacionTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTipoTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInformacionTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTituloDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckbxMosquiteroSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbxMosquiteroSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbxMosquiteroSiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        InicioAdministrarCotizaciones in = new InicioAdministrarCotizaciones();
        in.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbxEstadoCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoCotizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEstadoCotizacionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (cotizacionActual != null) {
            // Actualizar estado y tipo de trabajo con lo seleccionado en los ComboBox
            String nuevoEstado = cbxEstadoCotizacion.getSelectedItem().toString();
            String nuevoTipoTrabajo = cbxTipoTrabajo1.getSelectedItem().toString();
            cotizacionActual.setEstado(nuevoEstado);

            // Llamar al BO para actualizar la cotización
            boolean exito = cotizacionBO.actualizarCotizacion(cotizacionActual);

            if (exito) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cotización actualizada correctamente.");
                this.dispose(); // cerrar el frame después de guardar
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar la cotización.");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay cotización cargada para actualizar.");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cbxTipoTrabajo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoTrabajo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoTrabajo1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmEditarCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmEditarCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmEditarCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmEditarCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmEditarCotizacion().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descuento;
    private javax.swing.JLabel EditarCotizacion;
    private javax.swing.JButton btnDescargar;
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnVistaPrevia;
    private javax.swing.JComboBox<String> cbxCantidad;
    private javax.swing.JComboBox<String> cbxEstadoCotizacion;
    private javax.swing.JComboBox<String> cbxNumHojas;
    private javax.swing.JComboBox<String> cbxTipoCristal;
    private javax.swing.JComboBox<String> cbxTipoTrabajo1;
    private javax.swing.JCheckBox ckbxDescuentoNo;
    private javax.swing.JCheckBox ckbxDescuentoSi;
    private javax.swing.JCheckBox ckbxMosquiteroNo;
    private javax.swing.JCheckBox ckbxMosquiteroSi;
    private javax.swing.JLabel iconoEditar;
    private javax.swing.JLabel iconoTitulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelFechaCotizacion;
    private javax.swing.JLabel labelHorizontal;
    private javax.swing.JLabel labelNomCliente;
    private javax.swing.JLabel labelNumCotizacion;
    private javax.swing.JLabel labelNumHojas;
    private javax.swing.JLabel labelPorsentaje;
    private javax.swing.JLabel labelVertical;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBuscarCliente;
    private javax.swing.JPanel panelDescuento;
    private javax.swing.JPanel panelInformacionTrabajo;
    private javax.swing.JPanel panelSubtitulo;
    private javax.swing.JPanel panelTipoTrabajo;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelTituloDetalle;
    private javax.swing.JLabel tituloCantidad;
    private javax.swing.JLabel tituloCristal;
    private javax.swing.JLabel tituloMedidas;
    private javax.swing.JLabel tituloMosquitero;
    private javax.swing.JLabel tituloTipoTrabajo;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtMetrosHorizontal;
    private javax.swing.JTextField txtMetrosVertical;
    // End of variables declaration//GEN-END:variables
}
