/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package presentacion;

import dao.MaterialDAO;
import negocio.CotizacionBO;

/**
 *
 * @author aleja
 */
public class MaterialMosquiteras extends javax.swing.JDialog {

    private CotizacionBO cotizacionBO;
    private MaterialDAO materialDAO;

    /**
     * Creates new form MaterialMosquiteras
     */
    public MaterialMosquiteras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);

        // Crear la conexión y el DAO
        this.cotizacionBO = new CotizacionBO();
        this.materialDAO = new MaterialDAO(cotizacionBO.getConexion());
    }

    public MaterialMosquiteras(java.awt.Window parent, boolean modal) {
        super(parent, ModalityType.APPLICATION_MODAL);
        initComponents();
        setLocationRelativeTo(parent);

        this.cotizacionBO = new CotizacionBO();
        this.materialDAO = new MaterialDAO(cotizacionBO.getConexion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMalla = new javax.swing.JLabel();
        spnMalla = new javax.swing.JSpinner();
        lblAluminio = new javax.swing.JLabel();
        spnAluminio = new javax.swing.JSpinner();
        btnGuardar5 = new javax.swing.JButton();
        panelTitulo = new javax.swing.JPanel();
        titulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblMalla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMalla.setForeground(new java.awt.Color(0, 0, 0));
        lblMalla.setText("Malla:");

        lblAluminio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAluminio.setForeground(new java.awt.Color(0, 0, 0));
        lblAluminio.setText("Aluminio:");

        btnGuardar5.setBackground(new java.awt.Color(4, 210, 65));
        btnGuardar5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnGuardar5.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-20.png"))); // NOI18N
        btnGuardar5.setText("Guardar");
        btnGuardar5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGuardar5.setBorderPainted(false);
        btnGuardar5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar5.setDefaultCapable(false);
        btnGuardar5.setFocusPainted(false);
        btnGuardar5.setRequestFocusEnabled(false);
        btnGuardar5.setRolloverEnabled(false);
        btnGuardar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAluminio)
                    .addComponent(lblMalla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnMalla, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnAluminio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnGuardar5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnMalla, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMalla))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAluminio)
                    .addComponent(spnAluminio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panelTitulo.setBackground(new java.awt.Color(0, 19, 90));

        titulo1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 255, 255));
        titulo1.setText("Materiales");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar5ActionPerformed
        try {
            int cantMalla = (int) spnMalla.getValue();
            int cantAluminio = (int) spnAluminio.getValue();

            // --- MALLA ---
            if (cantMalla > 0) {
                int idMalla = materialDAO.obtenerIdPorDescripcion("Malla Ciclónica");

                if (idMalla != -1) {
                    int stockActual = materialDAO.obtenerStock(idMalla);
                    int nuevoStock = stockActual + cantMalla;

                    materialDAO.actualizarStock(idMalla, nuevoStock);
                }
            }

            // --- ALUMINIO ---
            if (cantAluminio > 0) {
                int idAluminio = 4;
                idAluminio = materialDAO.obtenerIdPorDescripcion("Aluminio para marco");

                if (idAluminio != -1) {
                    int stockActual = materialDAO.obtenerStock(idAluminio);
                    int nuevoStock = stockActual + cantAluminio;

                    materialDAO.actualizarStock(idAluminio, nuevoStock);
                }
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Stock actualizado correctamente");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error al actualizar stock: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }

        this.dispose();
    }//GEN-LAST:event_btnGuardar5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAluminio;
    private javax.swing.JLabel lblMalla;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JSpinner spnAluminio;
    private javax.swing.JSpinner spnMalla;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables
}
