package presentacion;

import dao.CatalogoTrabajoDAO;
import dao.MaterialDetalleDAO;
import dao.VentanaDetalleDAO;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelo.Material;
import modelo.MaterialDetalle;

/**
 *
 * @author Vidrieria
 */
public class PanelDetalleVentana extends javax.swing.JPanel {

    private List<Material> materialesDisponibles;
    private CatalogoTrabajoDAO catalogoDAO;

    /**
     * Creates new form PanelDetalleVentana
     */
    public PanelDetalleVentana() {
        initComponents();
        configurarListeners();
    }

    /**
     * Prepara el panel.
     *
     * @param materialesVidrio La lista de materiales
     */
    public void inicializarDatos(List<Material> materiales) {
        this.materialesDisponibles = materiales;

        // Inicializa el DAO
        try {
            this.catalogoDAO = new CatalogoTrabajoDAO(utils.Conexion.getConnection());
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al conectar con BD para Catálogo", "Error DB", JOptionPane.ERROR_MESSAGE);
        }

        cargarDatosComboBox();

        // Configurar los Spinners de 1 a 100, con valor inicial 1
        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        spnNoHojas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        // Validar campos de texto
        permitirSoloNumeros(txtMedidaH);
        permitirSoloNumeros(txtMedidaV);
        permitirSoloNumeros(txtMedidaCanalillo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDetalleVentana = new javax.swing.JPanel();
        medidaH = new javax.swing.JLabel();
        txtMedidaH = new javax.swing.JTextField();
        medidaV = new javax.swing.JLabel();
        txtMedidaV = new javax.swing.JTextField();
        panelTitulo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        tipoCristal = new javax.swing.JLabel();
        cmbTipoCristal = new javax.swing.JComboBox<>();
        noHojas = new javax.swing.JLabel();
        spnNoHojas = new javax.swing.JSpinner();
        tipoVentana = new javax.swing.JLabel();
        cmbTipoVentana = new javax.swing.JComboBox<>();
        mosquitero = new javax.swing.JLabel();
        ckMosquitero = new javax.swing.JCheckBox();
        arco = new javax.swing.JLabel();
        ckArco = new javax.swing.JCheckBox();
        tipoArco = new javax.swing.JLabel();
        cbxTipoArco = new javax.swing.JComboBox<>();
        medidaArcco = new javax.swing.JLabel();
        txtMedidaArco = new javax.swing.JTextField();
        tipoCanalillo = new javax.swing.JLabel();
        cbxTipoCanalillo = new javax.swing.JComboBox<>();
        medidaCanalillo = new javax.swing.JLabel();
        txtMedidaCanalillo = new javax.swing.JTextField();
        descripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();

        panelDetalleVentana.setBackground(new java.awt.Color(255, 255, 255));

        medidaH.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medidaH.setForeground(new java.awt.Color(0, 38, 115));
        medidaH.setText("Medida horizontal (m):");

        txtMedidaH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        medidaV.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medidaV.setForeground(new java.awt.Color(0, 38, 115));
        medidaV.setText("Medida vertical (m):");

        txtMedidaV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        panelTitulo.setBackground(new java.awt.Color(0, 19, 90));

        titulo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Detalles de Ventana");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(10, 10, 10))
        );

        cantidad.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cantidad.setForeground(new java.awt.Color(0, 38, 115));
        cantidad.setText("Cantidad:");

        tipoCristal.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoCristal.setForeground(new java.awt.Color(0, 38, 115));
        tipoCristal.setText("Tipo cristal:");

        cmbTipoCristal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTipoCristal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoCristal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoCristalActionPerformed(evt);
            }
        });

        noHojas.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        noHojas.setForeground(new java.awt.Color(0, 38, 115));
        noHojas.setText("No. hojas:");

        tipoVentana.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoVentana.setForeground(new java.awt.Color(0, 38, 115));
        tipoVentana.setText("Tipo ventana:");

        cmbTipoVentana.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTipoVentana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        mosquitero.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        mosquitero.setForeground(new java.awt.Color(0, 38, 115));
        mosquitero.setText("Mosquitero:");

        ckMosquitero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckMosquitero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckMosquiteroActionPerformed(evt);
            }
        });

        arco.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        arco.setForeground(new java.awt.Color(0, 38, 115));
        arco.setText("Arco:");

        ckArco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckArco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckArcoActionPerformed(evt);
            }
        });

        tipoArco.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoArco.setForeground(new java.awt.Color(0, 38, 115));
        tipoArco.setText("Tipo arco:");

        cbxTipoArco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoArco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoArco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoArcoActionPerformed(evt);
            }
        });

        medidaArcco.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medidaArcco.setForeground(new java.awt.Color(0, 38, 115));
        medidaArcco.setText("Medida arco (m):");

        txtMedidaArco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tipoCanalillo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoCanalillo.setForeground(new java.awt.Color(0, 38, 115));
        tipoCanalillo.setText("Tipo canalillo:");

        cbxTipoCanalillo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoCanalillo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoCanalillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoCanalilloActionPerformed(evt);
            }
        });

        medidaCanalillo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medidaCanalillo.setForeground(new java.awt.Color(0, 38, 115));
        medidaCanalillo.setText("Medida canalillo (m):");

        txtMedidaCanalillo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        descripcion.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        descripcion.setForeground(new java.awt.Color(0, 38, 115));
        descripcion.setText("Descripción:");

        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDetalleVentanaLayout = new javax.swing.GroupLayout(panelDetalleVentana);
        panelDetalleVentana.setLayout(panelDetalleVentanaLayout);
        panelDetalleVentanaLayout.setHorizontalGroup(
            panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTipoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnNoHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMedidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMedidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medidaCanalillo)
                            .addComponent(descripcion)
                            .addComponent(medidaArcco, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(arco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tipoArco, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tipoCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbxTipoCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxTipoArco, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ckArco)
                                            .addComponent(txtMedidaArco, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtDescripcion)
                                            .addComponent(txtMedidaCanalillo, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                        .addContainerGap(52, Short.MAX_VALUE))))))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addComponent(mosquitero, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ckMosquitero)
                        .addContainerGap())))
        );
        panelDetalleVentanaLayout.setVerticalGroup(
            panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckArco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(medidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(arco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(medidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoArco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxTipoArco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medidaArcco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMedidaArco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medidaCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnNoHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addComponent(cbxTipoCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtMedidaCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mosquitero, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckMosquitero, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDetalleVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDetalleVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoCristalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoCristalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoCristalActionPerformed

    private void cbxTipoCanalilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoCanalilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoCanalilloActionPerformed

    private void cbxTipoArcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoArcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoArcoActionPerformed

    private void ckArcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckArcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckArcoActionPerformed

    private void ckMosquiteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckMosquiteroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckMosquiteroActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    /**
     * Carga los ComboBoxes con datos filtrando por tipo de material o desde el
     * Enum.
     */
    private void cargarDatosComboBox() {
        // Cargar los tipos de ventana desde el Enum
        cmbTipoVentana.removeAllItems();
        cmbTipoVentana.addItem("Seleccione...");
        for (modelo.TipoVentana tv : modelo.TipoVentana.values()) {
            cmbTipoVentana.addItem(tv.getDescripcion());
        }
        cmbTipoVentana.setSelectedIndex(0);

        // Cargar materiales filtrados por tipo
        cargarComboPorTipo(cmbTipoCristal, Material.TipoMaterial.VIDRIO);
        cargarComboPorTipo(cbxTipoArco, Material.TipoMaterial.ARCO);
        cargarComboPorTipo(cbxTipoCanalillo, Material.TipoMaterial.CANALILLO);
        //cargarComboPorTipo(cbxTipoZoclo, Material.TipoMaterial.ZOCLO);
        //cargarComboPorTipo(cbxTipoJunquillo, Material.TipoMaterial.JUNQUILLO);
        //cargarComboPorTipo(cbxTipoTapa, Material.TipoMaterial.TAPA);
        // cargarComboPorTipo(cbxTipoBolsa, Material.TipoMaterial.BOLSA);
        // cargarComboPorTipo(cbxTipoPerfil, Material.TipoMaterial.PERFIL);
    }

    /**
     * Llena un JComboBox filtrando la lista de materiales por el tipo de
     * material.
     *
     * @param combo El JComboBox a llenar.
     * @param tipo El tipo de material a filtrar.
     */
    private void cargarComboPorTipo(JComboBox<String> combo, Material.TipoMaterial tipo) {
        combo.removeAllItems();
        combo.addItem("Seleccione"); // Opción inicial vacía obligatoria

        if (materialesDisponibles != null && !materialesDisponibles.isEmpty()) {
            for (Material m : materialesDisponibles) {
                if (m.getTipo() == tipo) {
                    combo.addItem(m.getDescripcion());
                }
            }
        } else {
            combo.addItem("No hay materiales disponibles");
        }

        combo.setSelectedIndex(0);
    }

    /**
     * Configura los listeners para la lógica (ej. habilitar/deshabilitar
     * campos).
     */
    private void configurarListeners() {
        cbxTipoArco.setEnabled(false);
        txtMedidaArco.setEnabled(false);

        ckArco.addActionListener(e -> {
            boolean seleccionado = ckArco.isSelected();
            cbxTipoArco.setEnabled(seleccionado);
            txtMedidaArco.setEnabled(seleccionado);
            if (!seleccionado) {
                cbxTipoArco.setSelectedIndex(0);
                txtMedidaArco.setText("");
            }
        });

    }

    public modelo.VentanaDetalle getDetalle() {
        modelo.VentanaDetalle d = new modelo.VentanaDetalle();

        try {
            System.out.println("=== INICIANDO getDetalle() ===");

            // Validar que catalogoDAO esté inicializado
            if (catalogoDAO != null) {
                d.setTipoTrabajo(catalogoDAO.obtenerPorId(1));
            } else {
                throw new RuntimeException("CatalogoDAO no inicializado.");
            }

            // VALIDAR MEDIDAS PRINCIPALES
            if (txtMedidaH.getText().trim().isEmpty() || txtMedidaV.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar las medidas horizontal y vertical.",
                        "Campos obligatorios", JOptionPane.WARNING_MESSAGE);
                return null;
            }

            BigDecimal medidaH, medidaV;
            BigDecimal maxAncho = new BigDecimal("10"); // máximo 10 metros ancho
            BigDecimal maxAlto = new BigDecimal("15");  // máximo 15 metros alto

            try {
                medidaH = new BigDecimal(txtMedidaH.getText());
                medidaV = new BigDecimal(txtMedidaV.getText());

                if (medidaH.compareTo(BigDecimal.ZERO) <= 0 || medidaV.compareTo(BigDecimal.ZERO) <= 0) {
                    JOptionPane.showMessageDialog(this, "Las medidas deben ser mayores que cero.",
                            "Valor inválido", JOptionPane.WARNING_MESSAGE);
                    return null;
                }

                if (medidaH.compareTo(maxAncho) > 0 || medidaV.compareTo(maxAlto) > 0) {
                    JOptionPane.showMessageDialog(this,
                            "Las medidas exceden el rango permitido.\n"
                            + "Máximo permitido: " + maxAncho + " m de ancho y " + maxAlto + " m de alto.",
                            "Medidas fuera de rango", JOptionPane.WARNING_MESSAGE);
                    return null;
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Las medidas deben ser numéricas válidas.",
                        "Error de formato", JOptionPane.ERROR_MESSAGE);
                return null;
            }

            // VALIDAR SELECCIONES REQUERIDAS
            if (cmbTipoVentana.getSelectedIndex() < 0) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de ventana.",
                        "Falta selección", JOptionPane.WARNING_MESSAGE);
                return null;
            }

            if (cmbTipoCristal.getSelectedIndex() < 0 || "Error al cargar".equals(cmbTipoCristal.getSelectedItem())) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de cristal válido.",
                        "Falta selección", JOptionPane.WARNING_MESSAGE);
                return null;
            }

            // VALIDAR ARCO (opcional)
            d.setArco(ckArco.isSelected());
            if (d.isArco()) {
                if (cbxTipoArco.getSelectedIndex() < 0) {
                    JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de arco.",
                            "Campo requerido", JOptionPane.WARNING_MESSAGE);
                    return null;
                }
                if (txtMedidaArco.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar la medida del arco.",
                            "Campo requerido", JOptionPane.WARNING_MESSAGE);
                    return null;
                }

                try {
                    BigDecimal medidaArcoBD = new BigDecimal(txtMedidaArco.getText());
                    if (medidaArcoBD.compareTo(BigDecimal.ZERO) <= 0) {
                        JOptionPane.showMessageDialog(this, "La medida del arco debe ser mayor que 0.",
                                "Valor inválido", JOptionPane.WARNING_MESSAGE);
                        return null;
                    }
                    if (medidaArcoBD.compareTo(maxAlto) > 0) {
                        JOptionPane.showMessageDialog(this,
                                "La medida del arco excede el máximo permitido de " + maxAlto + " metros.",
                                "Medida fuera de rango", JOptionPane.WARNING_MESSAGE);
                        return null;
                    }
                    d.setTipoArco((String) cbxTipoArco.getSelectedItem());
                    d.setMedidaArco(medidaArcoBD);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "La medida del arco debe ser numérica.",
                            "Error de formato", JOptionPane.ERROR_MESSAGE);
                    return null;
                }
            } else {
                d.setMedidaArco(null);
                d.setTipoArco(null);
            }

            // VALIDAR CANALILLO
            if (cbxTipoCanalillo.getSelectedIndex() < 0) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de canalillo.",
                        "Campo requerido", JOptionPane.WARNING_MESSAGE);
                return null;
            }

            if (txtMedidaCanalillo.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar la medida del canalillo.",
                        "Campo requerido", JOptionPane.WARNING_MESSAGE);
                txtMedidaCanalillo.requestFocus();
                return null;
            }

            BigDecimal medidaCanalilloBD;
            try {
                medidaCanalilloBD = new BigDecimal(txtMedidaCanalillo.getText());
                if (medidaCanalilloBD.compareTo(BigDecimal.ZERO) <= 0) {
                    JOptionPane.showMessageDialog(this, "La medida del canalillo debe ser mayor que 0.",
                            "Valor inválido", JOptionPane.WARNING_MESSAGE);
                    txtMedidaCanalillo.requestFocus();
                    return null;
                }
                if (medidaCanalilloBD.compareTo(maxAncho) > 0) {
                    JOptionPane.showMessageDialog(this,
                            "La medida del canalillo excede el máximo permitido de " + maxAncho + " metros.",
                            "Medida fuera de rango", JOptionPane.WARNING_MESSAGE);
                    txtMedidaCanalillo.requestFocus();
                    return null;
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "La medida del canalillo debe ser numérica.",
                        "Error de formato", JOptionPane.ERROR_MESSAGE);
                return null;
            }

            // VALIDAR DESCRIPCIÓN
            if (txtDescripcion.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "La descripción es obligatoria.",
                        "Campo requerido", JOptionPane.WARNING_MESSAGE);
                txtDescripcion.requestFocus();
                return null;
            }

            // CONSTRUIR OBJETO VentanaDetalle
            d.setMedidaHorizontal(medidaH);
            d.setMedidaVertical(medidaV);
            d.setCantidad((Integer) spnCantidad.getValue());
            d.setTipoCristal((String) cmbTipoCristal.getSelectedItem());
            d.setNoHojas((Integer) spnNoHojas.getValue());
            d.setDescripcion(txtDescripcion.getText());
            d.setTipoVentana(modelo.TipoVentana.fromDescripcion((String) cmbTipoVentana.getSelectedItem()));
            d.setMosquitero(ckMosquitero.isSelected());
            d.setTipoCanalillo((String) cbxTipoCanalillo.getSelectedItem());
            d.setMedidaCanalillo(medidaCanalilloBD);

            // MATERIALES Y SUBTOTAL
            List<Material> materialesSeleccionados = obtenerMaterialesSeleccionados();
            List<MaterialDetalle> materialesDetalle = new ArrayList<>();

            for (Material m : materialesSeleccionados) {
                BigDecimal cantidad = BigDecimal.valueOf(d.getCantidad());
                BigDecimal precioUnitario = m.getPrecio();
                MaterialDetalle md = new MaterialDetalle(m, cantidad, precioUnitario);
                materialesDetalle.add(md);
            }

            d.setMateriales(materialesDetalle);

            BigDecimal subtotal = BigDecimal.ZERO;
            for (MaterialDetalle md : materialesDetalle) {
                subtotal = subtotal.add(md.getPrecioTotal());
            }
            d.setPrecioSoloUnaUnidadCalculado(subtotal);
            d.setSubtotalLinea(subtotal);

        } catch (Exception e) {
            System.err.println("Error en getDetalle(): " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        return d;
    }

    /**
     * para editar llena los campos del panel con datos de un detalle existente.
     *
     * @param detalle El detalle a cargar en el formulario.
     */
    public void setDetalle(modelo.VentanaDetalle detalle) {
        if (detalle == null) {
            return;
        }

        txtMedidaH.setText(detalle.getMedidaHorizontal().toPlainString());
        txtMedidaV.setText(detalle.getMedidaVertical().toPlainString());
        spnCantidad.setValue(detalle.getCantidad());
        cmbTipoCristal.setSelectedItem(detalle.getTipoCristal());
        spnNoHojas.setValue(detalle.getNoHojas());

        // txtPrecioUnidad.setText(detalle.getPrecioSoloUnaUnidadCalculado().toPlainString());
        // txtSubtotal.setText(detalle.getSubtotalLinea().toPlainString());
        txtDescripcion.setText(detalle.getDescripcion());

        if (detalle.getTipoVentana() != null) {
            cmbTipoVentana.setSelectedItem(detalle.getTipoVentana().getDescripcion());
        }

        ckMosquitero.setSelected(detalle.isMosquitero());
        ckArco.setSelected(detalle.isArco());

        boolean arcoSeleccionado = detalle.isArco();
        cbxTipoArco.setEnabled(arcoSeleccionado);
        txtMedidaArco.setEnabled(arcoSeleccionado);

        cbxTipoArco.setSelectedItem(detalle.getTipoArco());
        txtMedidaArco.setText(detalle.getMedidaArco() != null ? detalle.getMedidaArco().toPlainString() : "");

        cbxTipoCanalillo.setSelectedItem(detalle.getTipoCanalillo());
        txtMedidaCanalillo.setText(detalle.getMedidaCanalillo() != null ? detalle.getMedidaCanalillo().toPlainString() : "");
    }

    /**
     * Devuelve la lista de materiales seleccionados según los checkboxes y
     * comboboxes del panel de Ventana.
     */
    private List<Material> obtenerMaterialesSeleccionados() {
        List<Material> seleccionados = new ArrayList<>();

        // VIDRIO
        if (cmbTipoCristal.getSelectedItem() != null) {
            Material m = buscarMaterial(Material.TipoMaterial.VIDRIO, (String) cmbTipoCristal.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        // ARCO
        if (ckArco.isSelected() && cbxTipoArco.getSelectedItem() != null) {
            Material m = buscarMaterial(Material.TipoMaterial.ARCO, (String) cbxTipoArco.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        // CANALILLO
        if (cbxTipoCanalillo.getSelectedItem() != null) {
            Material m = buscarMaterial(Material.TipoMaterial.CANALILLO, (String) cbxTipoCanalillo.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        // MOSQUITERO (si aplica)
        if (ckMosquitero.isSelected()) {
            Material m = buscarMaterial(Material.TipoMaterial.MOSQUITERO, "Mosquitero");
            if (m != null) {
                seleccionados.add(m);
            }
        }

        return seleccionados;
    }

    /**
     * Busca un material dentro de la lista de materiales disponibles según tipo
     * y descripción.
     */
    private Material buscarMaterial(Material.TipoMaterial tipo, String descripcion) {
        if (materialesDisponibles == null) {
            return null;
        }

        for (Material m : materialesDisponibles) {
            if (m.getTipo() == tipo && m.getDescripcion().equals(descripcion)) {
                return m;
            }
        }
        return null;
    }

    private void permitirSoloNumeros(javax.swing.JTextField campo) {
        campo.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                char c = e.getKeyChar();
                // Permitir solo dígitos, punto decimal o borrar
                if (!Character.isDigit(c) && c != '.' && c != KeyEvent.VK_BACK_SPACE) {
                    e.consume();
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arco;
    private javax.swing.JLabel cantidad;
    private javax.swing.JComboBox<String> cbxTipoArco;
    private javax.swing.JComboBox<String> cbxTipoCanalillo;
    private javax.swing.JCheckBox ckArco;
    private javax.swing.JCheckBox ckMosquitero;
    private javax.swing.JComboBox<String> cmbTipoCristal;
    private javax.swing.JComboBox<String> cmbTipoVentana;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel medidaArcco;
    private javax.swing.JLabel medidaCanalillo;
    private javax.swing.JLabel medidaH;
    private javax.swing.JLabel medidaV;
    private javax.swing.JLabel mosquitero;
    private javax.swing.JLabel noHojas;
    private javax.swing.JPanel panelDetalleVentana;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JSpinner spnNoHojas;
    private javax.swing.JLabel tipoArco;
    private javax.swing.JLabel tipoCanalillo;
    private javax.swing.JLabel tipoCristal;
    private javax.swing.JLabel tipoVentana;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtMedidaArco;
    private javax.swing.JTextField txtMedidaCanalillo;
    private javax.swing.JTextField txtMedidaH;
    private javax.swing.JTextField txtMedidaV;
    // End of variables declaration//GEN-END:variables
}
