package presentacion;

import dao.CatalogoTrabajoDAO;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Material;

/**
 *
 * @author Vidrieria
 */
public class PanelDetalleVentana extends javax.swing.JPanel {

    private List<Material> materialesDisponibles;
    private CatalogoTrabajoDAO catalogoDAO;

    /**
     * Creates new form PanelDetalleVentana
     */
    public PanelDetalleVentana() {
        initComponents();
        configurarListeners();
    }

    /**
     * Prepara el panel.
     *
     * @param materialesVidrio La lista de materiales
     */
    public void inicializarDatos(List<Material> materialesVidrio) {
        this.materialesDisponibles = materialesVidrio;

        // Inicializa el DAO
        try {
            this.catalogoDAO = new CatalogoTrabajoDAO(utils.Conexion.getConnection());
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al conectar con BD para Catálogo", "Error DB", JOptionPane.ERROR_MESSAGE);
        }

        cargarDatosComboBox();

        // Configurar los Spinners de 1 a 100, con valor inicial 1
        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        spnNoHojas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDetalleVentana = new javax.swing.JPanel();
        medidaH = new javax.swing.JLabel();
        txtMedidaH = new javax.swing.JTextField();
        medidaV = new javax.swing.JLabel();
        txtMedidaV = new javax.swing.JTextField();
        panelTitulo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        tipoCristal = new javax.swing.JLabel();
        cmbTipoCristal = new javax.swing.JComboBox<>();
        noHojas = new javax.swing.JLabel();
        spnNoHojas = new javax.swing.JSpinner();
        tipoVentana = new javax.swing.JLabel();
        cmbTipoVentana = new javax.swing.JComboBox<>();
        mosquitero = new javax.swing.JLabel();
        ckMosquitero = new javax.swing.JCheckBox();
        arco = new javax.swing.JLabel();
        ckArco = new javax.swing.JCheckBox();
        tipoArco = new javax.swing.JLabel();
        cmbTipoArco = new javax.swing.JComboBox<>();
        medidaArcco = new javax.swing.JLabel();
        txtMedidaArco = new javax.swing.JTextField();
        tipoCanalillo = new javax.swing.JLabel();
        cbxTipoCanalillo = new javax.swing.JComboBox<>();
        medidaCanalillo = new javax.swing.JLabel();
        txtMedidaCanalillo = new javax.swing.JTextField();
        descripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();

        panelDetalleVentana.setBackground(new java.awt.Color(255, 255, 255));

        medidaH.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medidaH.setForeground(new java.awt.Color(0, 38, 115));
        medidaH.setText("Medida horizontal (m):");

        txtMedidaH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        medidaV.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medidaV.setForeground(new java.awt.Color(0, 38, 115));
        medidaV.setText("Medida vertical (m):");

        txtMedidaV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        panelTitulo.setBackground(new java.awt.Color(0, 19, 90));

        titulo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Detalles de Ventana");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(10, 10, 10))
        );

        cantidad.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cantidad.setForeground(new java.awt.Color(0, 38, 115));
        cantidad.setText("Cantidad:");

        tipoCristal.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoCristal.setForeground(new java.awt.Color(0, 38, 115));
        tipoCristal.setText("Tipo cristal:");

        cmbTipoCristal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTipoCristal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoCristal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoCristalActionPerformed(evt);
            }
        });

        noHojas.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        noHojas.setForeground(new java.awt.Color(0, 38, 115));
        noHojas.setText("No. hojas:");

        tipoVentana.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoVentana.setForeground(new java.awt.Color(0, 38, 115));
        tipoVentana.setText("Tipo ventana:");

        cmbTipoVentana.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTipoVentana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        mosquitero.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        mosquitero.setForeground(new java.awt.Color(0, 38, 115));
        mosquitero.setText("Mosquitero:");

        ckMosquitero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckMosquitero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckMosquiteroActionPerformed(evt);
            }
        });

        arco.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        arco.setForeground(new java.awt.Color(0, 38, 115));
        arco.setText("Arco:");

        ckArco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckArco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckArcoActionPerformed(evt);
            }
        });

        tipoArco.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoArco.setForeground(new java.awt.Color(0, 38, 115));
        tipoArco.setText("Tipo arco:");

        cmbTipoArco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTipoArco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoArco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoArcoActionPerformed(evt);
            }
        });

        medidaArcco.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medidaArcco.setForeground(new java.awt.Color(0, 38, 115));
        medidaArcco.setText("Medida arco (m):");

        txtMedidaArco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tipoCanalillo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoCanalillo.setForeground(new java.awt.Color(0, 38, 115));
        tipoCanalillo.setText("Tipo canalillo:");

        cbxTipoCanalillo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoCanalillo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoCanalillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoCanalilloActionPerformed(evt);
            }
        });

        medidaCanalillo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medidaCanalillo.setForeground(new java.awt.Color(0, 38, 115));
        medidaCanalillo.setText("Medida canalillo (m):");

        txtMedidaCanalillo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        descripcion.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        descripcion.setForeground(new java.awt.Color(0, 38, 115));
        descripcion.setText("Descripción:");

        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDetalleVentanaLayout = new javax.swing.GroupLayout(panelDetalleVentana);
        panelDetalleVentana.setLayout(panelDetalleVentanaLayout);
        panelDetalleVentanaLayout.setHorizontalGroup(
            panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTipoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnNoHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMedidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(108, 108, 108)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addComponent(medidaCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedidaCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68))
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medidaArcco, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(arco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tipoArco, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)
                                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbTipoArco, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ckArco)
                                            .addComponent(txtMedidaArco, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalleVentanaLayout.createSequentialGroup()
                                .addComponent(tipoCanalillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10)
                                .addComponent(cbxTipoCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66))))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addComponent(mosquitero, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ckMosquitero)
                        .addGap(66, 66, 66))))
        );
        panelDetalleVentanaLayout.setVerticalGroup(
            panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckArco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMedidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMedidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoArco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipoArco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medidaArcco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedidaArco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipoCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medidaCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedidaCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnNoHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mosquitero, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckMosquitero, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDetalleVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDetalleVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoCristalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoCristalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoCristalActionPerformed

    private void cbxTipoCanalilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoCanalilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoCanalilloActionPerformed

    private void cmbTipoArcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoArcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoArcoActionPerformed

    private void ckArcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckArcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckArcoActionPerformed

    private void ckMosquiteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckMosquiteroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckMosquiteroActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    /**
     * Carga los ComboBoxes con datos (Tipos de Ventana y Cristales).
     */
    private void cargarDatosComboBox() {
        // Cargar los tipos de ventana desde el Enum
        cmbTipoVentana.removeAllItems();
        for (modelo.TipoVentana tv : modelo.TipoVentana.values()) {
            cmbTipoVentana.addItem(tv.getDescripcion());
        }

        // cargar los tipos de cristal desde la lista de materiales
        cmbTipoCristal.removeAllItems();
        if (materialesDisponibles != null && !materialesDisponibles.isEmpty()) {
            for (modelo.Material vidrio : materialesDisponibles) {
                cmbTipoCristal.addItem(vidrio.getDescripcion());
            }
        } else {
            cmbTipoCristal.addItem("Error al cargar vidrios");
        }

        // cargar el tipo de arco
        cmbTipoArco.removeAllItems();
        cmbTipoArco.addItem("Ninguno");
        cmbTipoArco.addItem("Medio Punto");
        cmbTipoArco.addItem("Rebajado");

        // cargar los tipo de canalillo 
        cbxTipoCanalillo.removeAllItems();
        cbxTipoCanalillo.addItem("Ninguno");
        cbxTipoCanalillo.addItem("Aluminio");
        cbxTipoCanalillo.addItem("PVC");
    }

    /**
     * Configura los listeners para la lógica (ej. habilitar/deshabilitar
     * campos).
     */
    private void configurarListeners() {
        cmbTipoArco.setEnabled(false);
        txtMedidaArco.setEnabled(false);

        ckArco.addActionListener(e -> {
            boolean seleccionado = ckArco.isSelected();
            cmbTipoArco.setEnabled(seleccionado);
            txtMedidaArco.setEnabled(seleccionado);
            if (!seleccionado) {
                cmbTipoArco.setSelectedIndex(0);
                txtMedidaArco.setText("");
            }
        });

        // (Puedes añadir más listeners aquí)
    }

    /**
     * lee todos los campos del panel y crea un objeto VentanaDetalle.
     *
     * @return El objeto VentanaDetalle con los datos del formulario.
     */
    public modelo.VentanaDetalle getDetalle() {
        modelo.VentanaDetalle d = new modelo.VentanaDetalle();

        try {
            if (catalogoDAO != null) {
                d.setTipoTrabajo(catalogoDAO.obtenerPorId(1));
            } else {
                throw new RuntimeException("CatalogoDAO no inicializado.");
            }

            // Leer valores
            d.setMedidaHorizontal(new BigDecimal(txtMedidaH.getText().isEmpty() ? "0" : txtMedidaH.getText()));
            d.setMedidaVertical(new BigDecimal(txtMedidaV.getText().isEmpty() ? "0" : txtMedidaV.getText()));
            d.setCantidad((Integer) spnCantidad.getValue());
            d.setTipoCristal((String) cmbTipoCristal.getSelectedItem());
            d.setNoHojas((Integer) spnNoHojas.getValue());

            // Asigna 0 si no tienes estos campos
            d.setPrecioSoloUnaUnidadCalculado(BigDecimal.ZERO);
            d.setSubtotalLinea(BigDecimal.ZERO);

            d.setDescripcion(txtDescripcion.getText());

            String descVentana = (String) cmbTipoVentana.getSelectedItem();
            d.setTipoVentana(modelo.TipoVentana.fromDescripcion(descVentana));

            d.setMosquitero(ckMosquitero.isSelected());
            d.setArco(ckArco.isSelected());

            d.setTipoArco((String) cmbTipoArco.getSelectedItem());
            d.setMedidaArco(new BigDecimal(txtMedidaArco.getText().isEmpty() ? "0" : txtMedidaArco.getText()));

            d.setTipoCanalillo((String) cbxTipoCanalillo.getSelectedItem());
            d.setMedidaCanalillo(new BigDecimal(txtMedidaCanalillo.getText().isEmpty() ? "0" : txtMedidaCanalillo.getText()));

        } catch (Exception e) {
            System.err.println("Error al leer datos del panel: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Error en los datos: " + "Ocurrió un error al leer los campos. Verifique los números.\n" + e.getMessage(), "Error de Formato", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        return d;
    }

    /**
     * para editar llena los campos del panel con datos de un detalle existente.
     *
     * @param detalle El detalle a cargar en el formulario.
     */
    public void setDetalle(modelo.VentanaDetalle detalle) {
        if (detalle == null) {
            return;
        }

        txtMedidaH.setText(detalle.getMedidaHorizontal().toPlainString());
        txtMedidaV.setText(detalle.getMedidaVertical().toPlainString());
        spnCantidad.setValue(detalle.getCantidad());
        cmbTipoCristal.setSelectedItem(detalle.getTipoCristal());
        spnNoHojas.setValue(detalle.getNoHojas());

        // txtPrecioUnidad.setText(detalle.getPrecioSoloUnaUnidadCalculado().toPlainString());
        // txtSubtotal.setText(detalle.getSubtotalLinea().toPlainString());
        txtDescripcion.setText(detalle.getDescripcion());

        if (detalle.getTipoVentana() != null) {
            cmbTipoVentana.setSelectedItem(detalle.getTipoVentana().getDescripcion());
        }

        ckMosquitero.setSelected(detalle.isMosquitero());
        ckArco.setSelected(detalle.isArco());

        boolean arcoSeleccionado = detalle.isArco();
        cmbTipoArco.setEnabled(arcoSeleccionado);
        txtMedidaArco.setEnabled(arcoSeleccionado);

        cmbTipoArco.setSelectedItem(detalle.getTipoArco());
        txtMedidaArco.setText(detalle.getMedidaArco() != null ? detalle.getMedidaArco().toPlainString() : "");

        cbxTipoCanalillo.setSelectedItem(detalle.getTipoCanalillo());
        txtMedidaCanalillo.setText(detalle.getMedidaCanalillo() != null ? detalle.getMedidaCanalillo().toPlainString() : "");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arco;
    private javax.swing.JLabel cantidad;
    private javax.swing.JComboBox<String> cbxTipoCanalillo;
    private javax.swing.JCheckBox ckArco;
    private javax.swing.JCheckBox ckMosquitero;
    private javax.swing.JComboBox<String> cmbTipoArco;
    private javax.swing.JComboBox<String> cmbTipoCristal;
    private javax.swing.JComboBox<String> cmbTipoVentana;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel medidaArcco;
    private javax.swing.JLabel medidaCanalillo;
    private javax.swing.JLabel medidaH;
    private javax.swing.JLabel medidaV;
    private javax.swing.JLabel mosquitero;
    private javax.swing.JLabel noHojas;
    private javax.swing.JPanel panelDetalleVentana;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JSpinner spnNoHojas;
    private javax.swing.JLabel tipoArco;
    private javax.swing.JLabel tipoCanalillo;
    private javax.swing.JLabel tipoCristal;
    private javax.swing.JLabel tipoVentana;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtMedidaArco;
    private javax.swing.JTextField txtMedidaCanalillo;
    private javax.swing.JTextField txtMedidaH;
    private javax.swing.JTextField txtMedidaV;
    // End of variables declaration//GEN-END:variables
}
