package presentacion;

import dao.CatalogoTrabajoDAO;
import dao.MaterialDetalleDAO;
import dao.VentanaDetalleDAO;
import java.awt.Frame;
import java.awt.Window;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import modelo.Material;
import modelo.MaterialDetalle;

/**
 *
 * @author Vidrieria
 */
public class PanelDetalleVentana extends javax.swing.JPanel {

    private List<Material> materialesDisponibles;
    private CatalogoTrabajoDAO catalogoDAO;

    private modelo.VentanaDetalle detalleTemp; // si quieres mantener estado temporal (opcional)

    /**
     * Creates new form PanelDetalleVentana
     */
    public PanelDetalleVentana() {
        initComponents();
        configurarListeners();
    }

    /**
     * Prepara el panel con los materiales disponibles.
     *
     * @param materiales La lista de materiales
     */
    public void inicializarDatos(List<Material> materiales) {
        this.materialesDisponibles = materiales;

        // Inicializa el DAO (para obtener el tipo de trabajo)
        try {
            this.catalogoDAO = new CatalogoTrabajoDAO(utils.Conexion.getConnection());
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al conectar con BD para Catálogo", "Error DB", JOptionPane.ERROR_MESSAGE);
        }

        cargarDatosComboBox();

        // Configurar los Spinners
        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        spnNoHojas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        spnNoEscuadras.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        // Validar campos de texto para permitir solo números
        permitirSoloNumeros(txtMedidaH);
        permitirSoloNumeros(txtMedidaV);
        permitirSoloNumeros(txtMedidaCanalillo);
        permitirSoloNumeros(txtMedidaArco);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDetalleVentana = new javax.swing.JPanel();
        medidaH = new javax.swing.JLabel();
        txtMedidaH = new javax.swing.JTextField();
        medidaV = new javax.swing.JLabel();
        txtMedidaV = new javax.swing.JTextField();
        panelTitulo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        tipoCristal = new javax.swing.JLabel();
        cmbTipoCristal = new javax.swing.JComboBox<>();
        noHojas = new javax.swing.JLabel();
        spnNoHojas = new javax.swing.JSpinner();
        tipoVentana = new javax.swing.JLabel();
        cmbTipoVentana = new javax.swing.JComboBox<>();
        mosquitero = new javax.swing.JLabel();
        ckMosquitero = new javax.swing.JCheckBox();
        arco = new javax.swing.JLabel();
        ckArco = new javax.swing.JCheckBox();
        tipoArco = new javax.swing.JLabel();
        cbxTipoArco = new javax.swing.JComboBox<>();
        medidaArcco = new javax.swing.JLabel();
        txtMedidaArco = new javax.swing.JTextField();
        tipoCanalillo = new javax.swing.JLabel();
        cbxTipoCanalillo = new javax.swing.JComboBox<>();
        medidaCanalillo = new javax.swing.JLabel();
        txtMedidaCanalillo = new javax.swing.JTextField();
        descripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        tipoMosquitero = new javax.swing.JLabel();
        cbxTipoMosquitero = new javax.swing.JComboBox<>();
        noEscuadras = new javax.swing.JLabel();
        spnNoEscuadras = new javax.swing.JSpinner();
        tela = new javax.swing.JLabel();
        cbxTelas = new javax.swing.JComboBox<>();
        largoTela = new javax.swing.JLabel();
        txtLargoTela = new javax.swing.JTextField();
        tipoPerfil = new javax.swing.JLabel();
        cbxTipoPerfil = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1213, 356));

        panelDetalleVentana.setBackground(new java.awt.Color(255, 255, 255));

        medidaH.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medidaH.setForeground(new java.awt.Color(0, 38, 115));
        medidaH.setText("Medida horizontal (m):");

        txtMedidaH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        medidaV.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medidaV.setForeground(new java.awt.Color(0, 38, 115));
        medidaV.setText("Medida vertical (m):");

        txtMedidaV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        panelTitulo.setBackground(new java.awt.Color(0, 19, 90));

        titulo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Detalles de Ventana");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(titulo)
                .addContainerGap(1024, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(10, 10, 10))
        );

        cantidad.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cantidad.setForeground(new java.awt.Color(0, 38, 115));
        cantidad.setText("Cantidad:");

        tipoCristal.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoCristal.setForeground(new java.awt.Color(0, 38, 115));
        tipoCristal.setText("Tipo cristal:");

        cmbTipoCristal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTipoCristal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoCristal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoCristalActionPerformed(evt);
            }
        });

        noHojas.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        noHojas.setForeground(new java.awt.Color(0, 38, 115));
        noHojas.setText("No. hojas:");

        tipoVentana.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoVentana.setForeground(new java.awt.Color(0, 38, 115));
        tipoVentana.setText("Tipo ventana:");

        cmbTipoVentana.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTipoVentana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        mosquitero.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        mosquitero.setForeground(new java.awt.Color(0, 38, 115));
        mosquitero.setText("Mosquitero:");

        ckMosquitero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckMosquitero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckMosquiteroActionPerformed(evt);
            }
        });

        arco.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        arco.setForeground(new java.awt.Color(0, 38, 115));
        arco.setText("Arco:");

        ckArco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckArco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckArcoActionPerformed(evt);
            }
        });

        tipoArco.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoArco.setForeground(new java.awt.Color(0, 38, 115));
        tipoArco.setText("Tipo arco:");

        cbxTipoArco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoArco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoArco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoArcoActionPerformed(evt);
            }
        });

        medidaArcco.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medidaArcco.setForeground(new java.awt.Color(0, 38, 115));
        medidaArcco.setText("Altura arco (m):");

        txtMedidaArco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tipoCanalillo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoCanalillo.setForeground(new java.awt.Color(0, 38, 115));
        tipoCanalillo.setText("Tipo canalillo:");

        cbxTipoCanalillo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoCanalillo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoCanalillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoCanalilloActionPerformed(evt);
            }
        });

        medidaCanalillo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medidaCanalillo.setForeground(new java.awt.Color(0, 38, 115));
        medidaCanalillo.setText("Medida canalillo (m):");

        txtMedidaCanalillo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        descripcion.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        descripcion.setForeground(new java.awt.Color(0, 38, 115));
        descripcion.setText("Descripción:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        tipoMosquitero.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoMosquitero.setForeground(new java.awt.Color(0, 38, 115));
        tipoMosquitero.setText("Tipo mosquitero:");

        cbxTipoMosquitero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoMosquitero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoMosquitero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoMosquiteroActionPerformed(evt);
            }
        });

        noEscuadras.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        noEscuadras.setForeground(new java.awt.Color(0, 38, 115));
        noEscuadras.setText("No. escuadras:");

        tela.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tela.setForeground(new java.awt.Color(0, 38, 115));
        tela.setText("Tela:");

        cbxTelas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTelasActionPerformed(evt);
            }
        });

        largoTela.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        largoTela.setForeground(new java.awt.Color(0, 38, 115));
        largoTela.setText("Largo Tela (m):");

        txtLargoTela.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tipoPerfil.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoPerfil.setForeground(new java.awt.Color(0, 38, 115));
        tipoPerfil.setText("Tipo perfil:");

        cbxTipoPerfil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDetalleVentanaLayout = new javax.swing.GroupLayout(panelDetalleVentana);
        panelDetalleVentana.setLayout(panelDetalleVentanaLayout);
        panelDetalleVentanaLayout.setHorizontalGroup(
            panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addGap(428, 428, 428)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medidaArcco, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(arco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tipoArco, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tipoCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(medidaCanalillo))
                                .addGap(10, 10, 10)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxTipoCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedidaCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxTipoArco, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ckArco)
                                    .addComponent(txtMedidaArco, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tipoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tipoMosquitero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mosquitero, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxTipoPerfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ckMosquitero)
                                    .addComponent(cbxTipoMosquitero, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(medidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noHojas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbTipoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbTipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMedidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMedidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(spnNoHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addGap(428, 428, 428)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tela, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(largoTela, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLargoTela, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxTelas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addComponent(noEscuadras, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(spnNoEscuadras, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        panelDetalleVentanaLayout.setVerticalGroup(
            panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckArco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                        .addComponent(arco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tipoArco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxTipoArco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(12, 12, 12)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medidaArcco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedidaArco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tipoCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxTipoCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medidaCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedidaCanalillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(medidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(medidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tipoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbTipoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbTipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(noHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnNoHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                    .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(noEscuadras, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnNoEscuadras, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tela, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbxTelas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtLargoTela, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                    .addGap(77, 77, 77)
                                    .addComponent(largoTela, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mosquitero, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ckMosquitero, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxTipoMosquitero, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoMosquitero, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tipoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxTipoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(37, 37, 37))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDetalleVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDetalleVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoCristalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoCristalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoCristalActionPerformed

    private void cbxTipoCanalilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoCanalilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoCanalilloActionPerformed

    private void cbxTipoArcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoArcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoArcoActionPerformed

    private void ckArcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckArcoActionPerformed


    }//GEN-LAST:event_ckArcoActionPerformed

    private void ckMosquiteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckMosquiteroActionPerformed

    }//GEN-LAST:event_ckMosquiteroActionPerformed

    private void cbxTipoMosquiteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoMosquiteroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoMosquiteroActionPerformed

    private void cbxTelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTelasActionPerformed

    private void cbxTipoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoPerfilActionPerformed

    /**
     * Carga los ComboBoxes con datos filtrando por tipo de material o desde el
     * Enum.
     */
    private void cargarDatosComboBox() {
        // Tipo de ventana (enum)
        cmbTipoVentana.removeAllItems();
        cmbTipoVentana.addItem("Seleccione...");
        for (modelo.TipoVentana tv : modelo.TipoVentana.values()) {
            cmbTipoVentana.addItem(tv.getDescripcion());
        }
        cmbTipoVentana.setSelectedIndex(0);

        // Cargar materiales filtrados por tipo (cada combo incluye opción inicial)
        cargarComboPorTipo(cmbTipoCristal, Material.TipoMaterial.VIDRIO);
        cargarComboPorTipo(cbxTipoArco, Material.TipoMaterial.ARCO);
        cargarComboPorTipo(cbxTipoCanalillo, Material.TipoMaterial.CANALILLO);
        cargarComboPorTipo(cbxTipoMosquitero, Material.TipoMaterial.MOSQUITERO);
        cargarComboPorTipo(cbxTelas, Material.TipoMaterial.TELA);
        cargarComboPorTipo(cbxTipoPerfil, Material.TipoMaterial.PERFIL);
    }

    private void cargarComboPorTipo(JComboBox<String> combo, Material.TipoMaterial tipo) {
        combo.removeAllItems();
        combo.addItem("Seleccione"); // opción inicial

        if (materialesDisponibles != null && !materialesDisponibles.isEmpty()) {
            for (Material m : materialesDisponibles) {
                if (m.getTipo() == tipo) {
                    combo.addItem(m.getDescripcion());
                }
            }
        } else {
            combo.addItem("No hay materiales disponibles");
        }

        combo.setSelectedIndex(0);
    }

    /**
     * Configura los listeners para la lógica (habilitar/deshabilitar campos).
     */
    private void configurarListeners() {
        cbxTipoArco.setEnabled(false);
        txtMedidaArco.setEnabled(false);

        ckArco.addActionListener(e -> {
            boolean seleccionado = ckArco.isSelected();
            cbxTipoArco.setEnabled(seleccionado);
            txtMedidaArco.setEnabled(seleccionado);
            if (!seleccionado) {
                cbxTipoArco.setSelectedIndex(0);
                txtMedidaArco.setText("");
            }
        });

        //mosquitero
        cbxTipoMosquitero.setEnabled(false);
        cbxTipoPerfil.setEnabled(false);
        spnNoEscuadras.setEnabled(false);
        cbxTelas.setEnabled(false);
        txtLargoTela.setEnabled(false);

        ckMosquitero.addActionListener(e -> {
            boolean seleccionado = ckMosquitero.isSelected();
            cbxTipoMosquitero.setEnabled(seleccionado);
            cbxTipoPerfil.setEnabled(seleccionado);
            spnNoEscuadras.setEnabled(seleccionado);
            cbxTelas.setEnabled(seleccionado);
            txtLargoTela.setEnabled(seleccionado);
            if (!seleccionado) {
                cbxTipoMosquitero.setSelectedIndex(0);
                cbxTipoPerfil.setSelectedIndex(0);
                spnNoEscuadras.setValue(0);
                cbxTelas.setSelectedIndex(0);
                txtLargoTela.setText("");
            }
        });

    }

    /**
     * Lee todos los campos del panel y crea un objeto VentanaDetalle.
     *
     * @return VentanaDetalle si todo es válido, o null si hay error de
     * validación.
     */
    public modelo.VentanaDetalle getDetalle() {

        modelo.VentanaDetalle d = new modelo.VentanaDetalle();

        // Variables que DEBEN existir incluso si se retorna antes
        BigDecimal medidaH = null;
        BigDecimal medidaV = null;
        BigDecimal medidaCanalilloBD = null;

        try {
            // ============================================
            // VALIDAR TIPO DE TRABAJO
            // ============================================
            if (catalogoDAO != null) {
                d.setTipoTrabajo(catalogoDAO.obtenerPorId(1));
            } else {
                throw new RuntimeException("CatalogoDAO no inicializado.");
            }

            // ============================================
            // VALIDAR MEDIDAS PRINCIPALES
            // ============================================
            if (txtMedidaH.getText().trim().isEmpty() || txtMedidaV.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Debe ingresar las medidas horizontal y vertical.",
                        "Campos obligatorios",
                        JOptionPane.WARNING_MESSAGE);
                return null;
            }

            BigDecimal maxAncho = new BigDecimal("15");
            BigDecimal maxAlto = new BigDecimal("10");

            try {
                medidaH = new BigDecimal(txtMedidaH.getText().trim());
                medidaV = new BigDecimal(txtMedidaV.getText().trim());

                if (medidaH.compareTo(BigDecimal.ZERO) <= 0
                        || medidaV.compareTo(BigDecimal.ZERO) <= 0) {

                    JOptionPane.showMessageDialog(this,
                            "Las medidas deben ser mayores que cero.",
                            "Valor inválido",
                            JOptionPane.WARNING_MESSAGE);
                    return null;
                }

                if (medidaH.compareTo(maxAncho) > 0
                        || medidaV.compareTo(maxAlto) > 0) {

                    JOptionPane.showMessageDialog(this,
                            "Las medidas exceden el rango permitido:\n"
                            + "Máximo 15m ancho y 10m alto.",
                            "Medidas fuera de rango",
                            JOptionPane.WARNING_MESSAGE);
                    return null;
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this,
                        "Las medidas deben ser numéricas válidas.",
                        "Error de formato",
                        JOptionPane.ERROR_MESSAGE);
                return null;
            }

            // ASIGNACIÓN SEGURA DE MEDIDAS
            d.setMedidaHorizontal(medidaH);
            d.setMedidaVertical(medidaV);

            // ============================================
            // VALIDAR TIPO DE VENTANA Y CRISTAL
            // ============================================
            if (cmbTipoVentana.getSelectedIndex() <= 0) {
                JOptionPane.showMessageDialog(this,
                        "Debe seleccionar un tipo de ventana.",
                        "Falta selección",
                        JOptionPane.WARNING_MESSAGE);
                return null;
            }

            if (cmbTipoCristal.getSelectedIndex() <= 0
                    || "No hay materiales disponibles".equals(cmbTipoCristal.getSelectedItem())) {

                JOptionPane.showMessageDialog(this,
                        "Debe seleccionar un tipo de cristal válido.",
                        "Falta selección",
                        JOptionPane.WARNING_MESSAGE);
                return null;
            }

            // ============================================
            // VALIDAR ARCO
            // ============================================
            d.setArco(ckArco.isSelected());
            if (d.isArco()) {

                if (cbxTipoArco.getSelectedIndex() <= 0) {
                    JOptionPane.showMessageDialog(this,
                            "Debe seleccionar un tipo de arco.",
                            "Falta selección",
                            JOptionPane.WARNING_MESSAGE);
                    return null;
                }

                if (txtMedidaArco.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this,
                            "Debe ingresar la medida del arco.",
                            "Campo requerido",
                            JOptionPane.WARNING_MESSAGE);
                    return null;
                }

                try {
                    BigDecimal medidaArcoBD = new BigDecimal(txtMedidaArco.getText().trim());

                    if (medidaArcoBD.compareTo(BigDecimal.ZERO) <= 0) {
                        JOptionPane.showMessageDialog(this,
                                "La medida del arco debe ser mayor que 0.",
                                "Valor inválido",
                                JOptionPane.WARNING_MESSAGE);
                        return null;
                    }

                    if (medidaArcoBD.compareTo(maxAlto) > 0) {
                        JOptionPane.showMessageDialog(this,
                                "La medida del arco excede el máximo permitido de 10 metros.",
                                "Medida fuera de rango",
                                JOptionPane.WARNING_MESSAGE);
                        return null;
                    }

                    d.setTipoArco((String) cbxTipoArco.getSelectedItem());
                    d.setMedidaArco(medidaArcoBD);

                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this,
                            "La medida del arco debe ser numérica.",
                            "Error de formato",
                            JOptionPane.ERROR_MESSAGE);
                    return null;
                }

            } else {
                d.setMedidaArco(null);
                d.setTipoArco(null);
            }

            // ============================================
            // VALIDAR CANALILLO
            // ============================================
            if (cbxTipoCanalillo.getSelectedIndex() <= 0) {
                JOptionPane.showMessageDialog(this,
                        "Debe seleccionar un tipo de canalillo.",
                        "Campo requerido",
                        JOptionPane.WARNING_MESSAGE);
                return null;
            }

            if (txtMedidaCanalillo.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Debe ingresar la medida del canalillo.",
                        "Campo requerido",
                        JOptionPane.WARNING_MESSAGE);
                return null;
            }

            try {
                medidaCanalilloBD = new BigDecimal(txtMedidaCanalillo.getText().trim());

                if (medidaCanalilloBD.compareTo(BigDecimal.ZERO) <= 0) {
                    JOptionPane.showMessageDialog(this,
                            "La medida del canalillo debe ser mayor que 0.",
                            "Valor inválido",
                            JOptionPane.WARNING_MESSAGE);
                    return null;
                }

                if (medidaCanalilloBD.compareTo(maxAncho) > 0) {
                    JOptionPane.showMessageDialog(this,
                            "La medida del canalillo excede el máximo permitido de 15 metros.",
                            "Medida fuera de rango",
                            JOptionPane.WARNING_MESSAGE);
                    return null;
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this,
                        "La medida del canalillo debe ser numérica.",
                        "Error de formato",
                        JOptionPane.ERROR_MESSAGE);
                return null;
            }

            // ============================================
            // VALIDAR MOSQUITEROS
            // ============================================
            d.setMosquitero(ckMosquitero.isSelected());

            if (d.isMosquitero()) {

                // ---- Tipo de mosquitero ----
                if (cbxTipoMosquitero.getSelectedIndex() <= 0) {
                    JOptionPane.showMessageDialog(this,
                            "Debe seleccionar un tipo de mosquitero.",
                            "Falta selección",
                            JOptionPane.WARNING_MESSAGE);
                    return null;
                }
                d.setTipoMosquitero((String) cbxTipoMosquitero.getSelectedItem());

                // ---- Tipo de perfil ----
                if (cbxTipoPerfil.getSelectedIndex() <= 0) {
                    JOptionPane.showMessageDialog(this,
                            "Debe seleccionar un tipo de perfil.",
                            "Falta selección",
                            JOptionPane.WARNING_MESSAGE);
                    return null;
                }
                d.setTipoPerfil((String) cbxTipoPerfil.getSelectedItem());

                // ---- Número de escuadras ----
                int noEscuadras = (int) spnNoEscuadras.getValue();
                if (noEscuadras <= 0) {
                    JOptionPane.showMessageDialog(this,
                            "El número de escuadras debe ser mayor que 0.",
                            "Valor inválido",
                            JOptionPane.WARNING_MESSAGE);
                    return null;
                }
                d.setNoEscuadras(noEscuadras);

                // ---- Tipo de tela ----
                if (cbxTelas.getSelectedIndex() <= 0) {
                    JOptionPane.showMessageDialog(this,
                            "Debe seleccionar un tipo de tela.",
                            "Falta selección",
                            JOptionPane.WARNING_MESSAGE);
                    return null;
                }
                d.setTipoTela((String) cbxTelas.getSelectedItem());

                // ---- Largo de tela ----
                if (txtLargoTela.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this,
                            "Debe ingresar el largo de la tela.",
                            "Campo requerido",
                            JOptionPane.WARNING_MESSAGE);
                    return null;
                }

                try {
                    BigDecimal largoTelaBD = new BigDecimal(txtLargoTela.getText().trim());

                    if (largoTelaBD.compareTo(BigDecimal.ZERO) <= 0) {
                        JOptionPane.showMessageDialog(this,
                                "El largo de la tela debe ser mayor que 0.",
                                "Valor inválido",
                                JOptionPane.WARNING_MESSAGE);
                        return null;
                    }

                    if (largoTelaBD.compareTo(maxAlto) > 0) {
                        JOptionPane.showMessageDialog(this,
                                "El largo de la tela excede el máximo permitido de 10 metros.",
                                "Medida fuera de rango",
                                JOptionPane.WARNING_MESSAGE);
                        return null;
                    }

                    d.setLargoTela(largoTelaBD);

                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this,
                            "El largo de la tela debe ser numérico.",
                            "Error de formato",
                            JOptionPane.ERROR_MESSAGE);
                    return null;
                }

            } else {
                // Si no hay mosquitero, limpiar los campos relacionados
                d.setTipoMosquitero(null);
                d.setTipoPerfil(null);
                d.setNoEscuadras(0);
                d.setTipoTela(null);
                d.setLargoTela(null);
            }

            // ============================================
            // DESCRIPCIÓN
            // ============================================
            if (txtDescripcion.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "La descripción es obligatoria.",
                        "Campo requerido",
                        JOptionPane.WARNING_MESSAGE);
                return null;
            }

            // ============================================
            // CONSTRUIR OBJETO COMPLETO
            // ============================================
            d.setCantidad((Integer) spnCantidad.getValue());
            d.setTipoCristal((String) cmbTipoCristal.getSelectedItem());
            d.setNoHojas((Integer) spnNoHojas.getValue());
            d.setDescripcion(txtDescripcion.getText().trim());
            d.setTipoVentana(modelo.TipoVentana.fromDescripcion(
                    (String) cmbTipoVentana.getSelectedItem()));
            d.setMosquitero(ckMosquitero.isSelected());
            d.setTipoCanalillo((String) cbxTipoCanalillo.getSelectedItem());
            d.setMedidaCanalillo(medidaCanalilloBD);

            if (d.isMosquitero()) {
                d.setTipoMosquitero((String) cbxTipoMosquitero.getSelectedItem());
                d.setTipoPerfil((String) cbxTipoPerfil.getSelectedItem());
                d.setNoEscuadras((Integer) spnNoEscuadras.getValue());
                d.setTipoTela((String) cbxTelas.getSelectedItem());

                BigDecimal largoTelaBD = new BigDecimal(txtLargoTela.getText().trim());
                d.setLargoTela(largoTelaBD);
            } else {
                d.setTipoMosquitero(null);
                d.setTipoPerfil(null);
                d.setNoEscuadras(0);
                d.setTipoTela(null);
                d.setLargoTela(null);
            }

            // ============================================
            // MATERIALES & SUBTOTAL
            // ============================================
            List<Material> materialesSeleccionados = obtenerMaterialesSeleccionados();
            List<MaterialDetalle> materialesDetalle = new ArrayList<>();

            for (Material m : materialesSeleccionados) {
                BigDecimal cantidadBD = BigDecimal.valueOf(d.getCantidad());
                materialesDetalle.add(new MaterialDetalle(m, cantidadBD, m.getPrecio()));
            }

            d.setMateriales(materialesDetalle);

            BigDecimal subtotal = BigDecimal.ZERO;
            for (MaterialDetalle md : materialesDetalle) {
                subtotal = subtotal.add(md.getPrecioTotal());
            }

            d.setPrecioSoloUnaUnidadCalculado(subtotal);
            d.setSubtotalLinea(subtotal);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return null;
        }

        return d;
    }

    /**
     * para editar llena los campos del panel con datos de un detalle existente.
     *
     * @param detalle El detalle a cargar en el formulario.
     */
    public void setDetalle(modelo.VentanaDetalle detalle) {
        if (detalle == null) {
            return;
        }

        txtMedidaH.setText(detalle.getMedidaHorizontal().toPlainString());
        txtMedidaV.setText(detalle.getMedidaVertical().toPlainString());
        spnCantidad.setValue(detalle.getCantidad());
        cmbTipoCristal.setSelectedItem(detalle.getTipoCristal());
        spnNoHojas.setValue(detalle.getNoHojas());
        txtDescripcion.setText(detalle.getDescripcion());

        if (detalle.getTipoVentana() != null) {
            cmbTipoVentana.setSelectedItem(detalle.getTipoVentana().getDescripcion());
        }

        ckMosquitero.setSelected(detalle.isMosquitero());
        ckArco.setSelected(detalle.isArco());

        boolean arcoSeleccionado = detalle.isArco();
        cbxTipoArco.setEnabled(arcoSeleccionado);
        txtMedidaArco.setEnabled(arcoSeleccionado);

        cbxTipoArco.setSelectedItem(detalle.getTipoArco());
        txtMedidaArco.setText(detalle.getMedidaArco() != null ? detalle.getMedidaArco().toPlainString() : "");

        cbxTipoCanalillo.setSelectedItem(detalle.getTipoCanalillo());
        txtMedidaCanalillo.setText(detalle.getMedidaCanalillo() != null ? detalle.getMedidaCanalillo().toPlainString() : "");

        //mosquitero
        boolean mosquiteroSeleccionado = detalle.isMosquitero();
        cbxTipoMosquitero.setEnabled(mosquiteroSeleccionado);
        cbxTipoPerfil.setEnabled(mosquiteroSeleccionado);
        spnNoEscuadras.setEnabled(mosquiteroSeleccionado);
        cbxTelas.setEnabled(mosquiteroSeleccionado);
        txtLargoTela.setEnabled(mosquiteroSeleccionado);

        cbxTipoMosquitero.setSelectedItem(detalle.getTipoMosquitero());
        cbxTipoPerfil.setSelectedItem(detalle.getTipoPerfil());
        spnNoEscuadras.setValue(detalle.getNoEscuadras());
        cbxTelas.setSelectedItem(detalle.getTipoTela());
        txtLargoTela.setText(detalle.getLargoTela() != null ? detalle.getLargoTela().toPlainString() : "");

    }

    /**
     * Devuelve la lista de materiales seleccionados según los checkboxes y
     * comboboxes del panel de Ventana.
     */
    private List<Material> obtenerMaterialesSeleccionados() {
        List<Material> seleccionados = new ArrayList<>();

        // VIDRIO
        if (cmbTipoCristal.getSelectedIndex() > 0) {
            Material m = buscarMaterial(Material.TipoMaterial.VIDRIO, (String) cmbTipoCristal.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        // ARCO
        if (ckArco.isSelected() && cbxTipoArco.getSelectedIndex() > 0) {
            Material m = buscarMaterial(Material.TipoMaterial.ARCO, (String) cbxTipoArco.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        // CANALILLO
        if (cbxTipoCanalillo.getSelectedIndex() > 0) {
            Material m = buscarMaterial(Material.TipoMaterial.CANALILLO, (String) cbxTipoCanalillo.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        // MOSQUITERO (si aplica)
        if (cbxTipoMosquitero.getSelectedIndex() > 0) {
            Material m = buscarMaterial(Material.TipoMaterial.MOSQUITERO, (String) cbxTipoMosquitero.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        return seleccionados;
    }

    /**
     * Busca un material dentro de la lista de materiales disponibles según tipo
     * y descripción.
     */
    private Material buscarMaterial(Material.TipoMaterial tipo, String descripcion) {
        if (materialesDisponibles == null) {
            return null;
        }
        for (Material m : materialesDisponibles) {
            if (m.getTipo() == tipo && m.getDescripcion().equals(descripcion)) {
                return m;
            }
        }
        return null;
    }

    public boolean validar() {

        // Validar medidas
        if (txtMedidaH.getText().trim().isEmpty() || txtMedidaV.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar las medidas horizontal y vertical.");
            return false;
        }

        try {
            BigDecimal h = new BigDecimal(txtMedidaH.getText());
            BigDecimal v = new BigDecimal(txtMedidaV.getText());

            if (h.compareTo(BigDecimal.ZERO) <= 0 || v.compareTo(BigDecimal.ZERO) <= 0) {
                JOptionPane.showMessageDialog(this, "Las medidas deben ser mayores a 0.");
                return false;
            }

            if (h.compareTo(new BigDecimal("10")) > 0 || v.compareTo(new BigDecimal("15")) > 0) {
                JOptionPane.showMessageDialog(this,
                        "Las medidas exceden el máximo permitido:\n10m ancho y 15m alto.");
                return false;
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Las medidas deben ser numéricas.");
            return false;
        }

        // Tipo ventana
        if (cmbTipoVentana.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de ventana.");
            return false;
        }

        // Tipo cristal
        if (cmbTipoCristal.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de cristal.");
            return false;
        }

        // Canalillo
        if (cbxTipoCanalillo.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de canalillo.");
            return false;
        }

        if (txtMedidaCanalillo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la medida del canalillo.");
            return false;
        }

        try {
            BigDecimal canal = new BigDecimal(txtMedidaCanalillo.getText());
            if (canal.compareTo(BigDecimal.ZERO) <= 0) {
                JOptionPane.showMessageDialog(this, "La medida del canalillo debe ser mayor a 0.");
                return false;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "La medida del canalillo debe ser numérica.");
            return false;
        }

        // Arco
        if (ckArco.isSelected()) {
            if (cbxTipoArco.getSelectedIndex() <= 0) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de arco.");
                return false;
            }

            if (txtMedidaArco.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar la medida del arco.");
                return false;
            }

            try {
                BigDecimal arco = new BigDecimal(txtMedidaArco.getText());
                if (arco.compareTo(BigDecimal.ZERO) <= 0) {
                    JOptionPane.showMessageDialog(this, "La medida del arco debe ser mayor a 0.");
                    return false;
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "La medida del arco debe ser numérica.");
                return false;
            }
        }

        // Descripción
        if (txtDescripcion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar una descripción.");
            return false;
        }

        return true;
    }

    private void permitirSoloNumeros(javax.swing.JTextField campo) {
        campo.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c) && c != '.' && c != KeyEvent.VK_BACK_SPACE) {
                    e.consume();
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arco;
    private javax.swing.JLabel cantidad;
    private javax.swing.JComboBox<String> cbxTelas;
    private javax.swing.JComboBox<String> cbxTipoArco;
    private javax.swing.JComboBox<String> cbxTipoCanalillo;
    private javax.swing.JComboBox<String> cbxTipoMosquitero;
    private javax.swing.JComboBox<String> cbxTipoPerfil;
    private javax.swing.JCheckBox ckArco;
    private javax.swing.JCheckBox ckMosquitero;
    private javax.swing.JComboBox<String> cmbTipoCristal;
    private javax.swing.JComboBox<String> cmbTipoVentana;
    private javax.swing.JLabel descripcion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel largoTela;
    private javax.swing.JLabel medidaArcco;
    private javax.swing.JLabel medidaCanalillo;
    private javax.swing.JLabel medidaH;
    private javax.swing.JLabel medidaV;
    private javax.swing.JLabel mosquitero;
    private javax.swing.JLabel noEscuadras;
    private javax.swing.JLabel noHojas;
    private javax.swing.JPanel panelDetalleVentana;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JSpinner spnNoEscuadras;
    private javax.swing.JSpinner spnNoHojas;
    private javax.swing.JLabel tela;
    private javax.swing.JLabel tipoArco;
    private javax.swing.JLabel tipoCanalillo;
    private javax.swing.JLabel tipoCristal;
    private javax.swing.JLabel tipoMosquitero;
    private javax.swing.JLabel tipoPerfil;
    private javax.swing.JLabel tipoVentana;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtLargoTela;
    private javax.swing.JTextField txtMedidaArco;
    private javax.swing.JTextField txtMedidaCanalillo;
    private javax.swing.JTextField txtMedidaH;
    private javax.swing.JTextField txtMedidaV;
    // End of variables declaration//GEN-END:variables
}
