/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Material;
import modelo.TipoPuerta;
import modelo.PuertaAbatibleDetalle;
import dao.CatalogoTrabajoDAO;
import dao.MaterialDetalleDAO;
import dao.PuertaAbatibleDetalleDAO;
import java.awt.Window;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;
import modelo.MaterialDetalle;
import utils.Conexion;

/**
 *
 * @author User
 */
public class PanelDetallePuertaAbatible extends javax.swing.JPanel {

    private List<Material> materialesDisponibles; // Para cristales, accesorios
    private CatalogoTrabajoDAO catalogoDAO;

    /**
     * Creates new form PanelDetallePuertaAbatible
     */
    public PanelDetallePuertaAbatible() {
        initComponents();
        configurarListeners();
    }

    /**
     * Prepara el panel
     *
     * @param materiales La lista de materiales
     */
    public void inicializarDatos(List<Material> materiales) {
        this.materialesDisponibles = materiales;
        try {
            this.catalogoDAO = new CatalogoTrabajoDAO(utils.Conexion.getConnection());
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al conectar con BD para Catálogo", "Error DB", JOptionPane.ERROR_MESSAGE);
        }

        cargarDatosComboBox();

        // Configurar los Spinners (de 1 a 100)
        spnCantidad.setModel(new SpinnerNumberModel(1, 1, 100, 1));
        spnNoHojas.setModel(new SpinnerNumberModel(1, 1, 100, 1));
        // Spinners para accesorios (permiten 0)
        spnCantidadPivote.setModel(new SpinnerNumberModel(0, 0, 10, 1));
        spnCantidadJaladera.setModel(new SpinnerNumberModel(0, 0, 10, 1));

        // Validar campos de texto
        permitirSoloNumeros(txtMedidaH);
        permitirSoloNumeros(txtMedidaV);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDetalleVentana = new javax.swing.JPanel();
        medidaH = new javax.swing.JLabel();
        txtMedidaH = new javax.swing.JTextField();
        medidaV = new javax.swing.JLabel();
        txtMedidaV = new javax.swing.JTextField();
        panelTitulo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        tipoCristal = new javax.swing.JLabel();
        cmbTipoCristal = new javax.swing.JComboBox<>();
        noHojas = new javax.swing.JLabel();
        spnNoHojas = new javax.swing.JSpinner();
        tipoPuerta = new javax.swing.JLabel();
        cmbTipoPuerta = new javax.swing.JComboBox<>();
        mosquitero = new javax.swing.JLabel();
        ckMosquitero = new javax.swing.JCheckBox();
        duela = new javax.swing.JLabel();
        ckDuela = new javax.swing.JCheckBox();
        tipoArco = new javax.swing.JLabel();
        cbxTipoDuela = new javax.swing.JComboBox<>();
        medidaDuela = new javax.swing.JLabel();
        txtMedidaDuela = new javax.swing.JTextField();
        tipoAdaptador = new javax.swing.JLabel();
        cbxTipoAdaptador = new javax.swing.JComboBox<>();
        adaptador = new javax.swing.JLabel();
        ckAdaptador = new javax.swing.JCheckBox();
        juanquillo = new javax.swing.JLabel();
        tipoJunquillo = new javax.swing.JLabel();
        ckJunquillo = new javax.swing.JCheckBox();
        cbxTipoJunquillo = new javax.swing.JComboBox<>();
        canal = new javax.swing.JLabel();
        ckCanal = new javax.swing.JCheckBox();
        tipoCanal = new javax.swing.JLabel();
        cbxTipoCanal = new javax.swing.JComboBox<>();
        pivote = new javax.swing.JLabel();
        ckPivote = new javax.swing.JCheckBox();
        tipoPivote = new javax.swing.JLabel();
        cbxTipoPivote = new javax.swing.JComboBox<>();
        cantidadPivote = new javax.swing.JLabel();
        spnCantidadPivote = new javax.swing.JSpinner();
        jaladera = new javax.swing.JLabel();
        ckJaladera = new javax.swing.JCheckBox();
        tipoJaladera = new javax.swing.JLabel();
        cbxTipoJaladera = new javax.swing.JComboBox<>();
        cantidadJaladera = new javax.swing.JLabel();
        spnCantidadJaladera = new javax.swing.JSpinner();
        barra = new javax.swing.JLabel();
        ckBarra = new javax.swing.JCheckBox();
        tipoBarra = new javax.swing.JLabel();
        cbxTipoBarra = new javax.swing.JComboBox<>();
        descripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();

        panelDetalleVentana.setBackground(new java.awt.Color(255, 255, 255));

        medidaH.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medidaH.setForeground(new java.awt.Color(0, 38, 115));
        medidaH.setText("Medida horizontal (m):");

        txtMedidaH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        medidaV.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medidaV.setForeground(new java.awt.Color(0, 38, 115));
        medidaV.setText("Medida vertical (m):");

        txtMedidaV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        panelTitulo.setBackground(new java.awt.Color(0, 19, 90));

        titulo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Detalles de Puerta Abatible");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(10, 10, 10))
        );

        cantidad.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cantidad.setForeground(new java.awt.Color(0, 38, 115));
        cantidad.setText("Cantidad:");

        tipoCristal.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoCristal.setForeground(new java.awt.Color(0, 38, 115));
        tipoCristal.setText("Tipo cristal:");

        cmbTipoCristal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTipoCristal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoCristal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoCristalActionPerformed(evt);
            }
        });

        noHojas.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        noHojas.setForeground(new java.awt.Color(0, 38, 115));
        noHojas.setText("No. hojas:");

        tipoPuerta.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoPuerta.setForeground(new java.awt.Color(0, 38, 115));
        tipoPuerta.setText("Tipo puerta:");

        cmbTipoPuerta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTipoPuerta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        mosquitero.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        mosquitero.setForeground(new java.awt.Color(0, 38, 115));
        mosquitero.setText("Mosquitero:");

        ckMosquitero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckMosquitero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckMosquiteroActionPerformed(evt);
            }
        });

        duela.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        duela.setForeground(new java.awt.Color(0, 38, 115));
        duela.setText("Duela:");

        ckDuela.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckDuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckDuelaActionPerformed(evt);
            }
        });

        tipoArco.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoArco.setForeground(new java.awt.Color(0, 38, 115));
        tipoArco.setText("Tipo duela:");

        cbxTipoDuela.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoDuela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoDuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoDuelaActionPerformed(evt);
            }
        });

        medidaDuela.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        medidaDuela.setForeground(new java.awt.Color(0, 38, 115));
        medidaDuela.setText("Medida duela(m):");

        txtMedidaDuela.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMedidaDuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedidaDuelaActionPerformed(evt);
            }
        });

        tipoAdaptador.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoAdaptador.setForeground(new java.awt.Color(0, 38, 115));
        tipoAdaptador.setText("Tipo adaptador:");

        cbxTipoAdaptador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoAdaptador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoAdaptador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoAdaptadorActionPerformed(evt);
            }
        });

        adaptador.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        adaptador.setForeground(new java.awt.Color(0, 38, 115));
        adaptador.setText("Adaptador:");

        ckAdaptador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckAdaptador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckAdaptadorActionPerformed(evt);
            }
        });

        juanquillo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        juanquillo.setForeground(new java.awt.Color(0, 38, 115));
        juanquillo.setText("Junquillo:");

        tipoJunquillo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoJunquillo.setForeground(new java.awt.Color(0, 38, 115));
        tipoJunquillo.setText("Tipo junquillo:");

        ckJunquillo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckJunquillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckJunquilloActionPerformed(evt);
            }
        });

        cbxTipoJunquillo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoJunquillo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoJunquillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoJunquilloActionPerformed(evt);
            }
        });

        canal.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        canal.setForeground(new java.awt.Color(0, 38, 115));
        canal.setText("Canal:");

        ckCanal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckCanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckCanalActionPerformed(evt);
            }
        });

        tipoCanal.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoCanal.setForeground(new java.awt.Color(0, 38, 115));
        tipoCanal.setText("Tipo canal:");

        cbxTipoCanal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoCanal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoCanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoCanalActionPerformed(evt);
            }
        });

        pivote.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        pivote.setForeground(new java.awt.Color(0, 38, 115));
        pivote.setText("Pivote:");

        ckPivote.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckPivote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckPivoteActionPerformed(evt);
            }
        });

        tipoPivote.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoPivote.setForeground(new java.awt.Color(0, 38, 115));
        tipoPivote.setText("Tipo pivote:");

        cbxTipoPivote.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoPivote.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoPivote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoPivoteActionPerformed(evt);
            }
        });

        cantidadPivote.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cantidadPivote.setForeground(new java.awt.Color(0, 38, 115));
        cantidadPivote.setText("Cantidad pivote:");

        jaladera.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jaladera.setForeground(new java.awt.Color(0, 38, 115));
        jaladera.setText("Jaladera:");

        ckJaladera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckJaladera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckJaladeraActionPerformed(evt);
            }
        });

        tipoJaladera.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoJaladera.setForeground(new java.awt.Color(0, 38, 115));
        tipoJaladera.setText("Tipo jaladera:");

        cbxTipoJaladera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoJaladera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoJaladera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoJaladeraActionPerformed(evt);
            }
        });

        cantidadJaladera.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cantidadJaladera.setForeground(new java.awt.Color(0, 38, 115));
        cantidadJaladera.setText("Cantidad jaladera:");

        barra.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        barra.setForeground(new java.awt.Color(0, 38, 115));
        barra.setText("Barra:");

        ckBarra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckBarraActionPerformed(evt);
            }
        });

        tipoBarra.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tipoBarra.setForeground(new java.awt.Color(0, 38, 115));
        tipoBarra.setText("Tipo barra:");

        cbxTipoBarra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoBarra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoBarraActionPerformed(evt);
            }
        });

        descripcion.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        descripcion.setForeground(new java.awt.Color(0, 38, 115));
        descripcion.setText("Descripción:");

        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDetalleVentanaLayout = new javax.swing.GroupLayout(panelDetalleVentana);
        panelDetalleVentana.setLayout(panelDetalleVentanaLayout);
        panelDetalleVentanaLayout.setHorizontalGroup(
            panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addComponent(medidaDuela, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtMedidaDuela, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(medidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMedidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tipoArco, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(duela, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckDuela)
                                    .addComponent(cbxTipoDuela, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTipoPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbTipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnNoHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxTipoJunquillo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxTipoCanal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ckCanal)
                                            .addComponent(ckJunquillo))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addComponent(mosquitero, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(ckMosquitero))
                            .addComponent(tipoCanal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(juanquillo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoJunquillo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(canal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adaptador, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoAdaptador, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ckAdaptador)
                                    .addComponent(txtDescripcion)
                                    .addComponent(cbxTipoAdaptador, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(25, 25, 25)
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jaladera, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoJaladera, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                            .addGap(180, 180, 180)
                            .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbxTipoJaladera, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ckJaladera)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalleVentanaLayout.createSequentialGroup()
                            .addComponent(cantidadJaladera, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(spnCantidadJaladera, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pivote, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tipoPivote, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                            .addComponent(cantidadPivote, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(spnCantidadPivote, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxTipoBarra, 0, 160, Short.MAX_VALUE)
                            .addComponent(ckBarra)
                            .addComponent(ckPivote)
                            .addComponent(cbxTipoPivote, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );
        panelDetalleVentanaLayout.setVerticalGroup(
            panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                        .addComponent(txtMedidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(txtMedidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                        .addComponent(medidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(medidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckPivote, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pivote, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxTipoPivote, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoPivote, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cantidadPivote, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnCantidadPivote, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tipoPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbTipoPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbTipoCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(noHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnNoHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(duela, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ckDuela, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(tipoArco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbxTipoDuela, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMedidaDuela, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(medidaDuela, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckJaladera, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jaladera, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxTipoJaladera, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoJaladera, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cantidadJaladera, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnCantidadJaladera, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxTipoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mosquitero, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckMosquitero, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addComponent(adaptador, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipoAdaptador, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDetalleVentanaLayout.createSequentialGroup()
                                .addComponent(ckAdaptador, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxTipoAdaptador, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckJunquillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(juanquillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTipoJunquillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoJunquillo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckCanal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(canal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDetalleVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTipoCanal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoCanal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDetalleVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDetalleVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 395, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ckAdaptadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckAdaptadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckAdaptadorActionPerformed

    private void cbxTipoAdaptadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoAdaptadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoAdaptadorActionPerformed

    private void cbxTipoDuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoDuelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoDuelaActionPerformed

    private void ckDuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckDuelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckDuelaActionPerformed

    private void ckMosquiteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckMosquiteroActionPerformed
        Window parent = SwingUtilities.getWindowAncestor(this);
        MaterialMosquiteras dlg = new MaterialMosquiteras(parent, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_ckMosquiteroActionPerformed

    private void cmbTipoCristalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoCristalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoCristalActionPerformed

    private void ckJunquilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckJunquilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckJunquilloActionPerformed

    private void cbxTipoJunquilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoJunquilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoJunquilloActionPerformed

    private void ckCanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckCanalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckCanalActionPerformed

    private void cbxTipoCanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoCanalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoCanalActionPerformed

    private void ckPivoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckPivoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckPivoteActionPerformed

    private void cbxTipoPivoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoPivoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoPivoteActionPerformed

    private void txtMedidaDuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedidaDuelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedidaDuelaActionPerformed

    private void ckJaladeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckJaladeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckJaladeraActionPerformed

    private void cbxTipoJaladeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoJaladeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoJaladeraActionPerformed

    private void ckBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckBarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckBarraActionPerformed

    private void cbxTipoBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoBarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoBarraActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    /**
     * Carga los ComboBoxes con datos filtrando por tipo de material o desde el
     * Enum.
     */
    private void cargarDatosComboBox() {
        // ===============================
        // Tipo de Puerta
        // ===============================
        cmbTipoPuerta.removeAllItems();
        cmbTipoPuerta.addItem("Seleccione una opción...");
        for (modelo.TipoPuerta tp : modelo.TipoPuerta.values()) {
            cmbTipoPuerta.addItem(tp.getDescripcion());
        }
        cmbTipoPuerta.setSelectedIndex(0);

        // ===============================
        // Materiales (Cristal, Duela, Adaptador, etc.)
        // ===============================
        cargarComboPorTipoConOpcionInicial(cmbTipoCristal, Material.TipoMaterial.VIDRIO);
        cargarComboPorTipoConOpcionInicial(cbxTipoDuela, Material.TipoMaterial.DUELA);
        cargarComboPorTipoConOpcionInicial(cbxTipoAdaptador, Material.TipoMaterial.ADAPTADOR);
        cargarComboPorTipoConOpcionInicial(cbxTipoJunquillo, Material.TipoMaterial.JUNQUILLO);
        cargarComboPorTipoConOpcionInicial(cbxTipoCanal, Material.TipoMaterial.CANALILLO);
        cargarComboPorTipoConOpcionInicial(cbxTipoJaladera, Material.TipoMaterial.JALADERA);
        cargarComboPorTipoConOpcionInicial(cbxTipoBarra, Material.TipoMaterial.BARRA);
        cargarComboPorTipoConOpcionInicial(cbxTipoPivote, Material.TipoMaterial.PIVOTE);
    }

    /**
     * Llena un JComboBox filtrando la lista de materiales por el tipo de
     * material.
     *
     * @param combo El JComboBox a llenar.
     * @param tipo El tipo de material a filtrar.
     */
    private void cargarComboPorTipoConOpcionInicial(JComboBox<String> combo, Material.TipoMaterial tipo) {
        combo.removeAllItems();
        combo.addItem("Seleccione una opción");

        if (materialesDisponibles != null && !materialesDisponibles.isEmpty()) {
            for (Material m : materialesDisponibles) {
                if (m.getTipo() == tipo) {
                    combo.addItem(m.getDescripcion());
                }
            }
        } else {
            combo.addItem("Error al cargar");
        }

        combo.setSelectedIndex(0);
    }

    /**
     * Configura los listeners para habilitar/deshabilitar campos.
     */
    private void configurarListeners() {

        // Duela
        cbxTipoDuela.setEnabled(false);
        txtMedidaDuela.setEnabled(false);
        ckDuela.addActionListener(e -> {
            boolean sel = ckDuela.isSelected();
            cbxTipoDuela.setEnabled(sel);
            txtMedidaDuela.setEnabled(sel);
            if (!sel) {
                cbxTipoDuela.setSelectedIndex(0);
                txtMedidaDuela.setText("");
            }
        });

        //Adaptador
        cbxTipoAdaptador.setEnabled(false);
        ckAdaptador.addActionListener(e -> {
            boolean sel = ckAdaptador.isSelected();
            cbxTipoAdaptador.setEnabled(sel);
            if (!sel) {
                cbxTipoAdaptador.setSelectedIndex(0);
            }
        });

        // Junquillo
        cbxTipoJunquillo.setEnabled(false);
        ckJunquillo.addActionListener(e -> {
            boolean sel = ckJunquillo.isSelected();
            cbxTipoJunquillo.setEnabled(sel);
            if (!sel) {
                cbxTipoJunquillo.setSelectedIndex(0);
            }
        });

        // Canal 
        cbxTipoCanal.setEnabled(false);
        ckCanal.addActionListener(e -> {
            boolean sel = ckCanal.isSelected();
            cbxTipoCanal.setEnabled(sel);
            if (!sel) {
                cbxTipoCanal.setSelectedIndex(0);
            }
        });

        // Pivote
        cbxTipoPivote.setEnabled(false);
        spnCantidadPivote.setEnabled(false);
        ckPivote.addActionListener(e -> {
            boolean sel = ckPivote.isSelected();
            cbxTipoPivote.setEnabled(sel);
            spnCantidadPivote.setEnabled(sel);
            if (!sel) {
                cbxTipoPivote.setSelectedIndex(0);
                spnCantidadPivote.setValue(0);
            }
        });

        // Jaladera
        cbxTipoJaladera.setEnabled(false);
        spnCantidadJaladera.setEnabled(false);
        ckJaladera.addActionListener(e -> {
            boolean sel = ckJaladera.isSelected();
            cbxTipoJaladera.setEnabled(sel);
            spnCantidadJaladera.setEnabled(sel);
            if (!sel) {
                cbxTipoJaladera.setSelectedIndex(0);
                spnCantidadJaladera.setValue(0);
            }
        });

        // Barra 
        cbxTipoBarra.setEnabled(false);
        ckBarra.addActionListener(e -> {
            boolean sel = ckBarra.isSelected();
            cbxTipoBarra.setEnabled(sel);
            if (!sel) {
                cbxTipoBarra.setSelectedIndex(0);
            }
        });
    }

    /**
     * Lee todos los campos del panel y crea un objeto PuertaAbatibleDetalle.
     *
     * @return El objeto PuertaAbatibleDetalle con los datos del formulario.
     */
    public modelo.PuertaAbatibleDetalle getDetalle() {
        modelo.PuertaAbatibleDetalle d = new modelo.PuertaAbatibleDetalle();

        try {
            // ---- VALIDACIONES BÁSICAS ----

            if (catalogoDAO != null) {
                d.setTipoTrabajo(catalogoDAO.obtenerPorId(2));
            } else {
                throw new RuntimeException("CatalogoDAO no inicializado.");
            }

            // 1. Validar medidas obligatorias
            if (txtMedidaH.getText().trim().isEmpty() || txtMedidaV.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar las medidas horizontal y vertical.",
                        "Campos obligatorios", JOptionPane.WARNING_MESSAGE);
                return null;
            }

            BigDecimal medidaH, medidaV;
            try {
                medidaH = new BigDecimal(txtMedidaH.getText());
                medidaV = new BigDecimal(txtMedidaV.getText());

                // Medidas no pueden ser 0 o negativas
                if (medidaH.compareTo(BigDecimal.ZERO) <= 0 || medidaV.compareTo(BigDecimal.ZERO) <= 0) {
                    JOptionPane.showMessageDialog(this, "Las medidas deben ser mayores que cero.",
                            "Valor inválido", JOptionPane.WARNING_MESSAGE);
                    return null;
                }

                // ✅ VALIDAR RANGO MÁXIMO
                BigDecimal maxH = new BigDecimal("15"); // ancho máximo
                BigDecimal maxV = new BigDecimal("10"); // alto máximo

                if (medidaH.compareTo(maxH) > 0 || medidaV.compareTo(maxV) > 0) {
                    JOptionPane.showMessageDialog(this,
                            "Las medidas exceden el rango permitido.\nMáximo: 15m de ancho y 10m de alto.",
                            "Medidas fuera de rango", JOptionPane.WARNING_MESSAGE);
                    return null;
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Las medidas deben ser numéricas válidas.",
                        "Error de formato", JOptionPane.ERROR_MESSAGE);
                return null;
            }

            // 2. Validar combos obligatorios
            if (cmbTipoPuerta.getSelectedIndex() < 0) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de puerta.",
                        "Falta selección", JOptionPane.WARNING_MESSAGE);
                return null;
            }
            if (cmbTipoCristal.getSelectedIndex() < 0 || "Error al cargar".equals(cmbTipoCristal.getSelectedItem())) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de cristal válido.",
                        "Falta selección", JOptionPane.WARNING_MESSAGE);
                return null;
            }

            // 3. Validaciones condicionales
            if (ckDuela.isSelected()) {
                if (cbxTipoDuela.getSelectedIndex() < 0) {
                    JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de duela.",
                            "Falta selección", JOptionPane.WARNING_MESSAGE);
                    return null;
                }
                try {
                    new BigDecimal(txtMedidaDuela.getText());
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "La medida de la duela debe ser numérica.",
                            "Error de formato", JOptionPane.ERROR_MESSAGE);
                    return null;
                }
            }

            if (ckPivote.isSelected() && cbxTipoPivote.getSelectedIndex() < 0) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de pivote.",
                        "Falta selección", JOptionPane.WARNING_MESSAGE);
                return null;
            }

            if (ckJaladera.isSelected() && cbxTipoJaladera.getSelectedIndex() < 0) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de jaladera.",
                        "Falta selección", JOptionPane.WARNING_MESSAGE);
                return null;
            }

            // ---- CONSTRUCCIÓN DEL OBJETO ----
            d.setMedidaHorizontal(medidaH);
            d.setMedidaVertical(medidaV);
            d.setCantidad((Integer) spnCantidad.getValue());
            d.setTipoCristal((String) cmbTipoCristal.getSelectedItem());
            d.setNoHojas((Integer) spnNoHojas.getValue());
            d.setDescripcion(txtDescripcion.getText());

            String descPuerta = (String) cmbTipoPuerta.getSelectedItem();
            d.setTipoPuerta(modelo.TipoPuerta.fromDescripcion(descPuerta));
            d.setMosquitero(ckMosquitero.isSelected());

            d.setDuela(ckDuela.isSelected());
            d.setTipoDuela(ckDuela.isSelected() ? (String) cbxTipoDuela.getSelectedItem() : null);
            d.setMedidaDuela(new BigDecimal(txtMedidaDuela.getText().isEmpty() ? "0" : txtMedidaDuela.getText()));

            d.setAdaptador(ckAdaptador.isSelected());
            d.setTipoAdaptador(ckAdaptador.isSelected() ? (String) cbxTipoAdaptador.getSelectedItem() : null);

            d.setJunquillo(ckJunquillo.isSelected());
            d.setTipoJunquillo(ckJunquillo.isSelected() ? (String) cbxTipoJunquillo.getSelectedItem() : null);

            d.setCanal(ckCanal.isSelected());
            d.setTipoCanal(ckCanal.isSelected() ? (String) cbxTipoCanal.getSelectedItem() : null);

            d.setPivote(ckPivote.isSelected());
            d.setTipoPivote(ckPivote.isSelected() ? (String) cbxTipoPivote.getSelectedItem() : null);
            d.setCantidadPivote((Integer) spnCantidadPivote.getValue());

            d.setJaladera(ckJaladera.isSelected());
            d.setTipoJaladera(ckJaladera.isSelected() ? (String) cbxTipoJaladera.getSelectedItem() : null);
            d.setCantidadJaladera((Integer) spnCantidadJaladera.getValue());

            d.setBarra(ckBarra.isSelected());
            d.setTipoBarra(ckBarra.isSelected() ? (String) cbxTipoBarra.getSelectedItem() : null);

            // Materiales seleccionados
            List<Material> materialesSeleccionados = obtenerMaterialesSeleccionados();
            List<MaterialDetalle> materialesDetalle = new ArrayList<>();

            for (Material m : materialesSeleccionados) {
                BigDecimal cantidad = BigDecimal.valueOf(d.getCantidad());
                BigDecimal precioUnitario = m.getPrecio();
                materialesDetalle.add(new MaterialDetalle(m, cantidad, precioUnitario));
            }

            d.setMateriales(materialesDetalle);

            BigDecimal subtotal = BigDecimal.ZERO;
            for (MaterialDetalle md : materialesDetalle) {
                subtotal = subtotal.add(md.getPrecioTotal());
            }
            d.setPrecioSoloUnaUnidadCalculado(subtotal);
            d.setSubtotalLinea(subtotal);

        } catch (Exception e) {
            System.err.println("Error al leer datos del panel de puerta: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Error en los datos: " + e.getMessage(),
                    "Error de Formato", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        return d;
    }

    /**
     * Llena los campos del panel de puerta con los datos de un detalle
     * existente para editar.
     *
     * @param detalle El detalle a cargar en el formulario.
     */
    public void setDetalle(modelo.PuertaAbatibleDetalle detalle) {
        if (detalle == null) {
            return;
        }

        // Medidas y cantidad
        txtMedidaH.setText(detalle.getMedidaHorizontal().toPlainString());
        txtMedidaV.setText(detalle.getMedidaVertical().toPlainString());
        spnCantidad.setValue(detalle.getCantidad());

        // Tipo de cristal y número de hojas
        cmbTipoCristal.setSelectedItem(detalle.getTipoCristal());
        spnNoHojas.setValue(detalle.getNoHojas());

        // Descripción
        txtDescripcion.setText(detalle.getDescripcion());

        // Tipo de puerta (del enum)
        if (detalle.getTipoPuerta() != null) {
            cmbTipoPuerta.setSelectedItem(detalle.getTipoPuerta().getDescripcion());
        }

        // Mosquitero
        ckMosquitero.setSelected(detalle.isMosquitero());

        // Duela
        ckDuela.setSelected(detalle.isDuela());
        cbxTipoDuela.setSelectedItem(detalle.getTipoDuela());
        txtMedidaDuela.setText(detalle.getMedidaDuela() != null ? detalle.getMedidaDuela().toPlainString() : "");
        cbxTipoDuela.setEnabled(detalle.isDuela());
        txtMedidaDuela.setEnabled(detalle.isDuela());

        // Adaptador
        ckAdaptador.setSelected(detalle.isAdaptador());
        cbxTipoAdaptador.setSelectedItem(detalle.getTipoAdaptador());
        cbxTipoAdaptador.setEnabled(detalle.isAdaptador());

        // Junquillo
        ckJunquillo.setSelected(detalle.isJunquillo());
        cbxTipoJunquillo.setSelectedItem(detalle.getTipoJunquillo());
        cbxTipoJunquillo.setEnabled(detalle.isJunquillo());

        // Canal
        ckCanal.setSelected(detalle.isCanal());
        cbxTipoCanal.setSelectedItem(detalle.getTipoCanal());
        cbxTipoCanal.setEnabled(detalle.isCanal());

        // Pivote
        ckPivote.setSelected(detalle.isPivote());
        cbxTipoPivote.setSelectedItem(detalle.getTipoPivote());
        spnCantidadPivote.setValue(detalle.getCantidadPivote());
        cbxTipoPivote.setEnabled(detalle.isPivote());
        spnCantidadPivote.setEnabled(detalle.isPivote());

        // Jaladera
        ckJaladera.setSelected(detalle.isJaladera());
        cbxTipoJaladera.setSelectedItem(detalle.getTipoJaladera());
        spnCantidadJaladera.setValue(detalle.getCantidadJaladera());
        cbxTipoJaladera.setEnabled(detalle.isJaladera());
        spnCantidadJaladera.setEnabled(detalle.isJaladera());

        // Barra
        ckBarra.setSelected(detalle.isBarra());
        cbxTipoBarra.setSelectedItem(detalle.getTipoBarra());
        cbxTipoBarra.setEnabled(detalle.isBarra());
    }

    /**
     * Devuelve la lista de materiales seleccionados según los checkboxes y
     * comboboxes de la puerta abatible.
     */
    private List<Material> obtenerMaterialesSeleccionados() {
        List<Material> seleccionados = new ArrayList<>();

        // Duela
        if (ckDuela.isSelected() && cbxTipoDuela.getSelectedItem() != null) {
            Material m = buscarMaterial(Material.TipoMaterial.DUELA, (String) cbxTipoDuela.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        // Adaptador
        if (ckAdaptador.isSelected() && cbxTipoAdaptador.getSelectedItem() != null) {
            Material m = buscarMaterial(Material.TipoMaterial.ADAPTADOR, (String) cbxTipoAdaptador.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        // Junquillo
        if (ckJunquillo.isSelected() && cbxTipoJunquillo.getSelectedItem() != null) {
            Material m = buscarMaterial(Material.TipoMaterial.JUNQUILLO, (String) cbxTipoJunquillo.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        // Canal
        if (ckCanal.isSelected() && cbxTipoCanal.getSelectedItem() != null) {
            Material m = buscarMaterial(Material.TipoMaterial.CANALILLO, (String) cbxTipoCanal.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        // Pivote
        if (ckPivote.isSelected() && cbxTipoPivote.getSelectedItem() != null) {
            Material m = buscarMaterial(Material.TipoMaterial.PIVOTE, (String) cbxTipoPivote.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        // Jaladera
        if (ckJaladera.isSelected() && cbxTipoJaladera.getSelectedItem() != null) {
            Material m = buscarMaterial(Material.TipoMaterial.JALADERA, (String) cbxTipoJaladera.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        // Barra
        if (ckBarra.isSelected() && cbxTipoBarra.getSelectedItem() != null) {
            Material m = buscarMaterial(Material.TipoMaterial.BARRA, (String) cbxTipoBarra.getSelectedItem());
            if (m != null) {
                seleccionados.add(m);
            }
        }

        // Mosquitero (si aplica como material)
        if (ckMosquitero.isSelected()) {
            Material m = buscarMaterial(Material.TipoMaterial.MOSQUITERO, "Mosquitero");
            if (m != null) {
                seleccionados.add(m);
            }
        }

        return seleccionados;
    }

    /**
     * Busca un material dentro de la lista de materiales disponibles según tipo
     * y descripción.
     */
    private Material buscarMaterial(Material.TipoMaterial tipo, String descripcion) {
        for (Material m : materialesDisponibles) {
            if (m.getTipo() == tipo && m.getDescripcion().equals(descripcion)) {
                return m;
            }
        }
        return null;
    }

    private void permitirSoloNumeros(javax.swing.JTextField campo) {
        campo.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                char c = e.getKeyChar();
                // Permitir solo dígitos, punto decimal o borrar
                if (!Character.isDigit(c) && c != '.' && c != KeyEvent.VK_BACK_SPACE) {
                    e.consume();
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adaptador;
    private javax.swing.JLabel barra;
    private javax.swing.JLabel canal;
    private javax.swing.JLabel cantidad;
    private javax.swing.JLabel cantidadJaladera;
    private javax.swing.JLabel cantidadPivote;
    private javax.swing.JComboBox<String> cbxTipoAdaptador;
    private javax.swing.JComboBox<String> cbxTipoBarra;
    private javax.swing.JComboBox<String> cbxTipoCanal;
    private javax.swing.JComboBox<String> cbxTipoDuela;
    private javax.swing.JComboBox<String> cbxTipoJaladera;
    private javax.swing.JComboBox<String> cbxTipoJunquillo;
    private javax.swing.JComboBox<String> cbxTipoPivote;
    private javax.swing.JCheckBox ckAdaptador;
    private javax.swing.JCheckBox ckBarra;
    private javax.swing.JCheckBox ckCanal;
    private javax.swing.JCheckBox ckDuela;
    private javax.swing.JCheckBox ckJaladera;
    private javax.swing.JCheckBox ckJunquillo;
    private javax.swing.JCheckBox ckMosquitero;
    private javax.swing.JCheckBox ckPivote;
    private javax.swing.JComboBox<String> cmbTipoCristal;
    private javax.swing.JComboBox<String> cmbTipoPuerta;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel duela;
    private javax.swing.JLabel jaladera;
    private javax.swing.JLabel juanquillo;
    private javax.swing.JLabel medidaDuela;
    private javax.swing.JLabel medidaH;
    private javax.swing.JLabel medidaV;
    private javax.swing.JLabel mosquitero;
    private javax.swing.JLabel noHojas;
    private javax.swing.JPanel panelDetalleVentana;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JLabel pivote;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JSpinner spnCantidadJaladera;
    private javax.swing.JSpinner spnCantidadPivote;
    private javax.swing.JSpinner spnNoHojas;
    private javax.swing.JLabel tipoAdaptador;
    private javax.swing.JLabel tipoArco;
    private javax.swing.JLabel tipoBarra;
    private javax.swing.JLabel tipoCanal;
    private javax.swing.JLabel tipoCristal;
    private javax.swing.JLabel tipoJaladera;
    private javax.swing.JLabel tipoJunquillo;
    private javax.swing.JLabel tipoPivote;
    private javax.swing.JLabel tipoPuerta;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtMedidaDuela;
    private javax.swing.JTextField txtMedidaH;
    private javax.swing.JTextField txtMedidaV;
    // End of variables declaration//GEN-END:variables
}
